# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import shardrpc_pb2 as shardrpc__pb2


class ShardRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubscribeToShard = channel.unary_unary(
        '/pb.ShardRPC/SubscribeToShard',
        request_serializer=shardrpc__pb2.ShardSubscribeRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetBlockHashAtSlot = channel.unary_unary(
        '/pb.ShardRPC/GetBlockHashAtSlot',
        request_serializer=shardrpc__pb2.SlotRequest.SerializeToString,
        response_deserializer=shardrpc__pb2.BlockHashResponse.FromString,
        )
    self.GenerateBlockTemplate = channel.unary_unary(
        '/pb.ShardRPC/GenerateBlockTemplate',
        request_serializer=shardrpc__pb2.BlockGenerationRequest.SerializeToString,
        response_deserializer=common__pb2.ShardBlock.FromString,
        )
    self.SubmitBlock = channel.unary_unary(
        '/pb.ShardRPC/SubmitBlock',
        request_serializer=shardrpc__pb2.ShardBlockSubmission.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SubmitTransaction = channel.unary_unary(
        '/pb.ShardRPC/SubmitTransaction',
        request_serializer=shardrpc__pb2.ShardTransactionSubmission.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetStateKey = channel.unary_unary(
        '/pb.ShardRPC/GetStateKey',
        request_serializer=shardrpc__pb2.GetStateKeyRequest.SerializeToString,
        response_deserializer=shardrpc__pb2.GetStateKeyResponse.FromString,
        )
    self.GetActionStream = channel.unary_stream(
        '/pb.ShardRPC/GetActionStream',
        request_serializer=shardrpc__pb2.ShardActionStreamRequest.SerializeToString,
        response_deserializer=shardrpc__pb2.ShardChainAction.FromString,
        )
    self.GetListeningAddresses = channel.unary_unary(
        '/pb.ShardRPC/GetListeningAddresses',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=common__pb2.ListeningAddressesResponse.FromString,
        )
    self.Connect = channel.unary_unary(
        '/pb.ShardRPC/Connect',
        request_serializer=common__pb2.ConnectMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetSlotNumber = channel.unary_unary(
        '/pb.ShardRPC/GetSlotNumber',
        request_serializer=shardrpc__pb2.SlotNumberRequest.SerializeToString,
        response_deserializer=common__pb2.SlotNumberResponse.FromString,
        )


class ShardRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubscribeToShard(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockHashAtSlot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateBlockTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStateKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetActionStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetListeningAddresses(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSlotNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShardRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubscribeToShard': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeToShard,
          request_deserializer=shardrpc__pb2.ShardSubscribeRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetBlockHashAtSlot': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockHashAtSlot,
          request_deserializer=shardrpc__pb2.SlotRequest.FromString,
          response_serializer=shardrpc__pb2.BlockHashResponse.SerializeToString,
      ),
      'GenerateBlockTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateBlockTemplate,
          request_deserializer=shardrpc__pb2.BlockGenerationRequest.FromString,
          response_serializer=common__pb2.ShardBlock.SerializeToString,
      ),
      'SubmitBlock': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitBlock,
          request_deserializer=shardrpc__pb2.ShardBlockSubmission.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SubmitTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitTransaction,
          request_deserializer=shardrpc__pb2.ShardTransactionSubmission.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetStateKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetStateKey,
          request_deserializer=shardrpc__pb2.GetStateKeyRequest.FromString,
          response_serializer=shardrpc__pb2.GetStateKeyResponse.SerializeToString,
      ),
      'GetActionStream': grpc.unary_stream_rpc_method_handler(
          servicer.GetActionStream,
          request_deserializer=shardrpc__pb2.ShardActionStreamRequest.FromString,
          response_serializer=shardrpc__pb2.ShardChainAction.SerializeToString,
      ),
      'GetListeningAddresses': grpc.unary_unary_rpc_method_handler(
          servicer.GetListeningAddresses,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=common__pb2.ListeningAddressesResponse.SerializeToString,
      ),
      'Connect': grpc.unary_unary_rpc_method_handler(
          servicer.Connect,
          request_deserializer=common__pb2.ConnectMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetSlotNumber': grpc.unary_unary_rpc_method_handler(
          servicer.GetSlotNumber,
          request_deserializer=shardrpc__pb2.SlotNumberRequest.FromString,
          response_serializer=common__pb2.SlotNumberResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.ShardRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
