// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beaconrpc.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MempoolRequest struct {
	LastBlockHash        []byte   `protobuf:"bytes,1,opt,name=LastBlockHash,proto3" json:"LastBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MempoolRequest) Reset()         { *m = MempoolRequest{} }
func (m *MempoolRequest) String() string { return proto.CompactTextString(m) }
func (*MempoolRequest) ProtoMessage()    {}
func (*MempoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{0}
}
func (m *MempoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MempoolRequest.Unmarshal(m, b)
}
func (m *MempoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MempoolRequest.Marshal(b, m, deterministic)
}
func (dst *MempoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MempoolRequest.Merge(dst, src)
}
func (m *MempoolRequest) XXX_Size() int {
	return xxx_messageInfo_MempoolRequest.Size(m)
}
func (m *MempoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MempoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MempoolRequest proto.InternalMessageInfo

func (m *MempoolRequest) GetLastBlockHash() []byte {
	if m != nil {
		return m.LastBlockHash
	}
	return nil
}

type GetValidatorRequest struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorRequest) Reset()         { *m = GetValidatorRequest{} }
func (m *GetValidatorRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorRequest) ProtoMessage()    {}
func (*GetValidatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{1}
}
func (m *GetValidatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorRequest.Unmarshal(m, b)
}
func (m *GetValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorRequest.Marshal(b, m, deterministic)
}
func (dst *GetValidatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorRequest.Merge(dst, src)
}
func (m *GetValidatorRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorRequest.Size(m)
}
func (m *GetValidatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorRequest proto.InternalMessageInfo

func (m *GetValidatorRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetBlockRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{2}
}
func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(dst, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GetBlockResponse struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockResponse) Reset()         { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()    {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{3}
}
func (m *GetBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponse.Unmarshal(m, b)
}
func (m *GetBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponse.Merge(dst, src)
}
func (m *GetBlockResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponse.Size(m)
}
func (m *GetBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponse proto.InternalMessageInfo

func (m *GetBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetProposerForSlotRequest struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProposerForSlotRequest) Reset()         { *m = GetProposerForSlotRequest{} }
func (m *GetProposerForSlotRequest) String() string { return proto.CompactTextString(m) }
func (*GetProposerForSlotRequest) ProtoMessage()    {}
func (*GetProposerForSlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{4}
}
func (m *GetProposerForSlotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProposerForSlotRequest.Unmarshal(m, b)
}
func (m *GetProposerForSlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProposerForSlotRequest.Marshal(b, m, deterministic)
}
func (dst *GetProposerForSlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProposerForSlotRequest.Merge(dst, src)
}
func (m *GetProposerForSlotRequest) XXX_Size() int {
	return xxx_messageInfo_GetProposerForSlotRequest.Size(m)
}
func (m *GetProposerForSlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProposerForSlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProposerForSlotRequest proto.InternalMessageInfo

func (m *GetProposerForSlotRequest) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type GetProposerForSlotResponse struct {
	Proposer             uint32   `protobuf:"varint,1,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProposerForSlotResponse) Reset()         { *m = GetProposerForSlotResponse{} }
func (m *GetProposerForSlotResponse) String() string { return proto.CompactTextString(m) }
func (*GetProposerForSlotResponse) ProtoMessage()    {}
func (*GetProposerForSlotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{5}
}
func (m *GetProposerForSlotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProposerForSlotResponse.Unmarshal(m, b)
}
func (m *GetProposerForSlotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProposerForSlotResponse.Marshal(b, m, deterministic)
}
func (dst *GetProposerForSlotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProposerForSlotResponse.Merge(dst, src)
}
func (m *GetProposerForSlotResponse) XXX_Size() int {
	return xxx_messageInfo_GetProposerForSlotResponse.Size(m)
}
func (m *GetProposerForSlotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProposerForSlotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProposerForSlotResponse proto.InternalMessageInfo

func (m *GetProposerForSlotResponse) GetProposer() uint32 {
	if m != nil {
		return m.Proposer
	}
	return 0
}

type EpochInformationRequest struct {
	EpochIndex           uint64   `protobuf:"varint,1,opt,name=EpochIndex,proto3" json:"EpochIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochInformationRequest) Reset()         { *m = EpochInformationRequest{} }
func (m *EpochInformationRequest) String() string { return proto.CompactTextString(m) }
func (*EpochInformationRequest) ProtoMessage()    {}
func (*EpochInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{6}
}
func (m *EpochInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochInformationRequest.Unmarshal(m, b)
}
func (m *EpochInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochInformationRequest.Marshal(b, m, deterministic)
}
func (dst *EpochInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochInformationRequest.Merge(dst, src)
}
func (m *EpochInformationRequest) XXX_Size() int {
	return xxx_messageInfo_EpochInformationRequest.Size(m)
}
func (m *EpochInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EpochInformationRequest proto.InternalMessageInfo

func (m *EpochInformationRequest) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

type EpochInformationResponse struct {
	HasEpochInformation  bool              `protobuf:"varint,1,opt,name=HasEpochInformation,proto3" json:"HasEpochInformation,omitempty"`
	Information          *EpochInformation `protobuf:"bytes,2,opt,name=Information,proto3" json:"Information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EpochInformationResponse) Reset()         { *m = EpochInformationResponse{} }
func (m *EpochInformationResponse) String() string { return proto.CompactTextString(m) }
func (*EpochInformationResponse) ProtoMessage()    {}
func (*EpochInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{7}
}
func (m *EpochInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochInformationResponse.Unmarshal(m, b)
}
func (m *EpochInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochInformationResponse.Marshal(b, m, deterministic)
}
func (dst *EpochInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochInformationResponse.Merge(dst, src)
}
func (m *EpochInformationResponse) XXX_Size() int {
	return xxx_messageInfo_EpochInformationResponse.Size(m)
}
func (m *EpochInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpochInformationResponse proto.InternalMessageInfo

func (m *EpochInformationResponse) GetHasEpochInformation() bool {
	if m != nil {
		return m.HasEpochInformation
	}
	return false
}

func (m *EpochInformationResponse) GetInformation() *EpochInformation {
	if m != nil {
		return m.Information
	}
	return nil
}

type EpochInformation struct {
	ShardCommitteesForSlots []*ShardCommitteesForSlot `protobuf:"bytes,1,rep,name=ShardCommitteesForSlots,proto3" json:"ShardCommitteesForSlots,omitempty"`
	Slot                    int64                     `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	LatestCrosslinks        []*Crosslink              `protobuf:"bytes,3,rep,name=LatestCrosslinks,proto3" json:"LatestCrosslinks,omitempty"`
	JustifiedEpoch          uint64                    `protobuf:"varint,4,opt,name=JustifiedEpoch,proto3" json:"JustifiedEpoch,omitempty"`
	JustifiedHash           []byte                    `protobuf:"bytes,5,opt,name=JustifiedHash,proto3" json:"JustifiedHash,omitempty"`
	TargetHash              []byte                    `protobuf:"bytes,6,opt,name=TargetHash,proto3" json:"TargetHash,omitempty"`
	PreviousTargetHash      []byte                    `protobuf:"bytes,7,opt,name=PreviousTargetHash,proto3" json:"PreviousTargetHash,omitempty"`
	PreviousJustifiedEpoch  uint64                    `protobuf:"varint,8,opt,name=PreviousJustifiedEpoch,proto3" json:"PreviousJustifiedEpoch,omitempty"`
	PreviousJustifiedHash   []byte                    `protobuf:"bytes,9,opt,name=PreviousJustifiedHash,proto3" json:"PreviousJustifiedHash,omitempty"`
	PreviousCrosslinks      []*Crosslink              `protobuf:"bytes,10,rep,name=PreviousCrosslinks,proto3" json:"PreviousCrosslinks,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                  `json:"-"`
	XXX_unrecognized        []byte                    `json:"-"`
	XXX_sizecache           int32                     `json:"-"`
}

func (m *EpochInformation) Reset()         { *m = EpochInformation{} }
func (m *EpochInformation) String() string { return proto.CompactTextString(m) }
func (*EpochInformation) ProtoMessage()    {}
func (*EpochInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{8}
}
func (m *EpochInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochInformation.Unmarshal(m, b)
}
func (m *EpochInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochInformation.Marshal(b, m, deterministic)
}
func (dst *EpochInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochInformation.Merge(dst, src)
}
func (m *EpochInformation) XXX_Size() int {
	return xxx_messageInfo_EpochInformation.Size(m)
}
func (m *EpochInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochInformation.DiscardUnknown(m)
}

var xxx_messageInfo_EpochInformation proto.InternalMessageInfo

func (m *EpochInformation) GetShardCommitteesForSlots() []*ShardCommitteesForSlot {
	if m != nil {
		return m.ShardCommitteesForSlots
	}
	return nil
}

func (m *EpochInformation) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *EpochInformation) GetLatestCrosslinks() []*Crosslink {
	if m != nil {
		return m.LatestCrosslinks
	}
	return nil
}

func (m *EpochInformation) GetJustifiedEpoch() uint64 {
	if m != nil {
		return m.JustifiedEpoch
	}
	return 0
}

func (m *EpochInformation) GetJustifiedHash() []byte {
	if m != nil {
		return m.JustifiedHash
	}
	return nil
}

func (m *EpochInformation) GetTargetHash() []byte {
	if m != nil {
		return m.TargetHash
	}
	return nil
}

func (m *EpochInformation) GetPreviousTargetHash() []byte {
	if m != nil {
		return m.PreviousTargetHash
	}
	return nil
}

func (m *EpochInformation) GetPreviousJustifiedEpoch() uint64 {
	if m != nil {
		return m.PreviousJustifiedEpoch
	}
	return 0
}

func (m *EpochInformation) GetPreviousJustifiedHash() []byte {
	if m != nil {
		return m.PreviousJustifiedHash
	}
	return nil
}

func (m *EpochInformation) GetPreviousCrosslinks() []*Crosslink {
	if m != nil {
		return m.PreviousCrosslinks
	}
	return nil
}

type DisconnectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{9}
}
func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (dst *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(dst, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetCommitteesForSlotRequest struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommitteesForSlotRequest) Reset()         { *m = GetCommitteesForSlotRequest{} }
func (m *GetCommitteesForSlotRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommitteesForSlotRequest) ProtoMessage()    {}
func (*GetCommitteesForSlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{10}
}
func (m *GetCommitteesForSlotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteesForSlotRequest.Unmarshal(m, b)
}
func (m *GetCommitteesForSlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteesForSlotRequest.Marshal(b, m, deterministic)
}
func (dst *GetCommitteesForSlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteesForSlotRequest.Merge(dst, src)
}
func (m *GetCommitteesForSlotRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommitteesForSlotRequest.Size(m)
}
func (m *GetCommitteesForSlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteesForSlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteesForSlotRequest proto.InternalMessageInfo

func (m *GetCommitteesForSlotRequest) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type GetSlotAndShardAssignmentRequest struct {
	ValidatorID          uint32   `protobuf:"varint,1,opt,name=ValidatorID,proto3" json:"ValidatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotAndShardAssignmentRequest) Reset()         { *m = GetSlotAndShardAssignmentRequest{} }
func (m *GetSlotAndShardAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetSlotAndShardAssignmentRequest) ProtoMessage()    {}
func (*GetSlotAndShardAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{11}
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Unmarshal(m, b)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Marshal(b, m, deterministic)
}
func (dst *GetSlotAndShardAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotAndShardAssignmentRequest.Merge(dst, src)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Size(m)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotAndShardAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotAndShardAssignmentRequest proto.InternalMessageInfo

func (m *GetSlotAndShardAssignmentRequest) GetValidatorID() uint32 {
	if m != nil {
		return m.ValidatorID
	}
	return 0
}

type SubmitBlockRequest struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitBlockRequest) Reset()         { *m = SubmitBlockRequest{} }
func (m *SubmitBlockRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockRequest) ProtoMessage()    {}
func (*SubmitBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{12}
}
func (m *SubmitBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitBlockRequest.Unmarshal(m, b)
}
func (m *SubmitBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitBlockRequest.Marshal(b, m, deterministic)
}
func (dst *SubmitBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockRequest.Merge(dst, src)
}
func (m *SubmitBlockRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitBlockRequest.Size(m)
}
func (m *SubmitBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockRequest proto.InternalMessageInfo

func (m *SubmitBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubmitBlockResponse struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitBlockResponse) Reset()         { *m = SubmitBlockResponse{} }
func (m *SubmitBlockResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockResponse) ProtoMessage()    {}
func (*SubmitBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{13}
}
func (m *SubmitBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitBlockResponse.Unmarshal(m, b)
}
func (m *SubmitBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitBlockResponse.Marshal(b, m, deterministic)
}
func (dst *SubmitBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockResponse.Merge(dst, src)
}
func (m *SubmitBlockResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitBlockResponse.Size(m)
}
func (m *SubmitBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockResponse proto.InternalMessageInfo

func (m *SubmitBlockResponse) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type SlotNumberResponse struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotNumberResponse) Reset()         { *m = SlotNumberResponse{} }
func (m *SlotNumberResponse) String() string { return proto.CompactTextString(m) }
func (*SlotNumberResponse) ProtoMessage()    {}
func (*SlotNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{14}
}
func (m *SlotNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotNumberResponse.Unmarshal(m, b)
}
func (m *SlotNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotNumberResponse.Marshal(b, m, deterministic)
}
func (dst *SlotNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotNumberResponse.Merge(dst, src)
}
func (m *SlotNumberResponse) XXX_Size() int {
	return xxx_messageInfo_SlotNumberResponse.Size(m)
}
func (m *SlotNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlotNumberResponse proto.InternalMessageInfo

func (m *SlotNumberResponse) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *SlotNumberResponse) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type GetBlockHashRequest struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashRequest) Reset()         { *m = GetBlockHashRequest{} }
func (m *GetBlockHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashRequest) ProtoMessage()    {}
func (*GetBlockHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{15}
}
func (m *GetBlockHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashRequest.Unmarshal(m, b)
}
func (m *GetBlockHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashRequest.Merge(dst, src)
}
func (m *GetBlockHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashRequest.Size(m)
}
func (m *GetBlockHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashRequest proto.InternalMessageInfo

func (m *GetBlockHashRequest) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type GetBlockHashResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashResponse) Reset()         { *m = GetBlockHashResponse{} }
func (m *GetBlockHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashResponse) ProtoMessage()    {}
func (*GetBlockHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{16}
}
func (m *GetBlockHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashResponse.Unmarshal(m, b)
}
func (m *GetBlockHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlockHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashResponse.Merge(dst, src)
}
func (m *GetBlockHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashResponse.Size(m)
}
func (m *GetBlockHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashResponse proto.InternalMessageInfo

func (m *GetBlockHashResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GetValidatorAtIndexRequest struct {
	Index                uint32   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorAtIndexRequest) Reset()         { *m = GetValidatorAtIndexRequest{} }
func (m *GetValidatorAtIndexRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorAtIndexRequest) ProtoMessage()    {}
func (*GetValidatorAtIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{17}
}
func (m *GetValidatorAtIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Unmarshal(m, b)
}
func (m *GetValidatorAtIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Marshal(b, m, deterministic)
}
func (dst *GetValidatorAtIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorAtIndexRequest.Merge(dst, src)
}
func (m *GetValidatorAtIndexRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Size(m)
}
func (m *GetValidatorAtIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorAtIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorAtIndexRequest proto.InternalMessageInfo

func (m *GetValidatorAtIndexRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type GetValidatorAtIndexResponse struct {
	Validator            *Validator `protobuf:"bytes,1,opt,name=Validator,proto3" json:"Validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetValidatorAtIndexResponse) Reset()         { *m = GetValidatorAtIndexResponse{} }
func (m *GetValidatorAtIndexResponse) String() string { return proto.CompactTextString(m) }
func (*GetValidatorAtIndexResponse) ProtoMessage()    {}
func (*GetValidatorAtIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{18}
}
func (m *GetValidatorAtIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Unmarshal(m, b)
}
func (m *GetValidatorAtIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Marshal(b, m, deterministic)
}
func (dst *GetValidatorAtIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorAtIndexResponse.Merge(dst, src)
}
func (m *GetValidatorAtIndexResponse) XXX_Size() int {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Size(m)
}
func (m *GetValidatorAtIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorAtIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorAtIndexResponse proto.InternalMessageInfo

func (m *GetValidatorAtIndexResponse) GetValidator() *Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

type GetCommitteeValidatorsRequest struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	Shard                uint32   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommitteeValidatorsRequest) Reset()         { *m = GetCommitteeValidatorsRequest{} }
func (m *GetCommitteeValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorsRequest) ProtoMessage()    {}
func (*GetCommitteeValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{19}
}
func (m *GetCommitteeValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Marshal(b, m, deterministic)
}
func (dst *GetCommitteeValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorsRequest.Merge(dst, src)
}
func (m *GetCommitteeValidatorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Size(m)
}
func (m *GetCommitteeValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorsRequest proto.InternalMessageInfo

func (m *GetCommitteeValidatorsRequest) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *GetCommitteeValidatorsRequest) GetShard() uint32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

type GetStateResponse struct {
	State                *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateResponse) Reset()         { *m = GetStateResponse{} }
func (m *GetStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateResponse) ProtoMessage()    {}
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{20}
}
func (m *GetStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateResponse.Unmarshal(m, b)
}
func (m *GetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateResponse.Marshal(b, m, deterministic)
}
func (dst *GetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateResponse.Merge(dst, src)
}
func (m *GetStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateResponse.Size(m)
}
func (m *GetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateResponse proto.InternalMessageInfo

func (m *GetStateResponse) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

type GetStateRootResponse struct {
	StateRoot            []byte   `protobuf:"bytes,1,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateRootResponse) Reset()         { *m = GetStateRootResponse{} }
func (m *GetStateRootResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateRootResponse) ProtoMessage()    {}
func (*GetStateRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{21}
}
func (m *GetStateRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateRootResponse.Unmarshal(m, b)
}
func (m *GetStateRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateRootResponse.Marshal(b, m, deterministic)
}
func (dst *GetStateRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateRootResponse.Merge(dst, src)
}
func (m *GetStateRootResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateRootResponse.Size(m)
}
func (m *GetStateRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateRootResponse proto.InternalMessageInfo

func (m *GetStateRootResponse) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

type GetCommitteeValidatorsResponse struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=Validators,proto3" json:"Validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCommitteeValidatorsResponse) Reset()         { *m = GetCommitteeValidatorsResponse{} }
func (m *GetCommitteeValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorsResponse) ProtoMessage()    {}
func (*GetCommitteeValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{22}
}
func (m *GetCommitteeValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Marshal(b, m, deterministic)
}
func (dst *GetCommitteeValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorsResponse.Merge(dst, src)
}
func (m *GetCommitteeValidatorsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Size(m)
}
func (m *GetCommitteeValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorsResponse proto.InternalMessageInfo

func (m *GetCommitteeValidatorsResponse) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type GetCommitteeValidatorIndicesResponse struct {
	Validators           []uint32 `protobuf:"varint,1,rep,packed,name=Validators,proto3" json:"Validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommitteeValidatorIndicesResponse) Reset()         { *m = GetCommitteeValidatorIndicesResponse{} }
func (m *GetCommitteeValidatorIndicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorIndicesResponse) ProtoMessage()    {}
func (*GetCommitteeValidatorIndicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_beaconrpc_75749bc53875efeb, []int{23}
}
func (m *GetCommitteeValidatorIndicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorIndicesResponse.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorIndicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorIndicesResponse.Marshal(b, m, deterministic)
}
func (dst *GetCommitteeValidatorIndicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorIndicesResponse.Merge(dst, src)
}
func (m *GetCommitteeValidatorIndicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorIndicesResponse.Size(m)
}
func (m *GetCommitteeValidatorIndicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorIndicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorIndicesResponse proto.InternalMessageInfo

func (m *GetCommitteeValidatorIndicesResponse) GetValidators() []uint32 {
	if m != nil {
		return m.Validators
	}
	return nil
}

func init() {
	proto.RegisterType((*MempoolRequest)(nil), "pb.MempoolRequest")
	proto.RegisterType((*GetValidatorRequest)(nil), "pb.GetValidatorRequest")
	proto.RegisterType((*GetBlockRequest)(nil), "pb.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "pb.GetBlockResponse")
	proto.RegisterType((*GetProposerForSlotRequest)(nil), "pb.GetProposerForSlotRequest")
	proto.RegisterType((*GetProposerForSlotResponse)(nil), "pb.GetProposerForSlotResponse")
	proto.RegisterType((*EpochInformationRequest)(nil), "pb.EpochInformationRequest")
	proto.RegisterType((*EpochInformationResponse)(nil), "pb.EpochInformationResponse")
	proto.RegisterType((*EpochInformation)(nil), "pb.EpochInformation")
	proto.RegisterType((*DisconnectResponse)(nil), "pb.DisconnectResponse")
	proto.RegisterType((*GetCommitteesForSlotRequest)(nil), "pb.GetCommitteesForSlotRequest")
	proto.RegisterType((*GetSlotAndShardAssignmentRequest)(nil), "pb.GetSlotAndShardAssignmentRequest")
	proto.RegisterType((*SubmitBlockRequest)(nil), "pb.SubmitBlockRequest")
	proto.RegisterType((*SubmitBlockResponse)(nil), "pb.SubmitBlockResponse")
	proto.RegisterType((*SlotNumberResponse)(nil), "pb.SlotNumberResponse")
	proto.RegisterType((*GetBlockHashRequest)(nil), "pb.GetBlockHashRequest")
	proto.RegisterType((*GetBlockHashResponse)(nil), "pb.GetBlockHashResponse")
	proto.RegisterType((*GetValidatorAtIndexRequest)(nil), "pb.GetValidatorAtIndexRequest")
	proto.RegisterType((*GetValidatorAtIndexResponse)(nil), "pb.GetValidatorAtIndexResponse")
	proto.RegisterType((*GetCommitteeValidatorsRequest)(nil), "pb.GetCommitteeValidatorsRequest")
	proto.RegisterType((*GetStateResponse)(nil), "pb.GetStateResponse")
	proto.RegisterType((*GetStateRootResponse)(nil), "pb.GetStateRootResponse")
	proto.RegisterType((*GetCommitteeValidatorsResponse)(nil), "pb.GetCommitteeValidatorsResponse")
	proto.RegisterType((*GetCommitteeValidatorIndicesResponse)(nil), "pb.GetCommitteeValidatorIndicesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainRPCClient is the client API for BlockchainRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainRPCClient interface {
	SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
	GetSlotNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SlotNumberResponse, error)
	GetBlockHash(ctx context.Context, in *GetBlockHashRequest, opts ...grpc.CallOption) (*GetBlockHashResponse, error)
	GetLastBlockHash(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBlockHashResponse, error)
	GetState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetStateResponse, error)
	GetStateRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetStateRootResponse, error)
	GetEpochInformation(ctx context.Context, in *EpochInformationRequest, opts ...grpc.CallOption) (*EpochInformationResponse, error)
	GetForkData(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ForkData, error)
	GetProposerForSlot(ctx context.Context, in *GetProposerForSlotRequest, opts ...grpc.CallOption) (*GetProposerForSlotResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	SubmitAttestation(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMempool(ctx context.Context, in *MempoolRequest, opts ...grpc.CallOption) (*BlockBody, error)
	GetValidatorInformation(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*Validator, error)
}

type blockchainRPCClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainRPCClient(cc *grpc.ClientConn) BlockchainRPCClient {
	return &blockchainRPCClient{cc}
}

func (c *blockchainRPCClient) SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/SubmitBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetSlotNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SlotNumberResponse, error) {
	out := new(SlotNumberResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetSlotNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetBlockHash(ctx context.Context, in *GetBlockHashRequest, opts ...grpc.CallOption) (*GetBlockHashResponse, error) {
	out := new(GetBlockHashResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetLastBlockHash(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetBlockHashResponse, error) {
	out := new(GetBlockHashResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetLastBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetStateRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetStateRootResponse, error) {
	out := new(GetStateRootResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetStateRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetEpochInformation(ctx context.Context, in *EpochInformationRequest, opts ...grpc.CallOption) (*EpochInformationResponse, error) {
	out := new(EpochInformationResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetEpochInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetForkData(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ForkData, error) {
	out := new(ForkData)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetForkData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetProposerForSlot(ctx context.Context, in *GetProposerForSlotRequest, opts ...grpc.CallOption) (*GetProposerForSlotResponse, error) {
	out := new(GetProposerForSlotResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetProposerForSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) SubmitAttestation(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/SubmitAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetMempool(ctx context.Context, in *MempoolRequest, opts ...grpc.CallOption) (*BlockBody, error) {
	out := new(BlockBody)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetMempool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetValidatorInformation(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*Validator, error) {
	out := new(Validator)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetValidatorInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainRPCServer is the server API for BlockchainRPC service.
type BlockchainRPCServer interface {
	SubmitBlock(context.Context, *SubmitBlockRequest) (*SubmitBlockResponse, error)
	GetSlotNumber(context.Context, *empty.Empty) (*SlotNumberResponse, error)
	GetBlockHash(context.Context, *GetBlockHashRequest) (*GetBlockHashResponse, error)
	GetLastBlockHash(context.Context, *empty.Empty) (*GetBlockHashResponse, error)
	GetState(context.Context, *empty.Empty) (*GetStateResponse, error)
	GetStateRoot(context.Context, *empty.Empty) (*GetStateRootResponse, error)
	GetEpochInformation(context.Context, *EpochInformationRequest) (*EpochInformationResponse, error)
	GetForkData(context.Context, *empty.Empty) (*ForkData, error)
	GetProposerForSlot(context.Context, *GetProposerForSlotRequest) (*GetProposerForSlotResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	SubmitAttestation(context.Context, *Attestation) (*empty.Empty, error)
	GetMempool(context.Context, *MempoolRequest) (*BlockBody, error)
	GetValidatorInformation(context.Context, *GetValidatorRequest) (*Validator, error)
}

func RegisterBlockchainRPCServer(s *grpc.Server, srv BlockchainRPCServer) {
	s.RegisterService(&_BlockchainRPC_serviceDesc, srv)
}

func _BlockchainRPC_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/SubmitBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).SubmitBlock(ctx, req.(*SubmitBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetSlotNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetSlotNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetSlotNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetSlotNumber(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetBlockHash(ctx, req.(*GetBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetLastBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetLastBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetLastBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetLastBlockHash(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetState(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetStateRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetStateRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetStateRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetStateRoot(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetEpochInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpochInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetEpochInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetEpochInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetEpochInformation(ctx, req.(*EpochInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetForkData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetForkData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetForkData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetForkData(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetProposerForSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProposerForSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetProposerForSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetProposerForSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetProposerForSlot(ctx, req.(*GetProposerForSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_SubmitAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).SubmitAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/SubmitAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).SubmitAttestation(ctx, req.(*Attestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetMempool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MempoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetMempool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetMempool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetMempool(ctx, req.(*MempoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetValidatorInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetValidatorInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetValidatorInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetValidatorInformation(ctx, req.(*GetValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockchainRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlockchainRPC",
	HandlerType: (*BlockchainRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBlock",
			Handler:    _BlockchainRPC_SubmitBlock_Handler,
		},
		{
			MethodName: "GetSlotNumber",
			Handler:    _BlockchainRPC_GetSlotNumber_Handler,
		},
		{
			MethodName: "GetBlockHash",
			Handler:    _BlockchainRPC_GetBlockHash_Handler,
		},
		{
			MethodName: "GetLastBlockHash",
			Handler:    _BlockchainRPC_GetLastBlockHash_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _BlockchainRPC_GetState_Handler,
		},
		{
			MethodName: "GetStateRoot",
			Handler:    _BlockchainRPC_GetStateRoot_Handler,
		},
		{
			MethodName: "GetEpochInformation",
			Handler:    _BlockchainRPC_GetEpochInformation_Handler,
		},
		{
			MethodName: "GetForkData",
			Handler:    _BlockchainRPC_GetForkData_Handler,
		},
		{
			MethodName: "GetProposerForSlot",
			Handler:    _BlockchainRPC_GetProposerForSlot_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _BlockchainRPC_GetBlock_Handler,
		},
		{
			MethodName: "SubmitAttestation",
			Handler:    _BlockchainRPC_SubmitAttestation_Handler,
		},
		{
			MethodName: "GetMempool",
			Handler:    _BlockchainRPC_GetMempool_Handler,
		},
		{
			MethodName: "GetValidatorInformation",
			Handler:    _BlockchainRPC_GetValidatorInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beaconrpc.proto",
}

func init() { proto.RegisterFile("beaconrpc.proto", fileDescriptor_beaconrpc_75749bc53875efeb) }

var fileDescriptor_beaconrpc_75749bc53875efeb = []byte{
	// 968 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x5b, 0x6f, 0xdb, 0x36,
	0x14, 0x46, 0x9c, 0x4b, 0xe3, 0xe3, 0x28, 0xc9, 0x18, 0x2f, 0xf1, 0x94, 0x34, 0x0b, 0x88, 0x76,
	0x28, 0x36, 0xcc, 0xd9, 0x92, 0x26, 0x68, 0x81, 0xdd, 0xdc, 0xb8, 0x71, 0x53, 0x74, 0x5b, 0x20,
	0x77, 0x7b, 0x97, 0x65, 0x26, 0x11, 0x62, 0x89, 0x9a, 0x48, 0x0f, 0xeb, 0xeb, 0xb0, 0x5f, 0xb9,
	0x5f, 0x33, 0xe8, 0x90, 0xa2, 0x28, 0x4b, 0x6a, 0xf6, 0x26, 0x7e, 0xe7, 0xca, 0x8f, 0x1f, 0x8f,
	0x08, 0x5b, 0x13, 0xe6, 0x07, 0x3c, 0x4e, 0x93, 0xa0, 0x9f, 0xa4, 0x5c, 0x72, 0xd2, 0x4a, 0x26,
	0xee, 0xfe, 0x2d, 0xe7, 0xb7, 0x33, 0x76, 0x8c, 0xc8, 0x64, 0x7e, 0x73, 0xcc, 0xa2, 0x44, 0x7e,
	0x50, 0x0e, 0xee, 0x46, 0xc0, 0xa3, 0x88, 0xc7, 0x6a, 0x45, 0xcf, 0x61, 0xf3, 0x67, 0x16, 0x25,
	0x9c, 0xcf, 0x3c, 0xf6, 0xc7, 0x9c, 0x09, 0x49, 0x9e, 0x80, 0xf3, 0xce, 0x17, 0xf2, 0xd5, 0x8c,
	0x07, 0xf7, 0x6f, 0x7c, 0x71, 0xd7, 0x5b, 0x3a, 0x5a, 0x7a, 0xb6, 0xe1, 0x95, 0x41, 0xfa, 0x14,
	0x76, 0x46, 0x4c, 0xfe, 0xee, 0xcf, 0xc2, 0xa9, 0x2f, 0x79, 0x9a, 0x07, 0x6f, 0x42, 0xeb, 0x6a,
	0x88, 0x11, 0x8e, 0xd7, 0xba, 0x1a, 0xd2, 0xa7, 0xb0, 0x35, 0x62, 0x2a, 0x2c, 0x77, 0x21, 0xb0,
	0x62, 0xa5, 0xc5, 0x6f, 0x7a, 0x0a, 0xdb, 0x85, 0x9b, 0x48, 0x78, 0x2c, 0x18, 0xf9, 0x1c, 0x56,
	0x11, 0x40, 0xc7, 0xce, 0x49, 0xbb, 0x9f, 0x4c, 0xfa, 0xca, 0x43, 0xe1, 0xf4, 0x18, 0x3e, 0x1b,
	0x31, 0x79, 0x9d, 0xf2, 0x84, 0x0b, 0x96, 0x5e, 0xf2, 0x74, 0x3c, 0xe3, 0xd2, 0xaa, 0x92, 0x2d,
	0x31, 0x78, 0xc5, 0xc3, 0x6f, 0xfa, 0x02, 0xdc, 0xba, 0x00, 0x5d, 0xcf, 0x85, 0xf5, 0xdc, 0xa4,
	0x37, 0x60, 0xd6, 0xf4, 0x25, 0xec, 0xbd, 0x4e, 0x78, 0x70, 0x77, 0x15, 0xdf, 0xf0, 0x34, 0xf2,
	0x65, 0xc8, 0xe3, 0xbc, 0xd0, 0x21, 0x80, 0x36, 0x4d, 0xd9, 0x5f, 0xba, 0x9c, 0x85, 0xd0, 0x7f,
	0x96, 0xa0, 0x57, 0x8d, 0xd5, 0x35, 0xbf, 0x81, 0x9d, 0x37, 0xbe, 0x58, 0x34, 0x63, 0x96, 0x75,
	0xaf, 0xce, 0x44, 0xce, 0xa1, 0x63, 0x7b, 0xb6, 0x90, 0x9b, 0x6e, 0xc6, 0x4d, 0xa5, 0x88, 0xed,
	0x48, 0xff, 0x5e, 0x81, 0xed, 0x4a, 0xb2, 0xf7, 0xb0, 0x37, 0xbe, 0xf3, 0xd3, 0xe9, 0x05, 0x8f,
	0xa2, 0x50, 0x4a, 0xc6, 0x84, 0x26, 0x45, 0xf4, 0x96, 0x8e, 0x96, 0x9f, 0x75, 0x4e, 0xdc, 0x2c,
	0x71, 0xbd, 0x8b, 0xd7, 0x14, 0x6a, 0xa8, 0xcf, 0x7a, 0x5b, 0x56, 0xd4, 0x93, 0x97, 0xb0, 0xfd,
	0xce, 0x97, 0x4c, 0xc8, 0x8b, 0x94, 0x0b, 0x31, 0x0b, 0xe3, 0x7b, 0xd1, 0x5b, 0xc6, 0x12, 0x4e,
	0x56, 0xc2, 0xa0, 0x5e, 0xc5, 0x8d, 0x7c, 0x01, 0x9b, 0x6f, 0xe7, 0x42, 0x86, 0x37, 0x21, 0x9b,
	0xe2, 0x0e, 0x7a, 0x2b, 0x48, 0xf2, 0x02, 0x9a, 0xe9, 0xd6, 0x20, 0x28, 0xb0, 0x55, 0xa5, 0xdb,
	0x12, 0x98, 0x1d, 0xd7, 0x7b, 0x3f, 0xbd, 0x65, 0x12, 0x5d, 0xd6, 0xd0, 0xc5, 0x42, 0x48, 0x1f,
	0xc8, 0x75, 0xca, 0xfe, 0x0c, 0xf9, 0x5c, 0x58, 0x7e, 0x8f, 0xd0, 0xaf, 0xc6, 0x42, 0xce, 0x61,
	0x37, 0x47, 0x17, 0xba, 0x5c, 0xc7, 0x2e, 0x1b, 0xac, 0xe4, 0x39, 0x7c, 0x5a, 0xb1, 0x60, 0xa9,
	0x36, 0x96, 0xaa, 0x37, 0x92, 0xef, 0x8b, 0xee, 0x2c, 0x22, 0xa1, 0x8e, 0xc8, 0x1a, 0x47, 0xda,
	0x07, 0x32, 0x0c, 0x45, 0xc0, 0xe3, 0x98, 0x05, 0x85, 0xf0, 0x7b, 0xf0, 0x68, 0x3c, 0x0f, 0x02,
	0x26, 0x84, 0x16, 0x5e, 0xbe, 0xa4, 0xdf, 0xc2, 0xfe, 0x88, 0xc9, 0xea, 0xd1, 0x7f, 0xe4, 0x8e,
	0x0d, 0xe1, 0x68, 0xc4, 0x64, 0xf6, 0x39, 0x88, 0xa7, 0xa8, 0x90, 0x81, 0x10, 0xe1, 0x6d, 0x1c,
	0xb1, 0xd8, 0xc4, 0x1d, 0x41, 0xc7, 0x0c, 0x0e, 0x33, 0x2d, 0x6c, 0x88, 0x9e, 0x01, 0x19, 0xcf,
	0x27, 0x51, 0x58, 0x9e, 0x1c, 0x0f, 0x4e, 0x84, 0x53, 0xd8, 0x29, 0x85, 0xe9, 0x0d, 0x1e, 0x40,
	0x7b, 0x71, 0x9a, 0x15, 0x00, 0xf5, 0x80, 0x64, 0xed, 0xfe, 0x32, 0x8f, 0x26, 0x2c, 0x35, 0x31,
	0x87, 0x00, 0x05, 0x9a, 0x5f, 0xeb, 0x02, 0x29, 0xe7, 0x6c, 0x2d, 0xe6, 0x3c, 0xc3, 0xe9, 0x68,
	0xd6, 0xd6, 0xac, 0xf8, 0x58, 0x52, 0xfa, 0x25, 0x74, 0xcb, 0x61, 0xba, 0x99, 0xba, 0x91, 0x79,
	0x82, 0xc3, 0xcc, 0x90, 0x36, 0x90, 0x38, 0x6e, 0xf2, 0x4a, 0x5d, 0x58, 0x2d, 0x06, 0x92, 0xe3,
	0xa9, 0x05, 0x7d, 0x8b, 0xe7, 0x59, 0x8d, 0xd1, 0x65, 0xbe, 0x82, 0xb6, 0xb1, 0x69, 0x8e, 0x51,
	0x54, 0xc5, 0x94, 0x2f, 0xec, 0xf4, 0x37, 0x78, 0x6c, 0x6b, 0xc3, 0x18, 0xc4, 0xff, 0xdc, 0x6c,
	0xd6, 0x22, 0xea, 0x03, 0xd9, 0x73, 0x3c, 0xb5, 0xd0, 0x7f, 0x82, 0xb1, 0xf4, 0x25, 0xb3, 0xff,
	0x04, 0x22, 0x03, 0xec, 0x73, 0x57, 0x1e, 0x0a, 0xa7, 0xcf, 0x91, 0x37, 0x05, 0x71, 0x6b, 0xa4,
	0x1f, 0x40, 0xdb, 0x80, 0xf9, 0xc1, 0x1b, 0x80, 0xfe, 0x0a, 0x87, 0x4d, 0x3b, 0xd0, 0xf1, 0x5f,
	0x03, 0x14, 0xa8, 0x1e, 0x89, 0x0b, 0x8c, 0x58, 0x0e, 0xf4, 0x12, 0x9e, 0xd4, 0x26, 0xbc, 0x8a,
	0xa7, 0x61, 0xc0, 0x84, 0xad, 0xad, 0x85, 0xb4, 0x8e, 0x9d, 0xe7, 0xe4, 0xdf, 0x35, 0x70, 0x50,
	0x04, 0xc1, 0x9d, 0x1f, 0xc6, 0xde, 0xf5, 0x05, 0xf9, 0x01, 0x3a, 0x96, 0xb0, 0xc9, 0x2e, 0x32,
	0x50, 0xb9, 0x20, 0xee, 0x5e, 0x05, 0xd7, 0x15, 0x7f, 0x04, 0x47, 0xdf, 0x4a, 0x4d, 0xfe, 0x6e,
	0x5f, 0x3d, 0x11, 0xfa, 0xf9, 0x13, 0xa1, 0xff, 0x3a, 0x7b, 0x22, 0xb8, 0x2a, 0x73, 0xf5, 0x3a,
	0x0c, 0x60, 0xc3, 0x56, 0x26, 0xc1, 0x4a, 0x35, 0x12, 0x77, 0x7b, 0x55, 0x83, 0x4e, 0x31, 0xc4,
	0x93, 0x2d, 0xbd, 0x22, 0x1a, 0xdb, 0x68, 0xce, 0xf2, 0x02, 0xd6, 0xf3, 0xa3, 0x6e, 0x8c, 0xee,
	0xea, 0xe8, 0xb2, 0x8a, 0x7e, 0xc2, 0x2d, 0x98, 0xe3, 0x7f, 0xb0, 0x76, 0x55, 0x4e, 0xd7, 0x78,
	0xab, 0x2b, 0x7f, 0xd1, 0xfd, 0xda, 0xbf, 0xaf, 0xe6, 0xe3, 0xa0, 0xde, 0xa8, 0x33, 0x9e, 0x42,
	0x67, 0xc4, 0xe4, 0x25, 0x4f, 0xef, 0x87, 0xbe, 0xf4, 0x1b, 0x5b, 0xda, 0xc8, 0x92, 0x18, 0xaf,
	0x31, 0x90, 0xea, 0x33, 0x86, 0x3c, 0xd6, 0x6d, 0xd7, 0xbf, 0x87, 0xdc, 0xc3, 0x26, 0xb3, 0xee,
	0xe4, 0x0c, 0x79, 0x55, 0xf2, 0xda, 0xb1, 0xd9, 0xcf, 0x13, 0x74, 0xcb, 0xa0, 0x0e, 0xfb, 0x0e,
	0x3e, 0x51, 0x7a, 0x1b, 0xc8, 0xec, 0xb7, 0xad, 0x08, 0xd9, 0xca, 0x5c, 0x2d, 0xc0, 0x6d, 0xd8,
	0x17, 0x39, 0x06, 0x18, 0x31, 0xa9, 0xdf, 0x9f, 0x84, 0x64, 0x61, 0xe5, 0xc7, 0xa8, 0xeb, 0x98,
	0x19, 0xff, 0x8a, 0x4f, 0x3f, 0x90, 0x01, 0xec, 0xd9, 0x03, 0xcc, 0x3e, 0x85, 0x5c, 0x91, 0x8b,
	0x4f, 0x52, 0xb7, 0x7c, 0x61, 0x27, 0x6b, 0xd8, 0xc3, 0xe9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x76, 0xa5, 0x3d, 0xeb, 0x39, 0x0b, 0x00, 0x00,
}
