// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SlotNumberResponse struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	TipSlot              uint64   `protobuf:"varint,3,opt,name=TipSlot,proto3" json:"TipSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotNumberResponse) Reset()         { *m = SlotNumberResponse{} }
func (m *SlotNumberResponse) String() string { return proto.CompactTextString(m) }
func (*SlotNumberResponse) ProtoMessage()    {}
func (*SlotNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{0}
}
func (m *SlotNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotNumberResponse.Unmarshal(m, b)
}
func (m *SlotNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotNumberResponse.Marshal(b, m, deterministic)
}
func (dst *SlotNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotNumberResponse.Merge(dst, src)
}
func (m *SlotNumberResponse) XXX_Size() int {
	return xxx_messageInfo_SlotNumberResponse.Size(m)
}
func (m *SlotNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlotNumberResponse proto.InternalMessageInfo

func (m *SlotNumberResponse) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *SlotNumberResponse) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *SlotNumberResponse) GetTipSlot() uint64 {
	if m != nil {
		return m.TipSlot
	}
	return 0
}

type ConnectMessage struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectMessage) Reset()         { *m = ConnectMessage{} }
func (m *ConnectMessage) String() string { return proto.CompactTextString(m) }
func (*ConnectMessage) ProtoMessage()    {}
func (*ConnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{1}
}
func (m *ConnectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectMessage.Unmarshal(m, b)
}
func (m *ConnectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectMessage.Marshal(b, m, deterministic)
}
func (dst *ConnectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectMessage.Merge(dst, src)
}
func (m *ConnectMessage) XXX_Size() int {
	return xxx_messageInfo_ConnectMessage.Size(m)
}
func (m *ConnectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectMessage proto.InternalMessageInfo

func (m *ConnectMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ListeningAddressesResponse struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListeningAddressesResponse) Reset()         { *m = ListeningAddressesResponse{} }
func (m *ListeningAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*ListeningAddressesResponse) ProtoMessage()    {}
func (*ListeningAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{2}
}
func (m *ListeningAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListeningAddressesResponse.Unmarshal(m, b)
}
func (m *ListeningAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListeningAddressesResponse.Marshal(b, m, deterministic)
}
func (dst *ListeningAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListeningAddressesResponse.Merge(dst, src)
}
func (m *ListeningAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_ListeningAddressesResponse.Size(m)
}
func (m *ListeningAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListeningAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListeningAddressesResponse proto.InternalMessageInfo

func (m *ListeningAddressesResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type ProposalSignedData struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Shard                uint64   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,3,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalSignedData) Reset()         { *m = ProposalSignedData{} }
func (m *ProposalSignedData) String() string { return proto.CompactTextString(m) }
func (*ProposalSignedData) ProtoMessage()    {}
func (*ProposalSignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{3}
}
func (m *ProposalSignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalSignedData.Unmarshal(m, b)
}
func (m *ProposalSignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalSignedData.Marshal(b, m, deterministic)
}
func (dst *ProposalSignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalSignedData.Merge(dst, src)
}
func (m *ProposalSignedData) XXX_Size() int {
	return xxx_messageInfo_ProposalSignedData.Size(m)
}
func (m *ProposalSignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalSignedData.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalSignedData proto.InternalMessageInfo

func (m *ProposalSignedData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ProposalSignedData) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *ProposalSignedData) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type ProposerSlashing struct {
	ProposerIndex        uint32              `protobuf:"varint,1,opt,name=ProposerIndex,proto3" json:"ProposerIndex,omitempty"`
	ProposalData1        *ProposalSignedData `protobuf:"bytes,2,opt,name=ProposalData1,proto3" json:"ProposalData1,omitempty"`
	ProposalSignature1   []byte              `protobuf:"bytes,3,opt,name=ProposalSignature1,proto3" json:"ProposalSignature1,omitempty"`
	ProposalData2        *ProposalSignedData `protobuf:"bytes,4,opt,name=ProposalData2,proto3" json:"ProposalData2,omitempty"`
	ProposalSignature2   []byte              `protobuf:"bytes,5,opt,name=ProposalSignature2,proto3" json:"ProposalSignature2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProposerSlashing) Reset()         { *m = ProposerSlashing{} }
func (m *ProposerSlashing) String() string { return proto.CompactTextString(m) }
func (*ProposerSlashing) ProtoMessage()    {}
func (*ProposerSlashing) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{4}
}
func (m *ProposerSlashing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposerSlashing.Unmarshal(m, b)
}
func (m *ProposerSlashing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposerSlashing.Marshal(b, m, deterministic)
}
func (dst *ProposerSlashing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposerSlashing.Merge(dst, src)
}
func (m *ProposerSlashing) XXX_Size() int {
	return xxx_messageInfo_ProposerSlashing.Size(m)
}
func (m *ProposerSlashing) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposerSlashing.DiscardUnknown(m)
}

var xxx_messageInfo_ProposerSlashing proto.InternalMessageInfo

func (m *ProposerSlashing) GetProposerIndex() uint32 {
	if m != nil {
		return m.ProposerIndex
	}
	return 0
}

func (m *ProposerSlashing) GetProposalData1() *ProposalSignedData {
	if m != nil {
		return m.ProposalData1
	}
	return nil
}

func (m *ProposerSlashing) GetProposalSignature1() []byte {
	if m != nil {
		return m.ProposalSignature1
	}
	return nil
}

func (m *ProposerSlashing) GetProposalData2() *ProposalSignedData {
	if m != nil {
		return m.ProposalData2
	}
	return nil
}

func (m *ProposerSlashing) GetProposalSignature2() []byte {
	if m != nil {
		return m.ProposalSignature2
	}
	return nil
}

type SlashableVoteData struct {
	AggregateSignaturePoC0Indices []uint32         `protobuf:"varint,1,rep,packed,name=AggregateSignaturePoC0Indices,proto3" json:"AggregateSignaturePoC0Indices,omitempty"`
	AggregateSignaturePoC1Indices []uint32         `protobuf:"varint,2,rep,packed,name=AggregateSignaturePoC1Indices,proto3" json:"AggregateSignaturePoC1Indices,omitempty"`
	Data                          *AttestationData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	AggregateSignature            []byte           `protobuf:"bytes,4,opt,name=AggregateSignature,proto3" json:"AggregateSignature,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}         `json:"-"`
	XXX_unrecognized              []byte           `json:"-"`
	XXX_sizecache                 int32            `json:"-"`
}

func (m *SlashableVoteData) Reset()         { *m = SlashableVoteData{} }
func (m *SlashableVoteData) String() string { return proto.CompactTextString(m) }
func (*SlashableVoteData) ProtoMessage()    {}
func (*SlashableVoteData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{5}
}
func (m *SlashableVoteData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlashableVoteData.Unmarshal(m, b)
}
func (m *SlashableVoteData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlashableVoteData.Marshal(b, m, deterministic)
}
func (dst *SlashableVoteData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashableVoteData.Merge(dst, src)
}
func (m *SlashableVoteData) XXX_Size() int {
	return xxx_messageInfo_SlashableVoteData.Size(m)
}
func (m *SlashableVoteData) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashableVoteData.DiscardUnknown(m)
}

var xxx_messageInfo_SlashableVoteData proto.InternalMessageInfo

func (m *SlashableVoteData) GetAggregateSignaturePoC0Indices() []uint32 {
	if m != nil {
		return m.AggregateSignaturePoC0Indices
	}
	return nil
}

func (m *SlashableVoteData) GetAggregateSignaturePoC1Indices() []uint32 {
	if m != nil {
		return m.AggregateSignaturePoC1Indices
	}
	return nil
}

func (m *SlashableVoteData) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SlashableVoteData) GetAggregateSignature() []byte {
	if m != nil {
		return m.AggregateSignature
	}
	return nil
}

type CasperSlashing struct {
	Vote0                *SlashableVoteData `protobuf:"bytes,1,opt,name=Vote0,proto3" json:"Vote0,omitempty"`
	Vote1                *SlashableVoteData `protobuf:"bytes,2,opt,name=Vote1,proto3" json:"Vote1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CasperSlashing) Reset()         { *m = CasperSlashing{} }
func (m *CasperSlashing) String() string { return proto.CompactTextString(m) }
func (*CasperSlashing) ProtoMessage()    {}
func (*CasperSlashing) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{6}
}
func (m *CasperSlashing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CasperSlashing.Unmarshal(m, b)
}
func (m *CasperSlashing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CasperSlashing.Marshal(b, m, deterministic)
}
func (dst *CasperSlashing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CasperSlashing.Merge(dst, src)
}
func (m *CasperSlashing) XXX_Size() int {
	return xxx_messageInfo_CasperSlashing.Size(m)
}
func (m *CasperSlashing) XXX_DiscardUnknown() {
	xxx_messageInfo_CasperSlashing.DiscardUnknown(m)
}

var xxx_messageInfo_CasperSlashing proto.InternalMessageInfo

func (m *CasperSlashing) GetVote0() *SlashableVoteData {
	if m != nil {
		return m.Vote0
	}
	return nil
}

func (m *CasperSlashing) GetVote1() *SlashableVoteData {
	if m != nil {
		return m.Vote1
	}
	return nil
}

type AttestationData struct {
	Slot            uint64 `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	BeaconBlockHash []byte `protobuf:"bytes,2,opt,name=BeaconBlockHash,proto3" json:"BeaconBlockHash,omitempty"`
	// This is the destination root
	TargetEpoch uint64 `protobuf:"varint,3,opt,name=TargetEpoch,proto3" json:"TargetEpoch,omitempty"`
	TargetHash  []byte `protobuf:"bytes,4,opt,name=TargetHash,proto3" json:"TargetHash,omitempty"`
	SourceEpoch uint64 `protobuf:"varint,5,opt,name=SourceEpoch,proto3" json:"SourceEpoch,omitempty"`
	SourceHash  []byte `protobuf:"bytes,6,opt,name=SourceHash,proto3" json:"SourceHash,omitempty"`
	// Crosslink vote
	ShardBlockHash       []byte   `protobuf:"bytes,7,opt,name=ShardBlockHash,proto3" json:"ShardBlockHash,omitempty"`
	Shard                uint64   `protobuf:"varint,8,opt,name=Shard,proto3" json:"Shard,omitempty"`
	LatestCrosslinkHash  []byte   `protobuf:"bytes,9,opt,name=LatestCrosslinkHash,proto3" json:"LatestCrosslinkHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationData) Reset()         { *m = AttestationData{} }
func (m *AttestationData) String() string { return proto.CompactTextString(m) }
func (*AttestationData) ProtoMessage()    {}
func (*AttestationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{7}
}
func (m *AttestationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationData.Unmarshal(m, b)
}
func (m *AttestationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationData.Marshal(b, m, deterministic)
}
func (dst *AttestationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationData.Merge(dst, src)
}
func (m *AttestationData) XXX_Size() int {
	return xxx_messageInfo_AttestationData.Size(m)
}
func (m *AttestationData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationData.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationData proto.InternalMessageInfo

func (m *AttestationData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationData) GetBeaconBlockHash() []byte {
	if m != nil {
		return m.BeaconBlockHash
	}
	return nil
}

func (m *AttestationData) GetTargetEpoch() uint64 {
	if m != nil {
		return m.TargetEpoch
	}
	return 0
}

func (m *AttestationData) GetTargetHash() []byte {
	if m != nil {
		return m.TargetHash
	}
	return nil
}

func (m *AttestationData) GetSourceEpoch() uint64 {
	if m != nil {
		return m.SourceEpoch
	}
	return 0
}

func (m *AttestationData) GetSourceHash() []byte {
	if m != nil {
		return m.SourceHash
	}
	return nil
}

func (m *AttestationData) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *AttestationData) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *AttestationData) GetLatestCrosslinkHash() []byte {
	if m != nil {
		return m.LatestCrosslinkHash
	}
	return nil
}

type AttestationDataAndCustodyBit struct {
	Data                 *AttestationData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	PoCBit               bool             `protobuf:"varint,2,opt,name=PoCBit,proto3" json:"PoCBit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AttestationDataAndCustodyBit) Reset()         { *m = AttestationDataAndCustodyBit{} }
func (m *AttestationDataAndCustodyBit) String() string { return proto.CompactTextString(m) }
func (*AttestationDataAndCustodyBit) ProtoMessage()    {}
func (*AttestationDataAndCustodyBit) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{8}
}
func (m *AttestationDataAndCustodyBit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationDataAndCustodyBit.Unmarshal(m, b)
}
func (m *AttestationDataAndCustodyBit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationDataAndCustodyBit.Marshal(b, m, deterministic)
}
func (dst *AttestationDataAndCustodyBit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationDataAndCustodyBit.Merge(dst, src)
}
func (m *AttestationDataAndCustodyBit) XXX_Size() int {
	return xxx_messageInfo_AttestationDataAndCustodyBit.Size(m)
}
func (m *AttestationDataAndCustodyBit) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationDataAndCustodyBit.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationDataAndCustodyBit proto.InternalMessageInfo

func (m *AttestationDataAndCustodyBit) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AttestationDataAndCustodyBit) GetPoCBit() bool {
	if m != nil {
		return m.PoCBit
	}
	return false
}

type Attestation struct {
	Data                  *AttestationData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	ParticipationBitfield []byte           `protobuf:"bytes,2,opt,name=ParticipationBitfield,proto3" json:"ParticipationBitfield,omitempty"`
	CustodyBitfield       []byte           `protobuf:"bytes,3,opt,name=CustodyBitfield,proto3" json:"CustodyBitfield,omitempty"`
	AggregateSig          []byte           `protobuf:"bytes,4,opt,name=AggregateSig,proto3" json:"AggregateSig,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{9}
}
func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (dst *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(dst, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Attestation) GetParticipationBitfield() []byte {
	if m != nil {
		return m.ParticipationBitfield
	}
	return nil
}

func (m *Attestation) GetCustodyBitfield() []byte {
	if m != nil {
		return m.CustodyBitfield
	}
	return nil
}

func (m *Attestation) GetAggregateSig() []byte {
	if m != nil {
		return m.AggregateSig
	}
	return nil
}

type DepositParameters struct {
	PublicKey             []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	ProofOfPossession     []byte   `protobuf:"bytes,2,opt,name=ProofOfPossession,proto3" json:"ProofOfPossession,omitempty"`
	WithdrawalCredentials []byte   `protobuf:"bytes,3,opt,name=WithdrawalCredentials,proto3" json:"WithdrawalCredentials,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DepositParameters) Reset()         { *m = DepositParameters{} }
func (m *DepositParameters) String() string { return proto.CompactTextString(m) }
func (*DepositParameters) ProtoMessage()    {}
func (*DepositParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{10}
}
func (m *DepositParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositParameters.Unmarshal(m, b)
}
func (m *DepositParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositParameters.Marshal(b, m, deterministic)
}
func (dst *DepositParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositParameters.Merge(dst, src)
}
func (m *DepositParameters) XXX_Size() int {
	return xxx_messageInfo_DepositParameters.Size(m)
}
func (m *DepositParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositParameters.DiscardUnknown(m)
}

var xxx_messageInfo_DepositParameters proto.InternalMessageInfo

func (m *DepositParameters) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *DepositParameters) GetProofOfPossession() []byte {
	if m != nil {
		return m.ProofOfPossession
	}
	return nil
}

func (m *DepositParameters) GetWithdrawalCredentials() []byte {
	if m != nil {
		return m.WithdrawalCredentials
	}
	return nil
}

type Deposit struct {
	Parameters           *DepositParameters `protobuf:"bytes,1,opt,name=Parameters,proto3" json:"Parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Deposit) Reset()         { *m = Deposit{} }
func (m *Deposit) String() string { return proto.CompactTextString(m) }
func (*Deposit) ProtoMessage()    {}
func (*Deposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{11}
}
func (m *Deposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deposit.Unmarshal(m, b)
}
func (m *Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deposit.Marshal(b, m, deterministic)
}
func (dst *Deposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposit.Merge(dst, src)
}
func (m *Deposit) XXX_Size() int {
	return xxx_messageInfo_Deposit.Size(m)
}
func (m *Deposit) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposit.DiscardUnknown(m)
}

var xxx_messageInfo_Deposit proto.InternalMessageInfo

func (m *Deposit) GetParameters() *DepositParameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Exit struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	ValidatorIndex       uint64   `protobuf:"varint,2,opt,name=ValidatorIndex,proto3" json:"ValidatorIndex,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exit) Reset()         { *m = Exit{} }
func (m *Exit) String() string { return proto.CompactTextString(m) }
func (*Exit) ProtoMessage()    {}
func (*Exit) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{12}
}
func (m *Exit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exit.Unmarshal(m, b)
}
func (m *Exit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exit.Marshal(b, m, deterministic)
}
func (dst *Exit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exit.Merge(dst, src)
}
func (m *Exit) XXX_Size() int {
	return xxx_messageInfo_Exit.Size(m)
}
func (m *Exit) XXX_DiscardUnknown() {
	xxx_messageInfo_Exit.DiscardUnknown(m)
}

var xxx_messageInfo_Exit proto.InternalMessageInfo

func (m *Exit) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Exit) GetValidatorIndex() uint64 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

func (m *Exit) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Body                 *BlockBody   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{13}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() *BlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type BlockHeader struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	ParentRoot           []byte   `protobuf:"bytes,2,opt,name=ParentRoot,proto3" json:"ParentRoot,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,3,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	RandaoReveal         []byte   `protobuf:"bytes,4,opt,name=RandaoReveal,proto3" json:"RandaoReveal,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{14}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *BlockHeader) GetParentRoot() []byte {
	if m != nil {
		return m.ParentRoot
	}
	return nil
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BlockBody struct {
	Attestations         []*Attestation      `protobuf:"bytes,1,rep,name=Attestations,proto3" json:"Attestations,omitempty"`
	ProposerSlashings    []*ProposerSlashing `protobuf:"bytes,2,rep,name=ProposerSlashings,proto3" json:"ProposerSlashings,omitempty"`
	CasperSlashings      []*CasperSlashing   `protobuf:"bytes,3,rep,name=CasperSlashings,proto3" json:"CasperSlashings,omitempty"`
	Deposits             []*Deposit          `protobuf:"bytes,4,rep,name=Deposits,proto3" json:"Deposits,omitempty"`
	Exits                []*Exit             `protobuf:"bytes,5,rep,name=Exits,proto3" json:"Exits,omitempty"`
	Votes                []*AggregatedVote   `protobuf:"bytes,6,rep,name=Votes,proto3" json:"Votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{15}
}
func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (dst *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(dst, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetAttestations() []*Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func (m *BlockBody) GetProposerSlashings() []*ProposerSlashing {
	if m != nil {
		return m.ProposerSlashings
	}
	return nil
}

func (m *BlockBody) GetCasperSlashings() []*CasperSlashing {
	if m != nil {
		return m.CasperSlashings
	}
	return nil
}

func (m *BlockBody) GetDeposits() []*Deposit {
	if m != nil {
		return m.Deposits
	}
	return nil
}

func (m *BlockBody) GetExits() []*Exit {
	if m != nil {
		return m.Exits
	}
	return nil
}

func (m *BlockBody) GetVotes() []*AggregatedVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

type ForkData struct {
	PreForkVersion       uint64   `protobuf:"varint,1,opt,name=PreForkVersion,proto3" json:"PreForkVersion,omitempty"`
	PostForkVersion      uint64   `protobuf:"varint,2,opt,name=PostForkVersion,proto3" json:"PostForkVersion,omitempty"`
	ForkSlot             uint64   `protobuf:"varint,3,opt,name=ForkSlot,proto3" json:"ForkSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForkData) Reset()         { *m = ForkData{} }
func (m *ForkData) String() string { return proto.CompactTextString(m) }
func (*ForkData) ProtoMessage()    {}
func (*ForkData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{16}
}
func (m *ForkData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForkData.Unmarshal(m, b)
}
func (m *ForkData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForkData.Marshal(b, m, deterministic)
}
func (dst *ForkData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForkData.Merge(dst, src)
}
func (m *ForkData) XXX_Size() int {
	return xxx_messageInfo_ForkData.Size(m)
}
func (m *ForkData) XXX_DiscardUnknown() {
	xxx_messageInfo_ForkData.DiscardUnknown(m)
}

var xxx_messageInfo_ForkData proto.InternalMessageInfo

func (m *ForkData) GetPreForkVersion() uint64 {
	if m != nil {
		return m.PreForkVersion
	}
	return 0
}

func (m *ForkData) GetPostForkVersion() uint64 {
	if m != nil {
		return m.PostForkVersion
	}
	return 0
}

func (m *ForkData) GetForkSlot() uint64 {
	if m != nil {
		return m.ForkSlot
	}
	return 0
}

type Validator struct {
	Pubkey                  []byte   `protobuf:"bytes,1,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	WithdrawalCredentials   []byte   `protobuf:"bytes,2,opt,name=WithdrawalCredentials,proto3" json:"WithdrawalCredentials,omitempty"`
	Status                  uint64   `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	LatestStatusChangeSlot  uint64   `protobuf:"varint,5,opt,name=LatestStatusChangeSlot,proto3" json:"LatestStatusChangeSlot,omitempty"`
	ExitCount               uint64   `protobuf:"varint,6,opt,name=ExitCount,proto3" json:"ExitCount,omitempty"`
	LastPoCChangeSlot       uint64   `protobuf:"varint,7,opt,name=LastPoCChangeSlot,proto3" json:"LastPoCChangeSlot,omitempty"`
	SecondLastPoCChangeSlot uint64   `protobuf:"varint,8,opt,name=SecondLastPoCChangeSlot,proto3" json:"SecondLastPoCChangeSlot,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{17}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (dst *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(dst, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Validator) GetWithdrawalCredentials() []byte {
	if m != nil {
		return m.WithdrawalCredentials
	}
	return nil
}

func (m *Validator) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Validator) GetLatestStatusChangeSlot() uint64 {
	if m != nil {
		return m.LatestStatusChangeSlot
	}
	return 0
}

func (m *Validator) GetExitCount() uint64 {
	if m != nil {
		return m.ExitCount
	}
	return 0
}

func (m *Validator) GetLastPoCChangeSlot() uint64 {
	if m != nil {
		return m.LastPoCChangeSlot
	}
	return 0
}

func (m *Validator) GetSecondLastPoCChangeSlot() uint64 {
	if m != nil {
		return m.SecondLastPoCChangeSlot
	}
	return 0
}

type ShardCommittee struct {
	Shard                uint64   `protobuf:"varint,1,opt,name=Shard,proto3" json:"Shard,omitempty"`
	Committee            []uint32 `protobuf:"varint,2,rep,packed,name=Committee,proto3" json:"Committee,omitempty"`
	TotalValidatorCount  uint64   `protobuf:"varint,3,opt,name=TotalValidatorCount,proto3" json:"TotalValidatorCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardCommittee) Reset()         { *m = ShardCommittee{} }
func (m *ShardCommittee) String() string { return proto.CompactTextString(m) }
func (*ShardCommittee) ProtoMessage()    {}
func (*ShardCommittee) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{18}
}
func (m *ShardCommittee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCommittee.Unmarshal(m, b)
}
func (m *ShardCommittee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCommittee.Marshal(b, m, deterministic)
}
func (dst *ShardCommittee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCommittee.Merge(dst, src)
}
func (m *ShardCommittee) XXX_Size() int {
	return xxx_messageInfo_ShardCommittee.Size(m)
}
func (m *ShardCommittee) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCommittee.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCommittee proto.InternalMessageInfo

func (m *ShardCommittee) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *ShardCommittee) GetCommittee() []uint32 {
	if m != nil {
		return m.Committee
	}
	return nil
}

func (m *ShardCommittee) GetTotalValidatorCount() uint64 {
	if m != nil {
		return m.TotalValidatorCount
	}
	return 0
}

type ShardCommitteesForSlot struct {
	Committees           []*ShardCommittee `protobuf:"bytes,1,rep,name=Committees,proto3" json:"Committees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShardCommitteesForSlot) Reset()         { *m = ShardCommitteesForSlot{} }
func (m *ShardCommitteesForSlot) String() string { return proto.CompactTextString(m) }
func (*ShardCommitteesForSlot) ProtoMessage()    {}
func (*ShardCommitteesForSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{19}
}
func (m *ShardCommitteesForSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCommitteesForSlot.Unmarshal(m, b)
}
func (m *ShardCommitteesForSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCommitteesForSlot.Marshal(b, m, deterministic)
}
func (dst *ShardCommitteesForSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCommitteesForSlot.Merge(dst, src)
}
func (m *ShardCommitteesForSlot) XXX_Size() int {
	return xxx_messageInfo_ShardCommitteesForSlot.Size(m)
}
func (m *ShardCommitteesForSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCommitteesForSlot.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCommitteesForSlot proto.InternalMessageInfo

func (m *ShardCommitteesForSlot) GetCommittees() []*ShardCommittee {
	if m != nil {
		return m.Committees
	}
	return nil
}

type PersistentCommitteesForSlot struct {
	PersistentCommittee  []uint32 `protobuf:"varint,1,rep,packed,name=PersistentCommittee,proto3" json:"PersistentCommittee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersistentCommitteesForSlot) Reset()         { *m = PersistentCommitteesForSlot{} }
func (m *PersistentCommitteesForSlot) String() string { return proto.CompactTextString(m) }
func (*PersistentCommitteesForSlot) ProtoMessage()    {}
func (*PersistentCommitteesForSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{20}
}
func (m *PersistentCommitteesForSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentCommitteesForSlot.Unmarshal(m, b)
}
func (m *PersistentCommitteesForSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentCommitteesForSlot.Marshal(b, m, deterministic)
}
func (dst *PersistentCommitteesForSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentCommitteesForSlot.Merge(dst, src)
}
func (m *PersistentCommitteesForSlot) XXX_Size() int {
	return xxx_messageInfo_PersistentCommitteesForSlot.Size(m)
}
func (m *PersistentCommitteesForSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentCommitteesForSlot.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentCommitteesForSlot proto.InternalMessageInfo

func (m *PersistentCommitteesForSlot) GetPersistentCommittee() []uint32 {
	if m != nil {
		return m.PersistentCommittee
	}
	return nil
}

type Crosslink struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,2,opt,name=ShardBlockHash,proto3" json:"ShardBlockHash,omitempty"`
	ShardStateHash       []byte   `protobuf:"bytes,3,opt,name=ShardStateHash,proto3" json:"ShardStateHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crosslink) Reset()         { *m = Crosslink{} }
func (m *Crosslink) String() string { return proto.CompactTextString(m) }
func (*Crosslink) ProtoMessage()    {}
func (*Crosslink) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{21}
}
func (m *Crosslink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crosslink.Unmarshal(m, b)
}
func (m *Crosslink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crosslink.Marshal(b, m, deterministic)
}
func (dst *Crosslink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crosslink.Merge(dst, src)
}
func (m *Crosslink) XXX_Size() int {
	return xxx_messageInfo_Crosslink.Size(m)
}
func (m *Crosslink) XXX_DiscardUnknown() {
	xxx_messageInfo_Crosslink.DiscardUnknown(m)
}

var xxx_messageInfo_Crosslink proto.InternalMessageInfo

func (m *Crosslink) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Crosslink) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *Crosslink) GetShardStateHash() []byte {
	if m != nil {
		return m.ShardStateHash
	}
	return nil
}

type PendingAttestation struct {
	Data                  *AttestationData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	ParticipationBitfield []byte           `protobuf:"bytes,2,opt,name=ParticipationBitfield,proto3" json:"ParticipationBitfield,omitempty"`
	CustodyBitfield       []byte           `protobuf:"bytes,3,opt,name=CustodyBitfield,proto3" json:"CustodyBitfield,omitempty"`
	InclusionDelay        uint64           `protobuf:"varint,4,opt,name=InclusionDelay,proto3" json:"InclusionDelay,omitempty"`
	ProposerIndex         uint32           `protobuf:"varint,5,opt,name=ProposerIndex,proto3" json:"ProposerIndex,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *PendingAttestation) Reset()         { *m = PendingAttestation{} }
func (m *PendingAttestation) String() string { return proto.CompactTextString(m) }
func (*PendingAttestation) ProtoMessage()    {}
func (*PendingAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{22}
}
func (m *PendingAttestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingAttestation.Unmarshal(m, b)
}
func (m *PendingAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingAttestation.Marshal(b, m, deterministic)
}
func (dst *PendingAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingAttestation.Merge(dst, src)
}
func (m *PendingAttestation) XXX_Size() int {
	return xxx_messageInfo_PendingAttestation.Size(m)
}
func (m *PendingAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_PendingAttestation proto.InternalMessageInfo

func (m *PendingAttestation) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PendingAttestation) GetParticipationBitfield() []byte {
	if m != nil {
		return m.ParticipationBitfield
	}
	return nil
}

func (m *PendingAttestation) GetCustodyBitfield() []byte {
	if m != nil {
		return m.CustodyBitfield
	}
	return nil
}

func (m *PendingAttestation) GetInclusionDelay() uint64 {
	if m != nil {
		return m.InclusionDelay
	}
	return 0
}

func (m *PendingAttestation) GetProposerIndex() uint32 {
	if m != nil {
		return m.ProposerIndex
	}
	return 0
}

type State struct {
	Slot                               uint64                    `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	EpochIndex                         uint64                    `protobuf:"varint,2,opt,name=EpochIndex,proto3" json:"EpochIndex,omitempty"`
	GenesisTime                        uint64                    `protobuf:"varint,3,opt,name=GenesisTime,proto3" json:"GenesisTime,omitempty"`
	ForkData                           *ForkData                 `protobuf:"bytes,4,opt,name=ForkData,proto3" json:"ForkData,omitempty"`
	ValidatorRegistry                  []*Validator              `protobuf:"bytes,5,rep,name=ValidatorRegistry,proto3" json:"ValidatorRegistry,omitempty"`
	ValidatorBalances                  []uint64                  `protobuf:"varint,6,rep,packed,name=ValidatorBalances,proto3" json:"ValidatorBalances,omitempty"`
	ValidatorRegistryLatestChangeEpoch uint64                    `protobuf:"varint,7,opt,name=ValidatorRegistryLatestChangeEpoch,proto3" json:"ValidatorRegistryLatestChangeEpoch,omitempty"`
	ValidatorRegistryExitCount         uint64                    `protobuf:"varint,8,opt,name=ValidatorRegistryExitCount,proto3" json:"ValidatorRegistryExitCount,omitempty"`
	ValidatorRegistryDeltaChainTip     []byte                    `protobuf:"bytes,9,opt,name=ValidatorRegistryDeltaChainTip,proto3" json:"ValidatorRegistryDeltaChainTip,omitempty"`
	RandaoMix                          []byte                    `protobuf:"bytes,10,opt,name=RandaoMix,proto3" json:"RandaoMix,omitempty"`
	NextRandaoMix                      []byte                    `protobuf:"bytes,11,opt,name=NextRandaoMix,proto3" json:"NextRandaoMix,omitempty"`
	ShardCommittees                    []*ShardCommitteesForSlot `protobuf:"bytes,12,rep,name=ShardCommittees,proto3" json:"ShardCommittees,omitempty"`
	PreviousJustifiedEpoch             uint64                    `protobuf:"varint,13,opt,name=PreviousJustifiedEpoch,proto3" json:"PreviousJustifiedEpoch,omitempty"`
	JustifiedEpoch                     uint64                    `protobuf:"varint,14,opt,name=JustifiedEpoch,proto3" json:"JustifiedEpoch,omitempty"`
	JustificationBitField              uint64                    `protobuf:"varint,15,opt,name=JustificationBitField,proto3" json:"JustificationBitField,omitempty"`
	FinalizedEpoch                     uint64                    `protobuf:"varint,16,opt,name=FinalizedEpoch,proto3" json:"FinalizedEpoch,omitempty"`
	LatestCrosslinks                   []*Crosslink              `protobuf:"bytes,17,rep,name=LatestCrosslinks,proto3" json:"LatestCrosslinks,omitempty"`
	PreviousCrosslinks                 []*Crosslink              `protobuf:"bytes,18,rep,name=PreviousCrosslinks,proto3" json:"PreviousCrosslinks,omitempty"`
	ShardRegistry                      [][]byte                  `protobuf:"bytes,19,rep,name=ShardRegistry,proto3" json:"ShardRegistry,omitempty"`
	LatestBlockHashes                  [][]byte                  `protobuf:"bytes,20,rep,name=LatestBlockHashes,proto3" json:"LatestBlockHashes,omitempty"`
	CurrentEpochAttestations           []*PendingAttestation     `protobuf:"bytes,21,rep,name=CurrentEpochAttestations,proto3" json:"CurrentEpochAttestations,omitempty"`
	PreviousEpochAttestations          []*PendingAttestation     `protobuf:"bytes,22,rep,name=PreviousEpochAttestations,proto3" json:"PreviousEpochAttestations,omitempty"`
	BatchedBlockRoots                  [][]byte                  `protobuf:"bytes,23,rep,name=BatchedBlockRoots,proto3" json:"BatchedBlockRoots,omitempty"`
	Proposals                          []*ActiveProposal         `protobuf:"bytes,24,rep,name=Proposals,proto3" json:"Proposals,omitempty"`
	PendingVotes                       []*AggregatedVote         `protobuf:"bytes,25,rep,name=PendingVotes,proto3" json:"PendingVotes,omitempty"`
	XXX_NoUnkeyedLiteral               struct{}                  `json:"-"`
	XXX_unrecognized                   []byte                    `json:"-"`
	XXX_sizecache                      int32                     `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{23}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *State) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

func (m *State) GetGenesisTime() uint64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

func (m *State) GetForkData() *ForkData {
	if m != nil {
		return m.ForkData
	}
	return nil
}

func (m *State) GetValidatorRegistry() []*Validator {
	if m != nil {
		return m.ValidatorRegistry
	}
	return nil
}

func (m *State) GetValidatorBalances() []uint64 {
	if m != nil {
		return m.ValidatorBalances
	}
	return nil
}

func (m *State) GetValidatorRegistryLatestChangeEpoch() uint64 {
	if m != nil {
		return m.ValidatorRegistryLatestChangeEpoch
	}
	return 0
}

func (m *State) GetValidatorRegistryExitCount() uint64 {
	if m != nil {
		return m.ValidatorRegistryExitCount
	}
	return 0
}

func (m *State) GetValidatorRegistryDeltaChainTip() []byte {
	if m != nil {
		return m.ValidatorRegistryDeltaChainTip
	}
	return nil
}

func (m *State) GetRandaoMix() []byte {
	if m != nil {
		return m.RandaoMix
	}
	return nil
}

func (m *State) GetNextRandaoMix() []byte {
	if m != nil {
		return m.NextRandaoMix
	}
	return nil
}

func (m *State) GetShardCommittees() []*ShardCommitteesForSlot {
	if m != nil {
		return m.ShardCommittees
	}
	return nil
}

func (m *State) GetPreviousJustifiedEpoch() uint64 {
	if m != nil {
		return m.PreviousJustifiedEpoch
	}
	return 0
}

func (m *State) GetJustifiedEpoch() uint64 {
	if m != nil {
		return m.JustifiedEpoch
	}
	return 0
}

func (m *State) GetJustificationBitField() uint64 {
	if m != nil {
		return m.JustificationBitField
	}
	return 0
}

func (m *State) GetFinalizedEpoch() uint64 {
	if m != nil {
		return m.FinalizedEpoch
	}
	return 0
}

func (m *State) GetLatestCrosslinks() []*Crosslink {
	if m != nil {
		return m.LatestCrosslinks
	}
	return nil
}

func (m *State) GetPreviousCrosslinks() []*Crosslink {
	if m != nil {
		return m.PreviousCrosslinks
	}
	return nil
}

func (m *State) GetShardRegistry() [][]byte {
	if m != nil {
		return m.ShardRegistry
	}
	return nil
}

func (m *State) GetLatestBlockHashes() [][]byte {
	if m != nil {
		return m.LatestBlockHashes
	}
	return nil
}

func (m *State) GetCurrentEpochAttestations() []*PendingAttestation {
	if m != nil {
		return m.CurrentEpochAttestations
	}
	return nil
}

func (m *State) GetPreviousEpochAttestations() []*PendingAttestation {
	if m != nil {
		return m.PreviousEpochAttestations
	}
	return nil
}

func (m *State) GetBatchedBlockRoots() [][]byte {
	if m != nil {
		return m.BatchedBlockRoots
	}
	return nil
}

func (m *State) GetProposals() []*ActiveProposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

func (m *State) GetPendingVotes() []*AggregatedVote {
	if m != nil {
		return m.PendingVotes
	}
	return nil
}

type ValidatorRegistryDeltaBlock struct {
	LatestRegistryDeltaRoot []byte   `protobuf:"bytes,1,opt,name=LatestRegistryDeltaRoot,proto3" json:"LatestRegistryDeltaRoot,omitempty"`
	ValidatorIndex          uint32   `protobuf:"varint,2,opt,name=ValidatorIndex,proto3" json:"ValidatorIndex,omitempty"`
	Pubkey                  []byte   `protobuf:"bytes,3,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Flag                    uint64   `protobuf:"varint,4,opt,name=Flag,proto3" json:"Flag,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ValidatorRegistryDeltaBlock) Reset()         { *m = ValidatorRegistryDeltaBlock{} }
func (m *ValidatorRegistryDeltaBlock) String() string { return proto.CompactTextString(m) }
func (*ValidatorRegistryDeltaBlock) ProtoMessage()    {}
func (*ValidatorRegistryDeltaBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{24}
}
func (m *ValidatorRegistryDeltaBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorRegistryDeltaBlock.Unmarshal(m, b)
}
func (m *ValidatorRegistryDeltaBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorRegistryDeltaBlock.Marshal(b, m, deterministic)
}
func (dst *ValidatorRegistryDeltaBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorRegistryDeltaBlock.Merge(dst, src)
}
func (m *ValidatorRegistryDeltaBlock) XXX_Size() int {
	return xxx_messageInfo_ValidatorRegistryDeltaBlock.Size(m)
}
func (m *ValidatorRegistryDeltaBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorRegistryDeltaBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorRegistryDeltaBlock proto.InternalMessageInfo

func (m *ValidatorRegistryDeltaBlock) GetLatestRegistryDeltaRoot() []byte {
	if m != nil {
		return m.LatestRegistryDeltaRoot
	}
	return nil
}

func (m *ValidatorRegistryDeltaBlock) GetValidatorIndex() uint32 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

func (m *ValidatorRegistryDeltaBlock) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *ValidatorRegistryDeltaBlock) GetFlag() uint64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type AttestationRequest struct {
	// possibly sign this message to prevent DoS
	ParticipationBitfield []byte   `protobuf:"bytes,1,opt,name=ParticipationBitfield,proto3" json:"ParticipationBitfield,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *AttestationRequest) Reset()         { *m = AttestationRequest{} }
func (m *AttestationRequest) String() string { return proto.CompactTextString(m) }
func (*AttestationRequest) ProtoMessage()    {}
func (*AttestationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{25}
}
func (m *AttestationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationRequest.Unmarshal(m, b)
}
func (m *AttestationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationRequest.Marshal(b, m, deterministic)
}
func (dst *AttestationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationRequest.Merge(dst, src)
}
func (m *AttestationRequest) XXX_Size() int {
	return xxx_messageInfo_AttestationRequest.Size(m)
}
func (m *AttestationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationRequest proto.InternalMessageInfo

func (m *AttestationRequest) GetParticipationBitfield() []byte {
	if m != nil {
		return m.ParticipationBitfield
	}
	return nil
}

type VoteData struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Shards               []uint32 `protobuf:"varint,2,rep,packed,name=Shards,proto3" json:"Shards,omitempty"`
	ActionHash           []byte   `protobuf:"bytes,3,opt,name=ActionHash,proto3" json:"ActionHash,omitempty"`
	Proposer             uint32   `protobuf:"varint,4,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteData) Reset()         { *m = VoteData{} }
func (m *VoteData) String() string { return proto.CompactTextString(m) }
func (*VoteData) ProtoMessage()    {}
func (*VoteData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{26}
}
func (m *VoteData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteData.Unmarshal(m, b)
}
func (m *VoteData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteData.Marshal(b, m, deterministic)
}
func (dst *VoteData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteData.Merge(dst, src)
}
func (m *VoteData) XXX_Size() int {
	return xxx_messageInfo_VoteData.Size(m)
}
func (m *VoteData) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteData.DiscardUnknown(m)
}

var xxx_messageInfo_VoteData proto.InternalMessageInfo

func (m *VoteData) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *VoteData) GetShards() []uint32 {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *VoteData) GetActionHash() []byte {
	if m != nil {
		return m.ActionHash
	}
	return nil
}

func (m *VoteData) GetProposer() uint32 {
	if m != nil {
		return m.Proposer
	}
	return 0
}

type AggregatedVote struct {
	Data                 *VoteData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Participation        []byte    `protobuf:"bytes,3,opt,name=Participation,proto3" json:"Participation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AggregatedVote) Reset()         { *m = AggregatedVote{} }
func (m *AggregatedVote) String() string { return proto.CompactTextString(m) }
func (*AggregatedVote) ProtoMessage()    {}
func (*AggregatedVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{27}
}
func (m *AggregatedVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatedVote.Unmarshal(m, b)
}
func (m *AggregatedVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatedVote.Marshal(b, m, deterministic)
}
func (dst *AggregatedVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedVote.Merge(dst, src)
}
func (m *AggregatedVote) XXX_Size() int {
	return xxx_messageInfo_AggregatedVote.Size(m)
}
func (m *AggregatedVote) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedVote.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedVote proto.InternalMessageInfo

func (m *AggregatedVote) GetData() *VoteData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AggregatedVote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AggregatedVote) GetParticipation() []byte {
	if m != nil {
		return m.Participation
	}
	return nil
}

type ActiveProposal struct {
	Data                 *VoteData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Participation        []byte    `protobuf:"bytes,2,opt,name=Participation,proto3" json:"Participation,omitempty"`
	StartEpoch           uint64    `protobuf:"varint,3,opt,name=StartEpoch,proto3" json:"StartEpoch,omitempty"`
	Queued               bool      `protobuf:"varint,4,opt,name=Queued,proto3" json:"Queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActiveProposal) Reset()         { *m = ActiveProposal{} }
func (m *ActiveProposal) String() string { return proto.CompactTextString(m) }
func (*ActiveProposal) ProtoMessage()    {}
func (*ActiveProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{28}
}
func (m *ActiveProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveProposal.Unmarshal(m, b)
}
func (m *ActiveProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveProposal.Marshal(b, m, deterministic)
}
func (dst *ActiveProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveProposal.Merge(dst, src)
}
func (m *ActiveProposal) XXX_Size() int {
	return xxx_messageInfo_ActiveProposal.Size(m)
}
func (m *ActiveProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveProposal.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveProposal proto.InternalMessageInfo

func (m *ActiveProposal) GetData() *VoteData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ActiveProposal) GetParticipation() []byte {
	if m != nil {
		return m.Participation
	}
	return nil
}

func (m *ActiveProposal) GetStartEpoch() uint64 {
	if m != nil {
		return m.StartEpoch
	}
	return 0
}

func (m *ActiveProposal) GetQueued() bool {
	if m != nil {
		return m.Queued
	}
	return false
}

type ShardBlock struct {
	Header               *ShardBlockHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Body                 *ShardBlockBody   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShardBlock) Reset()         { *m = ShardBlock{} }
func (m *ShardBlock) String() string { return proto.CompactTextString(m) }
func (*ShardBlock) ProtoMessage()    {}
func (*ShardBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{29}
}
func (m *ShardBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardBlock.Unmarshal(m, b)
}
func (m *ShardBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardBlock.Marshal(b, m, deterministic)
}
func (dst *ShardBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardBlock.Merge(dst, src)
}
func (m *ShardBlock) XXX_Size() int {
	return xxx_messageInfo_ShardBlock.Size(m)
}
func (m *ShardBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ShardBlock proto.InternalMessageInfo

func (m *ShardBlock) GetHeader() *ShardBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ShardBlock) GetBody() *ShardBlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type ShardBlockHeader struct {
	PreviousBlockHash    []byte   `protobuf:"bytes,1,opt,name=PreviousBlockHash,proto3" json:"PreviousBlockHash,omitempty"`
	Slot                 uint64   `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,4,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	TransactionRoot      []byte   `protobuf:"bytes,5,opt,name=TransactionRoot,proto3" json:"TransactionRoot,omitempty"`
	FinalizedBeaconHash  []byte   `protobuf:"bytes,6,opt,name=FinalizedBeaconHash,proto3" json:"FinalizedBeaconHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardBlockHeader) Reset()         { *m = ShardBlockHeader{} }
func (m *ShardBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ShardBlockHeader) ProtoMessage()    {}
func (*ShardBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{30}
}
func (m *ShardBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardBlockHeader.Unmarshal(m, b)
}
func (m *ShardBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardBlockHeader.Marshal(b, m, deterministic)
}
func (dst *ShardBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardBlockHeader.Merge(dst, src)
}
func (m *ShardBlockHeader) XXX_Size() int {
	return xxx_messageInfo_ShardBlockHeader.Size(m)
}
func (m *ShardBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ShardBlockHeader proto.InternalMessageInfo

func (m *ShardBlockHeader) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func (m *ShardBlockHeader) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ShardBlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ShardBlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *ShardBlockHeader) GetTransactionRoot() []byte {
	if m != nil {
		return m.TransactionRoot
	}
	return nil
}

func (m *ShardBlockHeader) GetFinalizedBeaconHash() []byte {
	if m != nil {
		return m.FinalizedBeaconHash
	}
	return nil
}

type ShardBlockBody struct {
	Transactions         []*ShardTransaction `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ShardBlockBody) Reset()         { *m = ShardBlockBody{} }
func (m *ShardBlockBody) String() string { return proto.CompactTextString(m) }
func (*ShardBlockBody) ProtoMessage()    {}
func (*ShardBlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{31}
}
func (m *ShardBlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardBlockBody.Unmarshal(m, b)
}
func (m *ShardBlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardBlockBody.Marshal(b, m, deterministic)
}
func (dst *ShardBlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardBlockBody.Merge(dst, src)
}
func (m *ShardBlockBody) XXX_Size() int {
	return xxx_messageInfo_ShardBlockBody.Size(m)
}
func (m *ShardBlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardBlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_ShardBlockBody proto.InternalMessageInfo

func (m *ShardBlockBody) GetTransactions() []*ShardTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ShardTransaction struct {
	TransactionData      []byte   `protobuf:"bytes,1,opt,name=TransactionData,proto3" json:"TransactionData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardTransaction) Reset()         { *m = ShardTransaction{} }
func (m *ShardTransaction) String() string { return proto.CompactTextString(m) }
func (*ShardTransaction) ProtoMessage()    {}
func (*ShardTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{32}
}
func (m *ShardTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardTransaction.Unmarshal(m, b)
}
func (m *ShardTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardTransaction.Marshal(b, m, deterministic)
}
func (dst *ShardTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardTransaction.Merge(dst, src)
}
func (m *ShardTransaction) XXX_Size() int {
	return xxx_messageInfo_ShardTransaction.Size(m)
}
func (m *ShardTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ShardTransaction proto.InternalMessageInfo

func (m *ShardTransaction) GetTransactionData() []byte {
	if m != nil {
		return m.TransactionData
	}
	return nil
}

type VerificationWitness struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	WitnessBitfield      []byte   `protobuf:"bytes,3,opt,name=WitnessBitfield,proto3" json:"WitnessBitfield,omitempty"`
	WitnessHashes        [][]byte `protobuf:"bytes,4,rep,name=WitnessHashes,proto3" json:"WitnessHashes,omitempty"`
	LastLevel            uint32   `protobuf:"varint,5,opt,name=LastLevel,proto3" json:"LastLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationWitness) Reset()         { *m = VerificationWitness{} }
func (m *VerificationWitness) String() string { return proto.CompactTextString(m) }
func (*VerificationWitness) ProtoMessage()    {}
func (*VerificationWitness) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{33}
}
func (m *VerificationWitness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationWitness.Unmarshal(m, b)
}
func (m *VerificationWitness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationWitness.Marshal(b, m, deterministic)
}
func (dst *VerificationWitness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationWitness.Merge(dst, src)
}
func (m *VerificationWitness) XXX_Size() int {
	return xxx_messageInfo_VerificationWitness.Size(m)
}
func (m *VerificationWitness) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationWitness.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationWitness proto.InternalMessageInfo

func (m *VerificationWitness) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *VerificationWitness) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *VerificationWitness) GetWitnessBitfield() []byte {
	if m != nil {
		return m.WitnessBitfield
	}
	return nil
}

func (m *VerificationWitness) GetWitnessHashes() [][]byte {
	if m != nil {
		return m.WitnessHashes
	}
	return nil
}

func (m *VerificationWitness) GetLastLevel() uint32 {
	if m != nil {
		return m.LastLevel
	}
	return 0
}

type UpdateWitness struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	OldValue             []byte   `protobuf:"bytes,2,opt,name=OldValue,proto3" json:"OldValue,omitempty"`
	NewValue             []byte   `protobuf:"bytes,3,opt,name=NewValue,proto3" json:"NewValue,omitempty"`
	WitnessBitfield      []byte   `protobuf:"bytes,4,opt,name=WitnessBitfield,proto3" json:"WitnessBitfield,omitempty"`
	WitnessHashes        [][]byte `protobuf:"bytes,5,rep,name=WitnessHashes,proto3" json:"WitnessHashes,omitempty"`
	LastLevel            uint32   `protobuf:"varint,6,opt,name=LastLevel,proto3" json:"LastLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWitness) Reset()         { *m = UpdateWitness{} }
func (m *UpdateWitness) String() string { return proto.CompactTextString(m) }
func (*UpdateWitness) ProtoMessage()    {}
func (*UpdateWitness) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{34}
}
func (m *UpdateWitness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWitness.Unmarshal(m, b)
}
func (m *UpdateWitness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWitness.Marshal(b, m, deterministic)
}
func (dst *UpdateWitness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWitness.Merge(dst, src)
}
func (m *UpdateWitness) XXX_Size() int {
	return xxx_messageInfo_UpdateWitness.Size(m)
}
func (m *UpdateWitness) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWitness.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWitness proto.InternalMessageInfo

func (m *UpdateWitness) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *UpdateWitness) GetOldValue() []byte {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *UpdateWitness) GetNewValue() []byte {
	if m != nil {
		return m.NewValue
	}
	return nil
}

func (m *UpdateWitness) GetWitnessBitfield() []byte {
	if m != nil {
		return m.WitnessBitfield
	}
	return nil
}

func (m *UpdateWitness) GetWitnessHashes() [][]byte {
	if m != nil {
		return m.WitnessHashes
	}
	return nil
}

func (m *UpdateWitness) GetLastLevel() uint32 {
	if m != nil {
		return m.LastLevel
	}
	return 0
}

type TransactionPackage struct {
	VerificationWitnesses []*VerificationWitness `protobuf:"bytes,1,rep,name=VerificationWitnesses,proto3" json:"VerificationWitnesses,omitempty"`
	UpdateWitnesses       []*UpdateWitness       `protobuf:"bytes,2,rep,name=UpdateWitnesses,proto3" json:"UpdateWitnesses,omitempty"`
	Transactions          []*ShardTransaction    `protobuf:"bytes,3,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	StartRoot             []byte                 `protobuf:"bytes,4,opt,name=StartRoot,proto3" json:"StartRoot,omitempty"`
	EndRoot               []byte                 `protobuf:"bytes,5,opt,name=EndRoot,proto3" json:"EndRoot,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *TransactionPackage) Reset()         { *m = TransactionPackage{} }
func (m *TransactionPackage) String() string { return proto.CompactTextString(m) }
func (*TransactionPackage) ProtoMessage()    {}
func (*TransactionPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_a86371cb2c44223d, []int{35}
}
func (m *TransactionPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionPackage.Unmarshal(m, b)
}
func (m *TransactionPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionPackage.Marshal(b, m, deterministic)
}
func (dst *TransactionPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionPackage.Merge(dst, src)
}
func (m *TransactionPackage) XXX_Size() int {
	return xxx_messageInfo_TransactionPackage.Size(m)
}
func (m *TransactionPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionPackage.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionPackage proto.InternalMessageInfo

func (m *TransactionPackage) GetVerificationWitnesses() []*VerificationWitness {
	if m != nil {
		return m.VerificationWitnesses
	}
	return nil
}

func (m *TransactionPackage) GetUpdateWitnesses() []*UpdateWitness {
	if m != nil {
		return m.UpdateWitnesses
	}
	return nil
}

func (m *TransactionPackage) GetTransactions() []*ShardTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *TransactionPackage) GetStartRoot() []byte {
	if m != nil {
		return m.StartRoot
	}
	return nil
}

func (m *TransactionPackage) GetEndRoot() []byte {
	if m != nil {
		return m.EndRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*SlotNumberResponse)(nil), "pb.SlotNumberResponse")
	proto.RegisterType((*ConnectMessage)(nil), "pb.ConnectMessage")
	proto.RegisterType((*ListeningAddressesResponse)(nil), "pb.ListeningAddressesResponse")
	proto.RegisterType((*ProposalSignedData)(nil), "pb.ProposalSignedData")
	proto.RegisterType((*ProposerSlashing)(nil), "pb.ProposerSlashing")
	proto.RegisterType((*SlashableVoteData)(nil), "pb.SlashableVoteData")
	proto.RegisterType((*CasperSlashing)(nil), "pb.CasperSlashing")
	proto.RegisterType((*AttestationData)(nil), "pb.AttestationData")
	proto.RegisterType((*AttestationDataAndCustodyBit)(nil), "pb.AttestationDataAndCustodyBit")
	proto.RegisterType((*Attestation)(nil), "pb.Attestation")
	proto.RegisterType((*DepositParameters)(nil), "pb.DepositParameters")
	proto.RegisterType((*Deposit)(nil), "pb.Deposit")
	proto.RegisterType((*Exit)(nil), "pb.Exit")
	proto.RegisterType((*Block)(nil), "pb.Block")
	proto.RegisterType((*BlockHeader)(nil), "pb.BlockHeader")
	proto.RegisterType((*BlockBody)(nil), "pb.BlockBody")
	proto.RegisterType((*ForkData)(nil), "pb.ForkData")
	proto.RegisterType((*Validator)(nil), "pb.Validator")
	proto.RegisterType((*ShardCommittee)(nil), "pb.ShardCommittee")
	proto.RegisterType((*ShardCommitteesForSlot)(nil), "pb.ShardCommitteesForSlot")
	proto.RegisterType((*PersistentCommitteesForSlot)(nil), "pb.PersistentCommitteesForSlot")
	proto.RegisterType((*Crosslink)(nil), "pb.Crosslink")
	proto.RegisterType((*PendingAttestation)(nil), "pb.PendingAttestation")
	proto.RegisterType((*State)(nil), "pb.State")
	proto.RegisterType((*ValidatorRegistryDeltaBlock)(nil), "pb.ValidatorRegistryDeltaBlock")
	proto.RegisterType((*AttestationRequest)(nil), "pb.AttestationRequest")
	proto.RegisterType((*VoteData)(nil), "pb.VoteData")
	proto.RegisterType((*AggregatedVote)(nil), "pb.AggregatedVote")
	proto.RegisterType((*ActiveProposal)(nil), "pb.ActiveProposal")
	proto.RegisterType((*ShardBlock)(nil), "pb.ShardBlock")
	proto.RegisterType((*ShardBlockHeader)(nil), "pb.ShardBlockHeader")
	proto.RegisterType((*ShardBlockBody)(nil), "pb.ShardBlockBody")
	proto.RegisterType((*ShardTransaction)(nil), "pb.ShardTransaction")
	proto.RegisterType((*VerificationWitness)(nil), "pb.VerificationWitness")
	proto.RegisterType((*UpdateWitness)(nil), "pb.UpdateWitness")
	proto.RegisterType((*TransactionPackage)(nil), "pb.TransactionPackage")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_a86371cb2c44223d) }

var fileDescriptor_common_a86371cb2c44223d = []byte{
	// 2066 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0x4f, 0x73, 0x1b, 0x49,
	0x15, 0x2f, 0xc9, 0x92, 0xff, 0x3c, 0xc9, 0xff, 0xda, 0xb1, 0x33, 0xeb, 0x0d, 0x2e, 0x33, 0x45,
	0x39, 0x2e, 0xd8, 0x4a, 0x39, 0xda, 0x65, 0x2b, 0xb0, 0x81, 0x22, 0x92, 0x63, 0x36, 0xc1, 0x49,
	0x44, 0xdb, 0x78, 0x2f, 0x54, 0x41, 0x5b, 0xd3, 0x91, 0x87, 0x8c, 0xa7, 0xc5, 0x74, 0xcb, 0xb1,
	0xf9, 0x14, 0x14, 0x05, 0x5f, 0x80, 0x2b, 0x45, 0x71, 0xe2, 0xc2, 0x95, 0x03, 0x1f, 0x06, 0x3e,
	0x00, 0x47, 0xea, 0x75, 0xf7, 0xcc, 0xf4, 0xfc, 0x91, 0xed, 0x23, 0x37, 0xf5, 0xef, 0xbd, 0x7e,
	0xfd, 0xfa, 0xf5, 0xfb, 0x3b, 0x82, 0xee, 0x48, 0x5c, 0x5e, 0x8a, 0xf8, 0xc9, 0x24, 0x11, 0x4a,
	0x90, 0xe6, 0xe4, 0xdc, 0x8f, 0x80, 0x9c, 0x44, 0x42, 0xbd, 0x9d, 0x5e, 0x9e, 0xf3, 0x84, 0x72,
	0x39, 0x11, 0xb1, 0xe4, 0x64, 0x07, 0x20, 0x47, 0xbd, 0xc6, 0x6e, 0x63, 0xbf, 0x45, 0x1d, 0x84,
	0x3c, 0x82, 0xa5, 0x7e, 0x24, 0x46, 0x1f, 0xbe, 0x66, 0xf2, 0xc2, 0x6b, 0xee, 0x36, 0xf6, 0xbb,
	0x34, 0x07, 0x88, 0x07, 0x0b, 0xa7, 0xe1, 0x04, 0xd9, 0xbd, 0x39, 0xbd, 0x35, 0x5d, 0xfa, 0xdf,
	0x85, 0x95, 0x81, 0x88, 0x63, 0x3e, 0x52, 0x6f, 0xb8, 0x94, 0x6c, 0xcc, 0x91, 0xf7, 0x45, 0x10,
	0x24, 0x5c, 0x4a, 0x7d, 0xcc, 0x12, 0x4d, 0x97, 0xfe, 0x0f, 0x61, 0xfb, 0x38, 0x94, 0x8a, 0xc7,
	0x61, 0x3c, 0xb6, 0x18, 0x97, 0x99, 0x86, 0x8f, 0x60, 0x29, 0x03, 0xbd, 0xc6, 0xee, 0xdc, 0xfe,
	0x12, 0xcd, 0x01, 0xff, 0x97, 0x40, 0x86, 0x89, 0x98, 0x08, 0xc9, 0xa2, 0x93, 0x70, 0x1c, 0xf3,
	0xe0, 0x90, 0x29, 0x46, 0x08, 0xb4, 0xb4, 0x52, 0xe6, 0x3e, 0xfa, 0x37, 0x79, 0x00, 0xed, 0x93,
	0x0b, 0x96, 0x04, 0xfa, 0x16, 0x2d, 0x6a, 0x16, 0xc5, 0xfb, 0xcd, 0x95, 0xee, 0xe7, 0xff, 0xb1,
	0x09, 0x6b, 0x46, 0x3c, 0x4f, 0x4e, 0x22, 0x26, 0x2f, 0xc2, 0x78, 0x4c, 0xbe, 0x03, 0xcb, 0x29,
	0xf6, 0x2a, 0x0e, 0xf8, 0xb5, 0x3e, 0x65, 0x99, 0x16, 0x41, 0xf2, 0x3c, 0xe5, 0x62, 0x11, 0xaa,
	0xf4, 0x54, 0x1f, 0xdb, 0xe9, 0x6d, 0x3d, 0x99, 0x9c, 0x3f, 0xa9, 0x6a, 0x4c, 0x8b, 0xcc, 0xe4,
	0x49, 0xf1, 0x5a, 0x4c, 0x4d, 0x13, 0xfe, 0xd4, 0xea, 0x57, 0x43, 0x29, 0x9f, 0xd6, 0xf3, 0x5a,
	0xf7, 0x3f, 0xad, 0x57, 0x7b, 0x5a, 0xcf, 0x6b, 0xcf, 0x38, 0xad, 0xe7, 0xff, 0xb7, 0x01, 0xeb,
	0xda, 0x1c, 0xec, 0x3c, 0xe2, 0x67, 0x42, 0x71, 0x6d, 0xf4, 0x43, 0xf8, 0xd6, 0x8b, 0xf1, 0x38,
	0xe1, 0x63, 0xa6, 0x78, 0xc6, 0x3c, 0x14, 0x83, 0x83, 0x57, 0x71, 0x10, 0x8e, 0xec, 0xe3, 0x2d,
	0xd3, 0xdb, 0x99, 0x66, 0x4a, 0x79, 0x9a, 0x4a, 0x69, 0xde, 0x22, 0x25, 0x65, 0x22, 0x8f, 0xa1,
	0x85, 0x3a, 0x69, 0x8b, 0x75, 0x7a, 0x1b, 0x68, 0x86, 0x17, 0x4a, 0x71, 0xa9, 0x98, 0x0a, 0x45,
	0xac, 0x6d, 0xa0, 0x19, 0xf0, 0xea, 0x55, 0x49, 0xda, 0x7a, 0x5d, 0x5a, 0x43, 0xf1, 0x7f, 0x03,
	0x2b, 0x03, 0x26, 0x27, 0x8e, 0x3b, 0x7c, 0x0f, 0xda, 0x68, 0x82, 0x03, 0xed, 0x06, 0x9d, 0xde,
	0x26, 0x9e, 0x55, 0x31, 0x0e, 0x35, 0x3c, 0x29, 0x73, 0xea, 0x0d, 0xb7, 0x31, 0x3f, 0xf5, 0xff,
	0xd9, 0x84, 0xd5, 0x92, 0xd6, 0xb5, 0x9e, 0xbd, 0x0f, 0xab, 0x7d, 0xce, 0x46, 0x22, 0x2e, 0x47,
	0x6a, 0x19, 0x26, 0xbb, 0xd0, 0x39, 0x65, 0xc9, 0x98, 0xab, 0x97, 0x13, 0x31, 0xba, 0xb0, 0x31,
	0xeb, 0x42, 0x98, 0x0f, 0xcc, 0x52, 0x8b, 0x31, 0x76, 0x70, 0x10, 0x94, 0x70, 0x22, 0xa6, 0xc9,
	0x88, 0x1b, 0x09, 0x6d, 0x23, 0xc1, 0x81, 0x74, 0x46, 0xd1, 0x4b, 0x2d, 0x61, 0xde, 0x48, 0xc8,
	0x11, 0xb2, 0x07, 0x2b, 0x3a, 0xf4, 0x72, 0x65, 0x17, 0x34, 0x4f, 0x09, 0xcd, 0xe3, 0x75, 0xd1,
	0x8d, 0xd7, 0x03, 0xd8, 0x38, 0x66, 0x68, 0x92, 0x41, 0x22, 0xa4, 0x8c, 0xc2, 0xd8, 0x88, 0x58,
	0xd2, 0x22, 0xea, 0x48, 0xfe, 0xaf, 0xe0, 0x51, 0xc9, 0x88, 0x2f, 0xe2, 0x60, 0x30, 0x95, 0x4a,
	0x04, 0x37, 0xfd, 0x50, 0x65, 0xae, 0xd2, 0xb8, 0xcb, 0x55, 0xb6, 0x60, 0x7e, 0x28, 0x06, 0xfd,
	0x50, 0x69, 0xeb, 0x2e, 0x52, 0xbb, 0xf2, 0xff, 0xd1, 0x80, 0x8e, 0xb3, 0xe3, 0xfe, 0x02, 0xbf,
	0x80, 0xcd, 0x21, 0x4b, 0x54, 0x38, 0x0a, 0x27, 0x9a, 0xd4, 0x0f, 0xd5, 0xfb, 0x90, 0x47, 0x81,
	0x7d, 0xbd, 0x7a, 0x22, 0xbe, 0x76, 0xae, 0xbd, 0xe1, 0x37, 0x79, 0xa1, 0x0c, 0x13, 0x1f, 0xba,
	0xae, 0x07, 0xdb, 0xd7, 0x2c, 0x60, 0xfe, 0x9f, 0x1a, 0xb0, 0x7e, 0xc8, 0x27, 0x42, 0x86, 0x6a,
	0xc8, 0x12, 0x76, 0xc9, 0x15, 0x4f, 0x24, 0x66, 0xc5, 0xe1, 0xf4, 0x3c, 0x0a, 0x47, 0x3f, 0xe3,
	0x37, 0xfa, 0x1e, 0x5d, 0x9a, 0x03, 0xe4, 0x33, 0x58, 0x1f, 0x26, 0x42, 0xbc, 0x7f, 0xf7, 0x7e,
	0x28, 0x30, 0x09, 0xcb, 0x50, 0xc4, 0x56, 0xe7, 0x2a, 0x01, 0x6f, 0xf9, 0x4d, 0xa8, 0x2e, 0x82,
	0x84, 0x7d, 0x64, 0xd1, 0x20, 0xe1, 0x01, 0x8f, 0x55, 0xc8, 0x22, 0x69, 0xb5, 0xae, 0x27, 0xfa,
	0x3f, 0x81, 0x05, 0xab, 0x16, 0xf9, 0x3e, 0x40, 0xae, 0x9a, 0x1b, 0x65, 0x15, 0xbd, 0xa9, 0xc3,
	0xe8, 0xff, 0x1a, 0x5a, 0x2f, 0xaf, 0x43, 0x55, 0x1b, 0x31, 0x7b, 0xb0, 0x72, 0xc6, 0xa2, 0x30,
	0x60, 0x4a, 0xd8, 0x1c, 0x6e, 0x8a, 0x42, 0x09, 0x45, 0x3b, 0xe4, 0x49, 0xc1, 0x56, 0x87, 0x3c,
	0x17, 0x9c, 0x40, 0x5b, 0xbb, 0x2b, 0x79, 0x0c, 0xf3, 0x5f, 0x73, 0x16, 0xd8, 0x02, 0xda, 0xe9,
	0xad, 0xa2, 0x76, 0xc6, 0x93, 0x35, 0x4c, 0x2d, 0x99, 0x7c, 0x1b, 0x5a, 0x7d, 0x11, 0xdc, 0xd8,
	0xe8, 0x5f, 0xce, 0xd8, 0x10, 0xa4, 0x9a, 0xe4, 0xff, 0xb5, 0x01, 0x1d, 0x67, 0xeb, 0x9d, 0x05,
	0x7a, 0x47, 0x5b, 0x87, 0xc7, 0x8a, 0x0a, 0xa1, 0xec, 0x2b, 0x38, 0x88, 0xbe, 0x82, 0x62, 0x8a,
	0x6b, 0x72, 0x7a, 0x85, 0x14, 0x40, 0x17, 0xa1, 0x2c, 0x0e, 0x98, 0xa0, 0xfc, 0x8a, 0xb3, 0x28,
	0x75, 0x11, 0x17, 0x2b, 0x1a, 0xa1, 0x5d, 0x36, 0xc2, 0xdf, 0x9b, 0xb6, 0x82, 0xa2, 0xf6, 0xe4,
	0x73, 0xe8, 0x3a, 0xbe, 0x6e, 0x52, 0xbe, 0xb5, 0x87, 0x83, 0xd3, 0x02, 0x13, 0xe9, 0x6b, 0x7f,
	0x2a, 0x14, 0x59, 0x93, 0xe6, 0x3b, 0xbd, 0x07, 0x79, 0x01, 0xcb, 0x89, 0xb4, 0xca, 0x4e, 0x9e,
	0xc3, 0x6a, 0x31, 0x2f, 0xa3, 0x7f, 0xa1, 0x04, 0x82, 0x12, 0x8a, 0x24, 0x5a, 0x66, 0x25, 0x8f,
	0x61, 0xd1, 0x3a, 0x93, 0xf4, 0x5a, 0x7a, 0x5b, 0xc7, 0x71, 0x30, 0x9a, 0x11, 0xc9, 0x0e, 0xb4,
	0xd1, 0xa9, 0xa4, 0xd7, 0xd6, 0x5c, 0x8b, 0xc8, 0x85, 0x00, 0x35, 0x30, 0xd9, 0x37, 0xf9, 0x5d,
	0x7a, 0xf3, 0xf9, 0xe1, 0x59, 0xbc, 0x05, 0x48, 0x32, 0xc9, 0x5d, 0xfa, 0xd7, 0xb0, 0x78, 0x24,
	0x92, 0x0f, 0x3a, 0x11, 0xec, 0xc1, 0xca, 0x30, 0xe1, 0xb8, 0x3c, 0xe3, 0x89, 0x8e, 0x26, 0xf3,
	0xce, 0x25, 0x14, 0x43, 0x7f, 0x28, 0xa4, 0x72, 0x19, 0x8d, 0xdf, 0x96, 0x61, 0xb2, 0x6d, 0xa4,
	0x3b, 0x9d, 0x59, 0xb6, 0xf6, 0xff, 0xd6, 0x84, 0xa5, 0xcc, 0xcf, 0x75, 0x56, 0x9b, 0x9e, 0x7f,
	0xc8, 0xe2, 0xdc, 0xae, 0x66, 0x87, 0x6d, 0xf3, 0x96, 0xb0, 0x45, 0x69, 0xe8, 0x5c, 0x53, 0xa9,
	0x3d, 0xa9, 0x45, 0xed, 0x8a, 0x7c, 0x09, 0x5b, 0x26, 0x37, 0x9b, 0xf5, 0xe0, 0x82, 0xc5, 0x63,
	0xae, 0xb5, 0x33, 0x15, 0x64, 0x06, 0x15, 0x7d, 0x0f, 0x0d, 0x3b, 0x10, 0xd3, 0x58, 0xe9, 0x5a,
	0xd2, 0xa2, 0x39, 0x80, 0x89, 0xe8, 0x98, 0x49, 0x35, 0x14, 0x03, 0x47, 0xe0, 0x82, 0xe6, 0xaa,
	0x12, 0xc8, 0x33, 0x78, 0x78, 0xc2, 0x47, 0x22, 0x0e, 0xaa, 0x7b, 0x4c, 0x89, 0x99, 0x45, 0xf6,
	0xaf, 0x6c, 0xc9, 0x1a, 0x88, 0xcb, 0xcb, 0x50, 0x29, 0xce, 0xf3, 0xe2, 0xd4, 0x28, 0x35, 0x93,
	0x19, 0x8b, 0xed, 0x53, 0x72, 0x00, 0x4b, 0xd7, 0xa9, 0x50, 0x2c, 0xca, 0x6c, 0x6f, 0x6e, 0x65,
	0x9e, 0xa7, 0x8e, 0xe4, 0x1f, 0xc3, 0x56, 0xf1, 0x5c, 0x79, 0x24, 0x12, 0x7d, 0x97, 0x1e, 0x40,
	0x0e, 0xda, 0x28, 0xd3, 0xce, 0x56, 0xe4, 0xa7, 0x0e, 0x97, 0xff, 0x0e, 0x3e, 0x1d, 0xa2, 0x7b,
	0x60, 0xa7, 0xad, 0xaa, 0x22, 0x0f, 0x60, 0xa3, 0x86, 0x6c, 0x9b, 0xb6, 0x3a, 0x92, 0x2f, 0x60,
	0x29, 0x2b, 0xb5, 0xb3, 0xd2, 0x6c, 0xa9, 0xd4, 0x37, 0x6b, 0x4b, 0x7d, 0xca, 0xa7, 0xf3, 0x92,
	0xd3, 0x89, 0x97, 0x50, 0xff, 0xdf, 0x0d, 0x20, 0x43, 0x1e, 0x07, 0x38, 0x27, 0xfc, 0x3f, 0x16,
	0xdc, 0x3d, 0x58, 0x79, 0x15, 0x8f, 0xa2, 0x29, 0x86, 0xe0, 0x21, 0x8f, 0xd8, 0x8d, 0x8d, 0x82,
	0x12, 0x5a, 0x9d, 0x20, 0xda, 0x35, 0x13, 0x84, 0xff, 0x67, 0x80, 0xb6, 0xbe, 0x7b, 0xad, 0x6d,
	0x77, 0x00, 0x74, 0xbf, 0xe5, 0x96, 0x2f, 0x07, 0xc1, 0x46, 0xed, 0xa7, 0x3c, 0xe6, 0x32, 0x94,
	0xa7, 0xe1, 0x25, 0x4f, 0x5b, 0x3d, 0x07, 0x22, 0xfb, 0x79, 0x06, 0xb2, 0xe3, 0x42, 0x17, 0x4d,
	0x97, 0x62, 0x34, 0xcf, 0x4f, 0x5f, 0xc1, 0x7a, 0xe6, 0x99, 0x94, 0x8f, 0x43, 0xa9, 0x92, 0x1b,
	0x9b, 0x01, 0x75, 0x0d, 0xcb, 0x89, 0x55, 0x3e, 0x0c, 0xd2, 0x0c, 0xec, 0xb3, 0x88, 0xc5, 0x23,
	0x9b, 0x1e, 0x5b, 0xb4, 0x4a, 0x20, 0x6f, 0xc1, 0xaf, 0x88, 0xb0, 0x5d, 0x9d, 0x8e, 0x47, 0xd3,
	0x76, 0x9a, 0x18, 0xbf, 0x07, 0x27, 0xf9, 0x31, 0x6c, 0x57, 0xb8, 0xf2, 0x8c, 0x62, 0xe2, 0xfe,
	0x16, 0x0e, 0x72, 0x04, 0x3b, 0x15, 0xea, 0x21, 0x8f, 0x14, 0x1b, 0x5c, 0xb0, 0x30, 0x3e, 0x0d,
	0x27, 0xb6, 0xf5, 0xbc, 0x83, 0x0b, 0x53, 0x83, 0x29, 0xaa, 0x6f, 0xc2, 0x6b, 0x0f, 0x4c, 0x11,
	0xcd, 0x00, 0x74, 0x88, 0xb7, 0xfc, 0x5a, 0xe5, 0x1c, 0x1d, 0xcd, 0x51, 0x04, 0xc9, 0x21, 0xac,
	0x96, 0xd2, 0x81, 0xd7, 0xd5, 0x8f, 0xb0, 0x5d, 0x8d, 0xfc, 0x34, 0xac, 0x69, 0x79, 0x0b, 0xa6,
	0xe2, 0x61, 0xc2, 0xaf, 0x42, 0x31, 0x95, 0xaf, 0xa7, 0x52, 0x85, 0xef, 0x43, 0x1e, 0x18, 0xab,
	0x2e, 0x9b, 0x54, 0x5c, 0x4f, 0x45, 0xe7, 0x2e, 0xf1, 0xaf, 0x18, 0xe7, 0x2e, 0xf1, 0x7d, 0x01,
	0x9b, 0x16, 0x19, 0xa5, 0x71, 0x74, 0xa4, 0x83, 0x66, 0x55, 0xb3, 0xd7, 0x13, 0x51, 0xfa, 0x51,
	0x18, 0xb3, 0x28, 0xfc, 0x5d, 0x2a, 0x7d, 0xcd, 0x48, 0x2f, 0xa2, 0xe4, 0x07, 0xb0, 0x56, 0x6a,
	0xf2, 0xa5, 0xb7, 0x9e, 0x7b, 0x62, 0x86, 0xd2, 0x0a, 0x1b, 0xf9, 0x11, 0x4e, 0xb9, 0xe6, 0x6a,
	0xce, 0x66, 0x52, 0xb7, 0xb9, 0x86, 0x11, 0xdf, 0x48, 0x9b, 0x32, 0x0b, 0x80, 0x8d, 0xdd, 0x39,
	0x7c, 0xa3, 0x02, 0x68, 0x4a, 0x12, 0x1e, 0x9c, 0x65, 0x37, 0x2e, 0xbd, 0x07, 0x9a, 0xb3, 0x4a,
	0x20, 0x14, 0xbc, 0xc1, 0x34, 0xc1, 0x5e, 0x4d, 0xdf, 0xae, 0xd0, 0x3a, 0x6d, 0x6a, 0xc5, 0xcc,
	0x04, 0x5f, 0xc9, 0x79, 0x74, 0xe6, 0x3e, 0x72, 0x0a, 0x9f, 0xa4, 0xda, 0x57, 0x85, 0x6e, 0xdd,
	0x2a, 0x74, 0xf6, 0x46, 0xbc, 0x57, 0x9f, 0xa9, 0xd1, 0x05, 0x37, 0x69, 0x1b, 0x9b, 0x47, 0xe9,
	0x3d, 0x34, 0xf7, 0xaa, 0x10, 0xc8, 0x01, 0x2c, 0xa5, 0x9f, 0x0d, 0xa4, 0xe7, 0x39, 0xad, 0xd0,
	0x48, 0x85, 0x57, 0x3c, 0x25, 0xd1, 0x9c, 0x89, 0x7c, 0x09, 0x5d, 0xab, 0x90, 0xe9, 0x9f, 0x3e,
	0x99, 0xd9, 0x3f, 0x15, 0xf8, 0xfc, 0xbf, 0x34, 0xe0, 0xd3, 0xfa, 0xd0, 0x33, 0xad, 0xf9, 0x33,
	0x78, 0x68, 0xcc, 0x5e, 0xa0, 0xe9, 0x66, 0xd8, 0xf4, 0x3b, 0xb3, 0xc8, 0x33, 0x66, 0x84, 0xe5,
	0xca, 0x8c, 0x90, 0x37, 0x50, 0x73, 0x85, 0x06, 0x8a, 0x40, 0xeb, 0x28, 0x62, 0x63, 0x5b, 0x02,
	0xf4, 0x6f, 0xff, 0x35, 0x10, 0xd7, 0xde, 0xfc, 0xb7, 0x53, 0x2e, 0xd5, 0xec, 0xb2, 0xd4, 0xb8,
	0xa5, 0x2c, 0xf9, 0x09, 0x2c, 0x66, 0x9f, 0x5e, 0x08, 0xb4, 0x4e, 0x6f, 0x26, 0xdc, 0x7e, 0x89,
	0xd2, 0xbf, 0x75, 0x2b, 0x86, 0xae, 0x99, 0x7e, 0x31, 0xb1, 0x2b, 0x2c, 0x1c, 0xf8, 0x0c, 0x22,
	0x76, 0x0a, 0xad, 0x83, 0x60, 0xeb, 0x98, 0xd6, 0x21, 0xad, 0xfb, 0x32, 0xcd, 0xd6, 0xd8, 0x08,
	0x15, 0x5f, 0x83, 0xec, 0x16, 0x6a, 0xaf, 0x2e, 0x20, 0xd9, 0x67, 0x0c, 0x53, 0x74, 0x0b, 0xe3,
	0x43, 0xb3, 0x34, 0x3e, 0xe8, 0x52, 0xe8, 0x5e, 0xcf, 0x2a, 0x54, 0x04, 0xfd, 0xdf, 0x37, 0x60,
	0xa5, 0xe8, 0x3b, 0xf7, 0x38, 0xb8, 0x22, 0xba, 0x59, 0x23, 0x5a, 0xcf, 0x57, 0x8a, 0x25, 0x85,
	0x2f, 0x22, 0x0e, 0x82, 0x66, 0xfc, 0xf9, 0x94, 0x4f, 0x79, 0xa0, 0x8d, 0xb1, 0x48, 0xed, 0xca,
	0x3f, 0x07, 0xc8, 0xbb, 0x18, 0xf2, 0x59, 0x69, 0x02, 0x7c, 0x90, 0x65, 0xe4, 0xba, 0x31, 0x70,
	0xaf, 0x30, 0x06, 0x92, 0x22, 0xaf, 0x33, 0x0b, 0xfe, 0xa7, 0x01, 0x6b, 0x65, 0x21, 0x66, 0xfa,
	0x36, 0x61, 0x9a, 0xf7, 0x55, 0x8d, 0x74, 0xfa, 0x2e, 0x11, 0xb2, 0xd6, 0xa1, 0xe9, 0xb4, 0x0e,
	0xb7, 0x4e, 0xb5, 0xc5, 0x81, 0xb1, 0x55, 0x1e, 0x18, 0xf7, 0x61, 0xf5, 0x34, 0x61, 0xb1, 0x64,
	0xda, 0x61, 0x34, 0x8f, 0x19, 0x09, 0xcb, 0x30, 0xf6, 0x93, 0x59, 0xee, 0x36, 0xdf, 0xa1, 0x9c,
	0x0f, 0x42, 0x75, 0x24, 0xff, 0xb5, 0xdb, 0x2e, 0xea, 0x71, 0xf2, 0x19, 0x74, 0x1d, 0xb1, 0x69,
	0xa3, 0x9b, 0x1b, 0xd7, 0x3d, 0xb3, 0xc0, 0xe9, 0x3f, 0xb7, 0x96, 0x73, 0xc0, 0x92, 0xee, 0x99,
	0xf7, 0x14, 0x75, 0x47, 0x18, 0xb3, 0xca, 0xc6, 0x19, 0x4f, 0xb2, 0x32, 0xf5, 0x4d, 0xa8, 0x62,
	0x2e, 0x25, 0x59, 0x83, 0xb9, 0xfc, 0x8b, 0x08, 0xfe, 0xc4, 0x41, 0xe0, 0x8c, 0x45, 0xd3, 0xd4,
	0xb3, 0xcd, 0x02, 0x4f, 0xb2, 0x5b, 0xca, 0x2d, 0x63, 0x09, 0x46, 0x27, 0xb5, 0x90, 0xad, 0x15,
	0x2d, 0x53, 0x55, 0x0a, 0x20, 0xbe, 0x09, 0x4e, 0x25, 0xc7, 0xfc, 0x8a, 0x47, 0xb6, 0x59, 0xcc,
	0x01, 0xff, 0x5f, 0x0d, 0x58, 0xfe, 0xc5, 0x24, 0x60, 0x8a, 0xcf, 0xd6, 0x73, 0x1b, 0x16, 0xdf,
	0x45, 0x81, 0xab, 0x6a, 0xb6, 0x46, 0xda, 0x5b, 0xfe, 0xd1, 0xd0, 0x8c, 0x9a, 0xd9, 0xba, 0xee,
	0x26, 0xad, 0x7b, 0xde, 0xa4, 0x7d, 0xe7, 0x4d, 0xe6, 0xcb, 0x37, 0xf9, 0x43, 0x13, 0x88, 0xf3,
	0x16, 0x43, 0x36, 0xfa, 0xc0, 0xc6, 0x9c, 0xbc, 0x81, 0xcd, 0x9a, 0xd7, 0xc8, 0x06, 0x9f, 0x87,
	0x3a, 0xf8, 0xab, 0x0c, 0xb4, 0x7e, 0x17, 0xf9, 0x0a, 0x56, 0x0b, 0xe6, 0xe2, 0xe9, 0xd7, 0x86,
	0x75, 0x14, 0x54, 0x20, 0xd1, 0x32, 0x67, 0xc5, 0x25, 0xe7, 0xee, 0xeb, 0x92, 0x36, 0xb0, 0x12,
	0x55, 0x0a, 0x2c, 0x03, 0x10, 0x0f, 0x16, 0x5e, 0xc6, 0x81, 0x13, 0x50, 0xe9, 0xf2, 0x7c, 0x5e,
	0xff, 0x87, 0xf3, 0xf9, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xf4, 0x16, 0x48, 0xd3, 0x19,
	0x00, 0x00,
}
