// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role int32

const (
	Role_ATTESTER Role = 0
	Role_PROPOSER Role = 1
)

var Role_name = map[int32]string{
	0: "ATTESTER",
	1: "PROPOSER",
}

var Role_value = map[string]int32{
	"ATTESTER": 0,
	"PROPOSER": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetSlotAndShardAssignmentRequest struct {
	ValidatorID          uint32   `protobuf:"varint,1,opt,name=ValidatorID,proto3" json:"ValidatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotAndShardAssignmentRequest) Reset()         { *m = GetSlotAndShardAssignmentRequest{} }
func (m *GetSlotAndShardAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetSlotAndShardAssignmentRequest) ProtoMessage()    {}
func (*GetSlotAndShardAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *GetSlotAndShardAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Unmarshal(m, b)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Marshal(b, m, deterministic)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotAndShardAssignmentRequest.Merge(m, src)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Size(m)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotAndShardAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotAndShardAssignmentRequest proto.InternalMessageInfo

func (m *GetSlotAndShardAssignmentRequest) GetValidatorID() uint32 {
	if m != nil {
		return m.ValidatorID
	}
	return 0
}

type SlotAndShardAssignment struct {
	ShardID              uint32   `protobuf:"varint,1,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	Slot                 uint64   `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Role                 Role     `protobuf:"varint,3,opt,name=Role,proto3,enum=pb.Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotAndShardAssignment) Reset()         { *m = SlotAndShardAssignment{} }
func (m *SlotAndShardAssignment) String() string { return proto.CompactTextString(m) }
func (*SlotAndShardAssignment) ProtoMessage()    {}
func (*SlotAndShardAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *SlotAndShardAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotAndShardAssignment.Unmarshal(m, b)
}
func (m *SlotAndShardAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotAndShardAssignment.Marshal(b, m, deterministic)
}
func (m *SlotAndShardAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotAndShardAssignment.Merge(m, src)
}
func (m *SlotAndShardAssignment) XXX_Size() int {
	return xxx_messageInfo_SlotAndShardAssignment.Size(m)
}
func (m *SlotAndShardAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotAndShardAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_SlotAndShardAssignment proto.InternalMessageInfo

func (m *SlotAndShardAssignment) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *SlotAndShardAssignment) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *SlotAndShardAssignment) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ATTESTER
}

type SubmitBlockRequest struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitBlockRequest) Reset()         { *m = SubmitBlockRequest{} }
func (m *SubmitBlockRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockRequest) ProtoMessage()    {}
func (*SubmitBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *SubmitBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitBlockRequest.Unmarshal(m, b)
}
func (m *SubmitBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitBlockRequest.Marshal(b, m, deterministic)
}
func (m *SubmitBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockRequest.Merge(m, src)
}
func (m *SubmitBlockRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitBlockRequest.Size(m)
}
func (m *SubmitBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockRequest proto.InternalMessageInfo

func (m *SubmitBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubmitBlockResponse struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitBlockResponse) Reset()         { *m = SubmitBlockResponse{} }
func (m *SubmitBlockResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockResponse) ProtoMessage()    {}
func (*SubmitBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *SubmitBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitBlockResponse.Unmarshal(m, b)
}
func (m *SubmitBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitBlockResponse.Marshal(b, m, deterministic)
}
func (m *SubmitBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockResponse.Merge(m, src)
}
func (m *SubmitBlockResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitBlockResponse.Size(m)
}
func (m *SubmitBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockResponse proto.InternalMessageInfo

func (m *SubmitBlockResponse) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type SlotNumberResponse struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotNumberResponse) Reset()         { *m = SlotNumberResponse{} }
func (m *SlotNumberResponse) String() string { return proto.CompactTextString(m) }
func (*SlotNumberResponse) ProtoMessage()    {}
func (*SlotNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *SlotNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotNumberResponse.Unmarshal(m, b)
}
func (m *SlotNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotNumberResponse.Marshal(b, m, deterministic)
}
func (m *SlotNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotNumberResponse.Merge(m, src)
}
func (m *SlotNumberResponse) XXX_Size() int {
	return xxx_messageInfo_SlotNumberResponse.Size(m)
}
func (m *SlotNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlotNumberResponse proto.InternalMessageInfo

func (m *SlotNumberResponse) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type GetBlockHashRequest struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashRequest) Reset()         { *m = GetBlockHashRequest{} }
func (m *GetBlockHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashRequest) ProtoMessage()    {}
func (*GetBlockHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *GetBlockHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashRequest.Unmarshal(m, b)
}
func (m *GetBlockHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashRequest.Merge(m, src)
}
func (m *GetBlockHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashRequest.Size(m)
}
func (m *GetBlockHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashRequest proto.InternalMessageInfo

func (m *GetBlockHashRequest) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type GetBlockHashResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashResponse) Reset()         { *m = GetBlockHashResponse{} }
func (m *GetBlockHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashResponse) ProtoMessage()    {}
func (*GetBlockHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *GetBlockHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashResponse.Unmarshal(m, b)
}
func (m *GetBlockHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashResponse.Merge(m, src)
}
func (m *GetBlockHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashResponse.Size(m)
}
func (m *GetBlockHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashResponse proto.InternalMessageInfo

func (m *GetBlockHashResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GetValidatorAtIndexRequest struct {
	Index                uint32   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorAtIndexRequest) Reset()         { *m = GetValidatorAtIndexRequest{} }
func (m *GetValidatorAtIndexRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorAtIndexRequest) ProtoMessage()    {}
func (*GetValidatorAtIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *GetValidatorAtIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Unmarshal(m, b)
}
func (m *GetValidatorAtIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorAtIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorAtIndexRequest.Merge(m, src)
}
func (m *GetValidatorAtIndexRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Size(m)
}
func (m *GetValidatorAtIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorAtIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorAtIndexRequest proto.InternalMessageInfo

func (m *GetValidatorAtIndexRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type GetValidatorAtIndexResponse struct {
	PublicKey            uint32   `protobuf:"varint,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorAtIndexResponse) Reset()         { *m = GetValidatorAtIndexResponse{} }
func (m *GetValidatorAtIndexResponse) String() string { return proto.CompactTextString(m) }
func (*GetValidatorAtIndexResponse) ProtoMessage()    {}
func (*GetValidatorAtIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *GetValidatorAtIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Unmarshal(m, b)
}
func (m *GetValidatorAtIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Marshal(b, m, deterministic)
}
func (m *GetValidatorAtIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorAtIndexResponse.Merge(m, src)
}
func (m *GetValidatorAtIndexResponse) XXX_Size() int {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Size(m)
}
func (m *GetValidatorAtIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorAtIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorAtIndexResponse proto.InternalMessageInfo

func (m *GetValidatorAtIndexResponse) GetPublicKey() uint32 {
	if m != nil {
		return m.PublicKey
	}
	return 0
}

func (m *GetValidatorAtIndexResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetCommitteeValidatorsRequest struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	Shard                uint32   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommitteeValidatorsRequest) Reset()         { *m = GetCommitteeValidatorsRequest{} }
func (m *GetCommitteeValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorsRequest) ProtoMessage()    {}
func (*GetCommitteeValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *GetCommitteeValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Marshal(b, m, deterministic)
}
func (m *GetCommitteeValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorsRequest.Merge(m, src)
}
func (m *GetCommitteeValidatorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Size(m)
}
func (m *GetCommitteeValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorsRequest proto.InternalMessageInfo

func (m *GetCommitteeValidatorsRequest) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *GetCommitteeValidatorsRequest) GetShard() uint32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

type GetCommitteeValidatorsResponse struct {
	Validators           []*GetValidatorAtIndexResponse `protobuf:"bytes,1,rep,name=Validators,proto3" json:"Validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetCommitteeValidatorsResponse) Reset()         { *m = GetCommitteeValidatorsResponse{} }
func (m *GetCommitteeValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorsResponse) ProtoMessage()    {}
func (*GetCommitteeValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *GetCommitteeValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Marshal(b, m, deterministic)
}
func (m *GetCommitteeValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorsResponse.Merge(m, src)
}
func (m *GetCommitteeValidatorsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Size(m)
}
func (m *GetCommitteeValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorsResponse proto.InternalMessageInfo

func (m *GetCommitteeValidatorsResponse) GetValidators() []*GetValidatorAtIndexResponse {
	if m != nil {
		return m.Validators
	}
	return nil
}

type Block struct {
	SlotNumber            uint64         `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	RandaoReveal          []byte         `protobuf:"bytes,2,opt,name=RandaoReveal,proto3" json:"RandaoReveal,omitempty"`
	AncestorHashes        [][]byte       `protobuf:"bytes,3,rep,name=AncestorHashes,proto3" json:"AncestorHashes,omitempty"`
	ActiveStateRoot       []byte         `protobuf:"bytes,4,opt,name=ActiveStateRoot,proto3" json:"ActiveStateRoot,omitempty"`
	CrystallizedStateRoot []byte         `protobuf:"bytes,5,opt,name=CrystallizedStateRoot,proto3" json:"CrystallizedStateRoot,omitempty"`
	Attestations          []*Attestation `protobuf:"bytes,6,rep,name=Attestations,proto3" json:"Attestations,omitempty"`
	Specials              []*Special     `protobuf:"bytes,7,rep,name=Specials,proto3" json:"Specials,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *Block) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *Block) GetAncestorHashes() [][]byte {
	if m != nil {
		return m.AncestorHashes
	}
	return nil
}

func (m *Block) GetActiveStateRoot() []byte {
	if m != nil {
		return m.ActiveStateRoot
	}
	return nil
}

func (m *Block) GetCrystallizedStateRoot() []byte {
	if m != nil {
		return m.CrystallizedStateRoot
	}
	return nil
}

func (m *Block) GetAttestations() []*Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func (m *Block) GetSpecials() []*Special {
	if m != nil {
		return m.Specials
	}
	return nil
}

type Special struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Data                 [][]byte `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Special) Reset()         { *m = Special{} }
func (m *Special) String() string { return proto.CompactTextString(m) }
func (*Special) ProtoMessage()    {}
func (*Special) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *Special) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Special.Unmarshal(m, b)
}
func (m *Special) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Special.Marshal(b, m, deterministic)
}
func (m *Special) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Special.Merge(m, src)
}
func (m *Special) XXX_Size() int {
	return xxx_messageInfo_Special.Size(m)
}
func (m *Special) XXX_DiscardUnknown() {
	xxx_messageInfo_Special.DiscardUnknown(m)
}

var xxx_messageInfo_Special proto.InternalMessageInfo

func (m *Special) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Special) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Attestation struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	ShardID              uint32   `protobuf:"varint,2,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	JustifiedSlot        uint64   `protobuf:"varint,3,opt,name=JustifiedSlot,proto3" json:"JustifiedSlot,omitempty"`
	JustifiedBlockHash   []byte   `protobuf:"bytes,4,opt,name=JustifiedBlockHash,proto3" json:"JustifiedBlockHash,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,5,opt,name=ShardBlockHash,proto3" json:"ShardBlockHash,omitempty"`
	ObliqueParentHashes  [][]byte `protobuf:"bytes,6,rep,name=ObliqueParentHashes,proto3" json:"ObliqueParentHashes,omitempty"`
	AttesterBitField     []byte   `protobuf:"bytes,7,opt,name=AttesterBitField,proto3" json:"AttesterBitField,omitempty"`
	AggregateSignature   []byte   `protobuf:"bytes,8,opt,name=AggregateSignature,proto3" json:"AggregateSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Attestation) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Attestation) GetJustifiedSlot() uint64 {
	if m != nil {
		return m.JustifiedSlot
	}
	return 0
}

func (m *Attestation) GetJustifiedBlockHash() []byte {
	if m != nil {
		return m.JustifiedBlockHash
	}
	return nil
}

func (m *Attestation) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *Attestation) GetObliqueParentHashes() [][]byte {
	if m != nil {
		return m.ObliqueParentHashes
	}
	return nil
}

func (m *Attestation) GetAttesterBitField() []byte {
	if m != nil {
		return m.AttesterBitField
	}
	return nil
}

func (m *Attestation) GetAggregateSignature() []byte {
	if m != nil {
		return m.AggregateSignature
	}
	return nil
}

type AttestationSignedData struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Slot                 uint64   `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Shard                uint32   `protobuf:"varint,3,opt,name=Shard,proto3" json:"Shard,omitempty"`
	ParentHashes         [][]byte `protobuf:"bytes,4,rep,name=ParentHashes,proto3" json:"ParentHashes,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,5,opt,name=ShardBlockHash,proto3" json:"ShardBlockHash,omitempty"`
	JustifiedSlot        uint64   `protobuf:"varint,6,opt,name=JustifiedSlot,proto3" json:"JustifiedSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationSignedData) Reset()         { *m = AttestationSignedData{} }
func (m *AttestationSignedData) String() string { return proto.CompactTextString(m) }
func (*AttestationSignedData) ProtoMessage()    {}
func (*AttestationSignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *AttestationSignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationSignedData.Unmarshal(m, b)
}
func (m *AttestationSignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationSignedData.Marshal(b, m, deterministic)
}
func (m *AttestationSignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationSignedData.Merge(m, src)
}
func (m *AttestationSignedData) XXX_Size() int {
	return xxx_messageInfo_AttestationSignedData.Size(m)
}
func (m *AttestationSignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationSignedData.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationSignedData proto.InternalMessageInfo

func (m *AttestationSignedData) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AttestationSignedData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationSignedData) GetShard() uint32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *AttestationSignedData) GetParentHashes() [][]byte {
	if m != nil {
		return m.ParentHashes
	}
	return nil
}

func (m *AttestationSignedData) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *AttestationSignedData) GetJustifiedSlot() uint64 {
	if m != nil {
		return m.JustifiedSlot
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Role", Role_name, Role_value)
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*GetSlotAndShardAssignmentRequest)(nil), "pb.GetSlotAndShardAssignmentRequest")
	proto.RegisterType((*SlotAndShardAssignment)(nil), "pb.SlotAndShardAssignment")
	proto.RegisterType((*SubmitBlockRequest)(nil), "pb.SubmitBlockRequest")
	proto.RegisterType((*SubmitBlockResponse)(nil), "pb.SubmitBlockResponse")
	proto.RegisterType((*SlotNumberResponse)(nil), "pb.SlotNumberResponse")
	proto.RegisterType((*GetBlockHashRequest)(nil), "pb.GetBlockHashRequest")
	proto.RegisterType((*GetBlockHashResponse)(nil), "pb.GetBlockHashResponse")
	proto.RegisterType((*GetValidatorAtIndexRequest)(nil), "pb.GetValidatorAtIndexRequest")
	proto.RegisterType((*GetValidatorAtIndexResponse)(nil), "pb.GetValidatorAtIndexResponse")
	proto.RegisterType((*GetCommitteeValidatorsRequest)(nil), "pb.GetCommitteeValidatorsRequest")
	proto.RegisterType((*GetCommitteeValidatorsResponse)(nil), "pb.GetCommitteeValidatorsResponse")
	proto.RegisterType((*Block)(nil), "pb.Block")
	proto.RegisterType((*Special)(nil), "pb.Special")
	proto.RegisterType((*Attestation)(nil), "pb.Attestation")
	proto.RegisterType((*AttestationSignedData)(nil), "pb.AttestationSignedData")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 847 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xc6, 0x3f, 0xb1, 0x93, 0x63, 0xbb, 0xcd, 0x6c, 0xda, 0x54, 0x98, 0x92, 0x9a, 0x9d, 0x0e,
	0x78, 0x72, 0x91, 0x01, 0xa7, 0xbd, 0x85, 0x51, 0x93, 0x10, 0x0a, 0x33, 0xc4, 0xb3, 0x0a, 0xb9,
	0x63, 0x98, 0xb5, 0x75, 0x70, 0x76, 0x90, 0x25, 0x57, 0xbb, 0xee, 0x10, 0xde, 0x8a, 0xa7, 0xe0,
	0x8a, 0x57, 0xe0, 0x59, 0x98, 0x3d, 0x5a, 0xcb, 0xb2, 0x2d, 0x27, 0xb9, 0xd3, 0xf9, 0x76, 0xbf,
	0xb3, 0xe7, 0x67, 0xf7, 0x3b, 0x82, 0xbd, 0x74, 0x36, 0x3e, 0x99, 0xa5, 0x89, 0x49, 0x58, 0x75,
	0x36, 0xe2, 0x4d, 0xd8, 0xb9, 0x98, 0xce, 0xcc, 0x1d, 0x3f, 0x87, 0xde, 0x25, 0x9a, 0x20, 0x4a,
	0x8c, 0x1f, 0x87, 0xc1, 0xad, 0x4c, 0x43, 0x5f, 0x6b, 0x35, 0x89, 0xa7, 0x18, 0x1b, 0x81, 0x1f,
	0xe6, 0xa8, 0x0d, 0xeb, 0x41, 0xeb, 0x46, 0x46, 0x2a, 0x94, 0x26, 0x49, 0xdf, 0x9f, 0x7b, 0x95,
	0x5e, 0xa5, 0xdf, 0x11, 0x45, 0x88, 0x87, 0x70, 0x58, 0xee, 0x82, 0x79, 0xd0, 0x24, 0x28, 0xe7,
	0x2d, 0x4c, 0xc6, 0xa0, 0x6e, 0x39, 0x5e, 0xb5, 0x57, 0xe9, 0xd7, 0x05, 0x7d, 0xb3, 0x97, 0x50,
	0x17, 0x49, 0x84, 0x5e, 0xad, 0x57, 0xe9, 0x3f, 0x19, 0xec, 0x9e, 0xcc, 0x46, 0x27, 0xd6, 0x16,
	0x84, 0xf2, 0xb7, 0xc0, 0x82, 0xf9, 0x68, 0xaa, 0xcc, 0xbb, 0x28, 0x19, 0xff, 0xb1, 0x88, 0xee,
	0x15, 0xec, 0x90, 0x4d, 0xfe, 0x5b, 0x83, 0x3d, 0x4b, 0xca, 0x36, 0x64, 0x38, 0x3f, 0x85, 0x83,
	0x15, 0x9a, 0x9e, 0x25, 0xb1, 0x46, 0xf6, 0x12, 0xf6, 0x08, 0xf8, 0x41, 0xea, 0x5b, 0xe2, 0xb6,
	0xc5, 0x12, 0xe0, 0x6f, 0x80, 0xd9, 0x88, 0x7e, 0x9e, 0x4f, 0x47, 0x98, 0xe6, 0x9c, 0x23, 0x80,
	0x25, 0x4a, 0xa4, 0xba, 0x28, 0x20, 0xfc, 0x2d, 0x1c, 0x5c, 0xa2, 0xc9, 0xbd, 0x2c, 0x42, 0x7c,
	0x88, 0x76, 0x0c, 0xcf, 0x56, 0x69, 0xee, 0x38, 0x06, 0xf5, 0x42, 0x74, 0xf4, 0xcd, 0x07, 0xd0,
	0xbd, 0x44, 0x93, 0x17, 0xdf, 0x37, 0xef, 0xe3, 0x10, 0xff, 0x5c, 0x9c, 0xf4, 0x0c, 0x76, 0xc8,
	0x76, 0xc5, 0xce, 0x0c, 0x1e, 0xc0, 0x67, 0xa5, 0x9c, 0x65, 0x25, 0x86, 0xf3, 0x51, 0xa4, 0xc6,
	0x3f, 0xe1, 0x9d, 0x23, 0x2e, 0x01, 0x76, 0x08, 0x8d, 0xc0, 0x48, 0x33, 0xd7, 0xd4, 0xa9, 0x8e,
	0x70, 0x16, 0xff, 0x05, 0x3e, 0xbf, 0x44, 0x73, 0x96, 0x4c, 0xa7, 0xca, 0x18, 0xc4, 0xdc, 0xbb,
	0x7e, 0x64, 0xd6, 0x36, 0x56, 0xba, 0x0b, 0xce, 0x6f, 0x66, 0x70, 0x09, 0x47, 0xdb, 0xdc, 0xba,
	0x70, 0xbf, 0x03, 0x58, 0xa2, 0x5e, 0xa5, 0x57, 0xeb, 0xb7, 0x06, 0xaf, 0x6c, 0xd7, 0xef, 0xc9,
	0x51, 0x14, 0x28, 0xfc, 0xef, 0xaa, 0xbb, 0x32, 0x0f, 0x86, 0xc8, 0xa1, 0x2d, 0x64, 0x1c, 0xca,
	0x44, 0xe0, 0x47, 0x94, 0x11, 0x45, 0xda, 0x16, 0x2b, 0x18, 0xfb, 0x12, 0x9e, 0xf8, 0xf1, 0x18,
	0xb5, 0x49, 0x52, 0xdb, 0x20, 0xd4, 0x5e, 0xad, 0x57, 0xeb, 0xb7, 0xc5, 0x1a, 0xca, 0xfa, 0xf0,
	0xd4, 0x1f, 0x1b, 0xf5, 0x11, 0x6d, 0xfd, 0x50, 0x24, 0x89, 0xf1, 0xea, 0xe4, 0x6e, 0x1d, 0x66,
	0x6f, 0xe0, 0xf9, 0x59, 0x7a, 0xa7, 0x8d, 0x8c, 0x22, 0xf5, 0x17, 0x86, 0xcb, 0xfd, 0x3b, 0xb4,
	0xbf, 0x7c, 0x91, 0x9d, 0x42, 0xdb, 0x37, 0x06, 0xb5, 0x91, 0x46, 0x25, 0xb1, 0xf6, 0x1a, 0x54,
	0x98, 0xa7, 0xb6, 0x30, 0x05, 0x5c, 0xac, 0x6c, 0x62, 0x5f, 0xc1, 0x6e, 0x30, 0xc3, 0xb1, 0x92,
	0x91, 0xf6, 0x9a, 0x44, 0x68, 0x59, 0x82, 0xc3, 0x44, 0xbe, 0xc8, 0xbf, 0x81, 0xa6, 0xfb, 0xb6,
	0xb7, 0xf2, 0xfa, 0x6e, 0x86, 0xee, 0xa6, 0xd0, 0xb7, 0xc5, 0xce, 0xa5, 0x91, 0x5e, 0x95, 0x52,
	0xa7, 0x6f, 0xfe, 0x4f, 0x15, 0x5a, 0x85, 0xc3, 0xf2, 0x07, 0x5f, 0x29, 0x3c, 0xf8, 0x82, 0x3c,
	0x54, 0x57, 0xe5, 0xe1, 0x35, 0x74, 0x7e, 0x9c, 0x6b, 0xa3, 0x7e, 0x57, 0x18, 0x12, 0xad, 0x46,
	0xb4, 0x55, 0x90, 0x9d, 0x00, 0xcb, 0x81, 0xe5, 0x6b, 0xce, 0xea, 0x5a, 0xb2, 0x62, 0x9b, 0x45,
	0x07, 0x2c, 0xf7, 0x66, 0x35, 0x5d, 0x43, 0xd9, 0xd7, 0x70, 0x70, 0x35, 0x8a, 0xd4, 0x87, 0x39,
	0x0e, 0x65, 0x8a, 0xb1, 0x71, 0x9d, 0x6d, 0x50, 0x7a, 0x65, 0x4b, 0xec, 0x18, 0xf6, 0xb3, 0x64,
	0x31, 0x7d, 0xa7, 0xcc, 0xf7, 0x0a, 0xa3, 0xd0, 0x6b, 0x92, 0xef, 0x0d, 0xdc, 0x46, 0xed, 0x4f,
	0x26, 0x29, 0x4e, 0xa4, 0xc1, 0x40, 0x4d, 0x62, 0x69, 0xe6, 0x29, 0x7a, 0xbb, 0x59, 0xd4, 0x9b,
	0x2b, 0xfc, 0xdf, 0x0a, 0x3c, 0x2f, 0x54, 0xd2, 0x2e, 0x60, 0x68, 0x6b, 0x6c, 0xeb, 0x77, 0x83,
	0xa9, 0x56, 0x49, 0xbc, 0x90, 0x57, 0x67, 0x96, 0xca, 0x6b, 0xfe, 0xe2, 0x6a, 0x85, 0x17, 0x67,
	0x2f, 0xf9, 0x4a, 0x92, 0x75, 0x4a, 0x72, 0x05, 0x7b, 0x74, 0xdd, 0x36, 0xba, 0xd6, 0x28, 0xe9,
	0xda, 0x31, 0xcf, 0x64, 0x9e, 0xb5, 0x61, 0xd7, 0xbf, 0xbe, 0xbe, 0x08, 0xae, 0x2f, 0xc4, 0xfe,
	0x27, 0xd6, 0x1a, 0x8a, 0xab, 0xe1, 0x55, 0x70, 0x21, 0xf6, 0x2b, 0x83, 0xff, 0x6a, 0xd0, 0x21,
	0xbf, 0xe3, 0x5b, 0xa9, 0x62, 0x31, 0x3c, 0x63, 0xdf, 0x42, 0xab, 0xa0, 0xe3, 0xec, 0x90, 0x2e,
	0xea, 0xc6, 0x3c, 0xe8, 0xbe, 0xd8, 0xc0, 0x9d, 0x6e, 0x0c, 0xa0, 0xe3, 0x46, 0x9d, 0x7b, 0xdd,
	0x34, 0x2a, 0x68, 0x0c, 0x76, 0x33, 0x67, 0x9b, 0x82, 0xef, 0x43, 0xbb, 0xa8, 0xcc, 0xec, 0x85,
	0xd3, 0x99, 0x75, 0x89, 0xef, 0x7a, 0x9b, 0x0b, 0xce, 0xc5, 0xaf, 0xf0, 0xe9, 0xd6, 0x09, 0xcb,
	0x5e, 0x3b, 0xda, 0xbd, 0x03, 0xb8, 0xdb, 0x5d, 0x44, 0x57, 0xe2, 0xe1, 0x86, 0x46, 0xce, 0xba,
	0xee, 0xb1, 0xa3, 0xad, 0x82, 0x98, 0xb9, 0x7c, 0x48, 0x30, 0xd9, 0x6f, 0x70, 0x58, 0xae, 0xc3,
	0xec, 0x0b, 0x47, 0xdd, 0x2e, 0xfd, 0x5d, 0x7e, 0xdf, 0x96, 0xec, 0x80, 0x51, 0x83, 0xfe, 0x46,
	0x4e, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x0a, 0x83, 0x68, 0x9a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainRPCClient is the client API for BlockchainRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainRPCClient interface {
	SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
	GetSlotNumber(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SlotNumberResponse, error)
	GetBlockHash(ctx context.Context, in *GetBlockHashRequest, opts ...grpc.CallOption) (*GetBlockHashResponse, error)
	GetSlotAndShardAssignment(ctx context.Context, in *GetSlotAndShardAssignmentRequest, opts ...grpc.CallOption) (*SlotAndShardAssignment, error)
	GetValidatorAtIndex(ctx context.Context, in *GetValidatorAtIndexRequest, opts ...grpc.CallOption) (*GetValidatorAtIndexResponse, error)
	GetCommitteeValidators(ctx context.Context, in *GetCommitteeValidatorsRequest, opts ...grpc.CallOption) (*GetCommitteeValidatorsResponse, error)
}

type blockchainRPCClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainRPCClient(cc *grpc.ClientConn) BlockchainRPCClient {
	return &blockchainRPCClient{cc}
}

func (c *blockchainRPCClient) SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/SubmitBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetSlotNumber(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SlotNumberResponse, error) {
	out := new(SlotNumberResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetSlotNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetBlockHash(ctx context.Context, in *GetBlockHashRequest, opts ...grpc.CallOption) (*GetBlockHashResponse, error) {
	out := new(GetBlockHashResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetSlotAndShardAssignment(ctx context.Context, in *GetSlotAndShardAssignmentRequest, opts ...grpc.CallOption) (*SlotAndShardAssignment, error) {
	out := new(SlotAndShardAssignment)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetSlotAndShardAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetValidatorAtIndex(ctx context.Context, in *GetValidatorAtIndexRequest, opts ...grpc.CallOption) (*GetValidatorAtIndexResponse, error) {
	out := new(GetValidatorAtIndexResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetValidatorAtIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetCommitteeValidators(ctx context.Context, in *GetCommitteeValidatorsRequest, opts ...grpc.CallOption) (*GetCommitteeValidatorsResponse, error) {
	out := new(GetCommitteeValidatorsResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetCommitteeValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainRPCServer is the server API for BlockchainRPC service.
type BlockchainRPCServer interface {
	SubmitBlock(context.Context, *SubmitBlockRequest) (*SubmitBlockResponse, error)
	GetSlotNumber(context.Context, *Empty) (*SlotNumberResponse, error)
	GetBlockHash(context.Context, *GetBlockHashRequest) (*GetBlockHashResponse, error)
	GetSlotAndShardAssignment(context.Context, *GetSlotAndShardAssignmentRequest) (*SlotAndShardAssignment, error)
	GetValidatorAtIndex(context.Context, *GetValidatorAtIndexRequest) (*GetValidatorAtIndexResponse, error)
	GetCommitteeValidators(context.Context, *GetCommitteeValidatorsRequest) (*GetCommitteeValidatorsResponse, error)
}

func RegisterBlockchainRPCServer(s *grpc.Server, srv BlockchainRPCServer) {
	s.RegisterService(&_BlockchainRPC_serviceDesc, srv)
}

func _BlockchainRPC_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/SubmitBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).SubmitBlock(ctx, req.(*SubmitBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetSlotNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetSlotNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetSlotNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetSlotNumber(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetBlockHash(ctx, req.(*GetBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetSlotAndShardAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotAndShardAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetSlotAndShardAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetSlotAndShardAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetSlotAndShardAssignment(ctx, req.(*GetSlotAndShardAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetValidatorAtIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorAtIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetValidatorAtIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetValidatorAtIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetValidatorAtIndex(ctx, req.(*GetValidatorAtIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetCommitteeValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitteeValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetCommitteeValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetCommitteeValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetCommitteeValidators(ctx, req.(*GetCommitteeValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockchainRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlockchainRPC",
	HandlerType: (*BlockchainRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBlock",
			Handler:    _BlockchainRPC_SubmitBlock_Handler,
		},
		{
			MethodName: "GetSlotNumber",
			Handler:    _BlockchainRPC_GetSlotNumber_Handler,
		},
		{
			MethodName: "GetBlockHash",
			Handler:    _BlockchainRPC_GetBlockHash_Handler,
		},
		{
			MethodName: "GetSlotAndShardAssignment",
			Handler:    _BlockchainRPC_GetSlotAndShardAssignment_Handler,
		},
		{
			MethodName: "GetValidatorAtIndex",
			Handler:    _BlockchainRPC_GetValidatorAtIndex_Handler,
		},
		{
			MethodName: "GetCommitteeValidators",
			Handler:    _BlockchainRPC_GetCommitteeValidators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
