// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role int32

const (
	Role_ATTESTER Role = 0
	Role_PROPOSER Role = 1
)

var Role_name = map[int32]string{
	0: "ATTESTER",
	1: "PROPOSER",
}

var Role_value = map[string]int32{
	"ATTESTER": 0,
	"PROPOSER": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type ConnectionStatus struct {
	Connected            bool     `protobuf:"varint,1,opt,name=Connected,proto3" json:"Connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionStatus) Reset()         { *m = ConnectionStatus{} }
func (m *ConnectionStatus) String() string { return proto.CompactTextString(m) }
func (*ConnectionStatus) ProtoMessage()    {}
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *ConnectionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionStatus.Unmarshal(m, b)
}
func (m *ConnectionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionStatus.Marshal(b, m, deterministic)
}
func (m *ConnectionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionStatus.Merge(m, src)
}
func (m *ConnectionStatus) XXX_Size() int {
	return xxx_messageInfo_ConnectionStatus.Size(m)
}
func (m *ConnectionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionStatus proto.InternalMessageInfo

func (m *ConnectionStatus) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

type Peer struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SubscriptionRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionRequest) Reset()         { *m = SubscriptionRequest{} }
func (m *SubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*SubscriptionRequest) ProtoMessage()    {}
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *SubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionRequest.Unmarshal(m, b)
}
func (m *SubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *SubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionRequest.Merge(m, src)
}
func (m *SubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_SubscriptionRequest.Size(m)
}
func (m *SubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionRequest proto.InternalMessageInfo

func (m *SubscriptionRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Subscription struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetPeersResponse struct {
	Peers                []*Peer  `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeersResponse) Reset()         { *m = GetPeersResponse{} }
func (m *GetPeersResponse) String() string { return proto.CompactTextString(m) }
func (*GetPeersResponse) ProtoMessage()    {}
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *GetPeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeersResponse.Unmarshal(m, b)
}
func (m *GetPeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeersResponse.Marshal(b, m, deterministic)
}
func (m *GetPeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeersResponse.Merge(m, src)
}
func (m *GetPeersResponse) XXX_Size() int {
	return xxx_messageInfo_GetPeersResponse.Size(m)
}
func (m *GetPeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeersResponse proto.InternalMessageInfo

func (m *GetPeersResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Message struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MessageAndTopic struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageAndTopic) Reset()         { *m = MessageAndTopic{} }
func (m *MessageAndTopic) String() string { return proto.CompactTextString(m) }
func (*MessageAndTopic) ProtoMessage()    {}
func (*MessageAndTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *MessageAndTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageAndTopic.Unmarshal(m, b)
}
func (m *MessageAndTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageAndTopic.Marshal(b, m, deterministic)
}
func (m *MessageAndTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageAndTopic.Merge(m, src)
}
func (m *MessageAndTopic) XXX_Size() int {
	return xxx_messageInfo_MessageAndTopic.Size(m)
}
func (m *MessageAndTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageAndTopic.DiscardUnknown(m)
}

var xxx_messageInfo_MessageAndTopic proto.InternalMessageInfo

func (m *MessageAndTopic) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessageAndTopic) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Peers struct {
	Peers                []*Peer  `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peers) Reset()         { *m = Peers{} }
func (m *Peers) String() string { return proto.CompactTextString(m) }
func (*Peers) ProtoMessage()    {}
func (*Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peers.Unmarshal(m, b)
}
func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peers.Marshal(b, m, deterministic)
}
func (m *Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peers.Merge(m, src)
}
func (m *Peers) XXX_Size() int {
	return xxx_messageInfo_Peers.Size(m)
}
func (m *Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type ConnectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DisconnectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type P2PSettings struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PSettings) Reset()         { *m = P2PSettings{} }
func (m *P2PSettings) String() string { return proto.CompactTextString(m) }
func (*P2PSettings) ProtoMessage()    {}
func (*P2PSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *P2PSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PSettings.Unmarshal(m, b)
}
func (m *P2PSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PSettings.Marshal(b, m, deterministic)
}
func (m *P2PSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PSettings.Merge(m, src)
}
func (m *P2PSettings) XXX_Size() int {
	return xxx_messageInfo_P2PSettings.Size(m)
}
func (m *P2PSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PSettings.DiscardUnknown(m)
}

var xxx_messageInfo_P2PSettings proto.InternalMessageInfo

type GetSlotAndShardAssignmentRequest struct {
	ValidatorID          uint32   `protobuf:"varint,1,opt,name=ValidatorID,proto3" json:"ValidatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotAndShardAssignmentRequest) Reset()         { *m = GetSlotAndShardAssignmentRequest{} }
func (m *GetSlotAndShardAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetSlotAndShardAssignmentRequest) ProtoMessage()    {}
func (*GetSlotAndShardAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *GetSlotAndShardAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Unmarshal(m, b)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Marshal(b, m, deterministic)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotAndShardAssignmentRequest.Merge(m, src)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetSlotAndShardAssignmentRequest.Size(m)
}
func (m *GetSlotAndShardAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotAndShardAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotAndShardAssignmentRequest proto.InternalMessageInfo

func (m *GetSlotAndShardAssignmentRequest) GetValidatorID() uint32 {
	if m != nil {
		return m.ValidatorID
	}
	return 0
}

type SlotAndShardAssignment struct {
	ShardID              uint32   `protobuf:"varint,1,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	Slot                 uint64   `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Role                 Role     `protobuf:"varint,3,opt,name=Role,proto3,enum=pb.Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotAndShardAssignment) Reset()         { *m = SlotAndShardAssignment{} }
func (m *SlotAndShardAssignment) String() string { return proto.CompactTextString(m) }
func (*SlotAndShardAssignment) ProtoMessage()    {}
func (*SlotAndShardAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *SlotAndShardAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotAndShardAssignment.Unmarshal(m, b)
}
func (m *SlotAndShardAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotAndShardAssignment.Marshal(b, m, deterministic)
}
func (m *SlotAndShardAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotAndShardAssignment.Merge(m, src)
}
func (m *SlotAndShardAssignment) XXX_Size() int {
	return xxx_messageInfo_SlotAndShardAssignment.Size(m)
}
func (m *SlotAndShardAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotAndShardAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_SlotAndShardAssignment proto.InternalMessageInfo

func (m *SlotAndShardAssignment) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *SlotAndShardAssignment) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *SlotAndShardAssignment) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ATTESTER
}

type SubmitBlockRequest struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitBlockRequest) Reset()         { *m = SubmitBlockRequest{} }
func (m *SubmitBlockRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockRequest) ProtoMessage()    {}
func (*SubmitBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *SubmitBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitBlockRequest.Unmarshal(m, b)
}
func (m *SubmitBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitBlockRequest.Marshal(b, m, deterministic)
}
func (m *SubmitBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockRequest.Merge(m, src)
}
func (m *SubmitBlockRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitBlockRequest.Size(m)
}
func (m *SubmitBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockRequest proto.InternalMessageInfo

func (m *SubmitBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubmitBlockResponse struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitBlockResponse) Reset()         { *m = SubmitBlockResponse{} }
func (m *SubmitBlockResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitBlockResponse) ProtoMessage()    {}
func (*SubmitBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *SubmitBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitBlockResponse.Unmarshal(m, b)
}
func (m *SubmitBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitBlockResponse.Marshal(b, m, deterministic)
}
func (m *SubmitBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitBlockResponse.Merge(m, src)
}
func (m *SubmitBlockResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitBlockResponse.Size(m)
}
func (m *SubmitBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitBlockResponse proto.InternalMessageInfo

func (m *SubmitBlockResponse) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type SlotNumberResponse struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotNumberResponse) Reset()         { *m = SlotNumberResponse{} }
func (m *SlotNumberResponse) String() string { return proto.CompactTextString(m) }
func (*SlotNumberResponse) ProtoMessage()    {}
func (*SlotNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *SlotNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotNumberResponse.Unmarshal(m, b)
}
func (m *SlotNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotNumberResponse.Marshal(b, m, deterministic)
}
func (m *SlotNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotNumberResponse.Merge(m, src)
}
func (m *SlotNumberResponse) XXX_Size() int {
	return xxx_messageInfo_SlotNumberResponse.Size(m)
}
func (m *SlotNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlotNumberResponse proto.InternalMessageInfo

func (m *SlotNumberResponse) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type GetBlockHashRequest struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashRequest) Reset()         { *m = GetBlockHashRequest{} }
func (m *GetBlockHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashRequest) ProtoMessage()    {}
func (*GetBlockHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *GetBlockHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashRequest.Unmarshal(m, b)
}
func (m *GetBlockHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashRequest.Merge(m, src)
}
func (m *GetBlockHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashRequest.Size(m)
}
func (m *GetBlockHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashRequest proto.InternalMessageInfo

func (m *GetBlockHashRequest) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type GetBlockHashResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashResponse) Reset()         { *m = GetBlockHashResponse{} }
func (m *GetBlockHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashResponse) ProtoMessage()    {}
func (*GetBlockHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{17}
}

func (m *GetBlockHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashResponse.Unmarshal(m, b)
}
func (m *GetBlockHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashResponse.Merge(m, src)
}
func (m *GetBlockHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashResponse.Size(m)
}
func (m *GetBlockHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashResponse proto.InternalMessageInfo

func (m *GetBlockHashResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ValidatorResponse struct {
	Pubkey               uint32   `protobuf:"varint,1,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	WithdrawalAddress    []byte   `protobuf:"bytes,2,opt,name=WithdrawalAddress,proto3" json:"WithdrawalAddress,omitempty"`
	WithdrawalShardID    uint32   `protobuf:"varint,3,opt,name=WithdrawalShardID,proto3" json:"WithdrawalShardID,omitempty"`
	RandaoCommitment     []byte   `protobuf:"bytes,4,opt,name=RandaoCommitment,proto3" json:"RandaoCommitment,omitempty"`
	RandaoLastChange     uint64   `protobuf:"varint,5,opt,name=RandaoLastChange,proto3" json:"RandaoLastChange,omitempty"`
	Balance              uint64   `protobuf:"varint,6,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	ExitSlot             uint64   `protobuf:"varint,8,opt,name=ExitSlot,proto3" json:"ExitSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorResponse) Reset()         { *m = ValidatorResponse{} }
func (m *ValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*ValidatorResponse) ProtoMessage()    {}
func (*ValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{18}
}

func (m *ValidatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorResponse.Unmarshal(m, b)
}
func (m *ValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorResponse.Marshal(b, m, deterministic)
}
func (m *ValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorResponse.Merge(m, src)
}
func (m *ValidatorResponse) XXX_Size() int {
	return xxx_messageInfo_ValidatorResponse.Size(m)
}
func (m *ValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorResponse proto.InternalMessageInfo

func (m *ValidatorResponse) GetPubkey() uint32 {
	if m != nil {
		return m.Pubkey
	}
	return 0
}

func (m *ValidatorResponse) GetWithdrawalAddress() []byte {
	if m != nil {
		return m.WithdrawalAddress
	}
	return nil
}

func (m *ValidatorResponse) GetWithdrawalShardID() uint32 {
	if m != nil {
		return m.WithdrawalShardID
	}
	return 0
}

func (m *ValidatorResponse) GetRandaoCommitment() []byte {
	if m != nil {
		return m.RandaoCommitment
	}
	return nil
}

func (m *ValidatorResponse) GetRandaoLastChange() uint64 {
	if m != nil {
		return m.RandaoLastChange
	}
	return 0
}

func (m *ValidatorResponse) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ValidatorResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ValidatorResponse) GetExitSlot() uint64 {
	if m != nil {
		return m.ExitSlot
	}
	return 0
}

type GetValidatorAtIndexRequest struct {
	Index                uint32   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorAtIndexRequest) Reset()         { *m = GetValidatorAtIndexRequest{} }
func (m *GetValidatorAtIndexRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorAtIndexRequest) ProtoMessage()    {}
func (*GetValidatorAtIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{19}
}

func (m *GetValidatorAtIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Unmarshal(m, b)
}
func (m *GetValidatorAtIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorAtIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorAtIndexRequest.Merge(m, src)
}
func (m *GetValidatorAtIndexRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorAtIndexRequest.Size(m)
}
func (m *GetValidatorAtIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorAtIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorAtIndexRequest proto.InternalMessageInfo

func (m *GetValidatorAtIndexRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type GetValidatorAtIndexResponse struct {
	Validator            *ValidatorResponse `protobuf:"bytes,1,opt,name=Validator,proto3" json:"Validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetValidatorAtIndexResponse) Reset()         { *m = GetValidatorAtIndexResponse{} }
func (m *GetValidatorAtIndexResponse) String() string { return proto.CompactTextString(m) }
func (*GetValidatorAtIndexResponse) ProtoMessage()    {}
func (*GetValidatorAtIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{20}
}

func (m *GetValidatorAtIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Unmarshal(m, b)
}
func (m *GetValidatorAtIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Marshal(b, m, deterministic)
}
func (m *GetValidatorAtIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorAtIndexResponse.Merge(m, src)
}
func (m *GetValidatorAtIndexResponse) XXX_Size() int {
	return xxx_messageInfo_GetValidatorAtIndexResponse.Size(m)
}
func (m *GetValidatorAtIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorAtIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorAtIndexResponse proto.InternalMessageInfo

func (m *GetValidatorAtIndexResponse) GetValidator() *ValidatorResponse {
	if m != nil {
		return m.Validator
	}
	return nil
}

type GetCommitteeValidatorsRequest struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	Shard                uint32   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommitteeValidatorsRequest) Reset()         { *m = GetCommitteeValidatorsRequest{} }
func (m *GetCommitteeValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorsRequest) ProtoMessage()    {}
func (*GetCommitteeValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{21}
}

func (m *GetCommitteeValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Marshal(b, m, deterministic)
}
func (m *GetCommitteeValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorsRequest.Merge(m, src)
}
func (m *GetCommitteeValidatorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorsRequest.Size(m)
}
func (m *GetCommitteeValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorsRequest proto.InternalMessageInfo

func (m *GetCommitteeValidatorsRequest) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *GetCommitteeValidatorsRequest) GetShard() uint32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

type GetCommitteeValidatorsResponse struct {
	Validators           []*ValidatorResponse `protobuf:"bytes,1,rep,name=Validators,proto3" json:"Validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetCommitteeValidatorsResponse) Reset()         { *m = GetCommitteeValidatorsResponse{} }
func (m *GetCommitteeValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommitteeValidatorsResponse) ProtoMessage()    {}
func (*GetCommitteeValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{22}
}

func (m *GetCommitteeValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Unmarshal(m, b)
}
func (m *GetCommitteeValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Marshal(b, m, deterministic)
}
func (m *GetCommitteeValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommitteeValidatorsResponse.Merge(m, src)
}
func (m *GetCommitteeValidatorsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommitteeValidatorsResponse.Size(m)
}
func (m *GetCommitteeValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommitteeValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommitteeValidatorsResponse proto.InternalMessageInfo

func (m *GetCommitteeValidatorsResponse) GetValidators() []*ValidatorResponse {
	if m != nil {
		return m.Validators
	}
	return nil
}

type Block struct {
	SlotNumber            uint64         `protobuf:"varint,1,opt,name=SlotNumber,proto3" json:"SlotNumber,omitempty"`
	RandaoReveal          []byte         `protobuf:"bytes,2,opt,name=RandaoReveal,proto3" json:"RandaoReveal,omitempty"`
	AncestorHashes        [][]byte       `protobuf:"bytes,3,rep,name=AncestorHashes,proto3" json:"AncestorHashes,omitempty"`
	ActiveStateRoot       []byte         `protobuf:"bytes,4,opt,name=ActiveStateRoot,proto3" json:"ActiveStateRoot,omitempty"`
	CrystallizedStateRoot []byte         `protobuf:"bytes,5,opt,name=CrystallizedStateRoot,proto3" json:"CrystallizedStateRoot,omitempty"`
	Attestations          []*Attestation `protobuf:"bytes,6,rep,name=Attestations,proto3" json:"Attestations,omitempty"`
	Specials              []*Special     `protobuf:"bytes,7,rep,name=Specials,proto3" json:"Specials,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{23}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *Block) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *Block) GetAncestorHashes() [][]byte {
	if m != nil {
		return m.AncestorHashes
	}
	return nil
}

func (m *Block) GetActiveStateRoot() []byte {
	if m != nil {
		return m.ActiveStateRoot
	}
	return nil
}

func (m *Block) GetCrystallizedStateRoot() []byte {
	if m != nil {
		return m.CrystallizedStateRoot
	}
	return nil
}

func (m *Block) GetAttestations() []*Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func (m *Block) GetSpecials() []*Special {
	if m != nil {
		return m.Specials
	}
	return nil
}

type Special struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Data                 [][]byte `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Special) Reset()         { *m = Special{} }
func (m *Special) String() string { return proto.CompactTextString(m) }
func (*Special) ProtoMessage()    {}
func (*Special) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{24}
}

func (m *Special) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Special.Unmarshal(m, b)
}
func (m *Special) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Special.Marshal(b, m, deterministic)
}
func (m *Special) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Special.Merge(m, src)
}
func (m *Special) XXX_Size() int {
	return xxx_messageInfo_Special.Size(m)
}
func (m *Special) XXX_DiscardUnknown() {
	xxx_messageInfo_Special.DiscardUnknown(m)
}

var xxx_messageInfo_Special proto.InternalMessageInfo

func (m *Special) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Special) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Attestation struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	ShardID              uint32   `protobuf:"varint,2,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	JustifiedSlot        uint64   `protobuf:"varint,3,opt,name=JustifiedSlot,proto3" json:"JustifiedSlot,omitempty"`
	JustifiedBlockHash   []byte   `protobuf:"bytes,4,opt,name=JustifiedBlockHash,proto3" json:"JustifiedBlockHash,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,5,opt,name=ShardBlockHash,proto3" json:"ShardBlockHash,omitempty"`
	ObliqueParentHashes  [][]byte `protobuf:"bytes,6,rep,name=ObliqueParentHashes,proto3" json:"ObliqueParentHashes,omitempty"`
	AttesterBitField     []byte   `protobuf:"bytes,7,opt,name=AttesterBitField,proto3" json:"AttesterBitField,omitempty"`
	AggregateSignature   []byte   `protobuf:"bytes,8,opt,name=AggregateSignature,proto3" json:"AggregateSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{25}
}

func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Attestation) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Attestation) GetJustifiedSlot() uint64 {
	if m != nil {
		return m.JustifiedSlot
	}
	return 0
}

func (m *Attestation) GetJustifiedBlockHash() []byte {
	if m != nil {
		return m.JustifiedBlockHash
	}
	return nil
}

func (m *Attestation) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *Attestation) GetObliqueParentHashes() [][]byte {
	if m != nil {
		return m.ObliqueParentHashes
	}
	return nil
}

func (m *Attestation) GetAttesterBitField() []byte {
	if m != nil {
		return m.AttesterBitField
	}
	return nil
}

func (m *Attestation) GetAggregateSignature() []byte {
	if m != nil {
		return m.AggregateSignature
	}
	return nil
}

type AttestationSignedData struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Slot                 uint64   `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Shard                uint32   `protobuf:"varint,3,opt,name=Shard,proto3" json:"Shard,omitempty"`
	ParentHashes         [][]byte `protobuf:"bytes,4,rep,name=ParentHashes,proto3" json:"ParentHashes,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,5,opt,name=ShardBlockHash,proto3" json:"ShardBlockHash,omitempty"`
	JustifiedSlot        uint64   `protobuf:"varint,6,opt,name=JustifiedSlot,proto3" json:"JustifiedSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationSignedData) Reset()         { *m = AttestationSignedData{} }
func (m *AttestationSignedData) String() string { return proto.CompactTextString(m) }
func (*AttestationSignedData) ProtoMessage()    {}
func (*AttestationSignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{26}
}

func (m *AttestationSignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationSignedData.Unmarshal(m, b)
}
func (m *AttestationSignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationSignedData.Marshal(b, m, deterministic)
}
func (m *AttestationSignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationSignedData.Merge(m, src)
}
func (m *AttestationSignedData) XXX_Size() int {
	return xxx_messageInfo_AttestationSignedData.Size(m)
}
func (m *AttestationSignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationSignedData.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationSignedData proto.InternalMessageInfo

func (m *AttestationSignedData) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AttestationSignedData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationSignedData) GetShard() uint32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *AttestationSignedData) GetParentHashes() [][]byte {
	if m != nil {
		return m.ParentHashes
	}
	return nil
}

func (m *AttestationSignedData) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *AttestationSignedData) GetJustifiedSlot() uint64 {
	if m != nil {
		return m.JustifiedSlot
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Role", Role_name, Role_value)
	proto.RegisterType((*ConnectionStatus)(nil), "pb.ConnectionStatus")
	proto.RegisterType((*Peer)(nil), "pb.Peer")
	proto.RegisterType((*SubscriptionRequest)(nil), "pb.SubscriptionRequest")
	proto.RegisterType((*Subscription)(nil), "pb.Subscription")
	proto.RegisterType((*GetPeersResponse)(nil), "pb.GetPeersResponse")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageAndTopic)(nil), "pb.MessageAndTopic")
	proto.RegisterType((*Peers)(nil), "pb.Peers")
	proto.RegisterType((*ConnectResponse)(nil), "pb.ConnectResponse")
	proto.RegisterType((*DisconnectResponse)(nil), "pb.DisconnectResponse")
	proto.RegisterType((*P2PSettings)(nil), "pb.P2PSettings")
	proto.RegisterType((*GetSlotAndShardAssignmentRequest)(nil), "pb.GetSlotAndShardAssignmentRequest")
	proto.RegisterType((*SlotAndShardAssignment)(nil), "pb.SlotAndShardAssignment")
	proto.RegisterType((*SubmitBlockRequest)(nil), "pb.SubmitBlockRequest")
	proto.RegisterType((*SubmitBlockResponse)(nil), "pb.SubmitBlockResponse")
	proto.RegisterType((*SlotNumberResponse)(nil), "pb.SlotNumberResponse")
	proto.RegisterType((*GetBlockHashRequest)(nil), "pb.GetBlockHashRequest")
	proto.RegisterType((*GetBlockHashResponse)(nil), "pb.GetBlockHashResponse")
	proto.RegisterType((*ValidatorResponse)(nil), "pb.ValidatorResponse")
	proto.RegisterType((*GetValidatorAtIndexRequest)(nil), "pb.GetValidatorAtIndexRequest")
	proto.RegisterType((*GetValidatorAtIndexResponse)(nil), "pb.GetValidatorAtIndexResponse")
	proto.RegisterType((*GetCommitteeValidatorsRequest)(nil), "pb.GetCommitteeValidatorsRequest")
	proto.RegisterType((*GetCommitteeValidatorsResponse)(nil), "pb.GetCommitteeValidatorsResponse")
	proto.RegisterType((*Block)(nil), "pb.Block")
	proto.RegisterType((*Special)(nil), "pb.Special")
	proto.RegisterType((*Attestation)(nil), "pb.Attestation")
	proto.RegisterType((*AttestationSignedData)(nil), "pb.AttestationSignedData")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 1269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xef, 0x72, 0xd3, 0x46,
	0x10, 0xaf, 0xff, 0xc4, 0x7f, 0xd6, 0x0e, 0x31, 0x17, 0x48, 0x55, 0x01, 0xc1, 0xbd, 0x61, 0x4a,
	0x0a, 0x1d, 0x43, 0x1d, 0x68, 0x99, 0xe9, 0x4c, 0x3b, 0x8e, 0x13, 0x52, 0x3a, 0xb4, 0x78, 0xce,
	0x01, 0x3e, 0x75, 0x3a, 0x67, 0x69, 0x71, 0x34, 0xc8, 0x92, 0xd1, 0x9d, 0x29, 0xe9, 0x3b, 0xf5,
	0x43, 0x9f, 0xa2, 0x1f, 0x3a, 0x7d, 0x92, 0xbe, 0x44, 0xe7, 0x4e, 0x27, 0x59, 0xb6, 0x64, 0xe0,
	0x9b, 0xf6, 0xb7, 0x7f, 0x6e, 0x6f, 0x77, 0x6f, 0x77, 0x05, 0xcd, 0x68, 0xee, 0xf4, 0xe6, 0x51,
	0x28, 0x43, 0x52, 0x9e, 0x4f, 0xec, 0x6b, 0xd3, 0x30, 0x9c, 0xfa, 0x78, 0x4f, 0x23, 0x93, 0xc5,
	0xab, 0x7b, 0x38, 0x9b, 0xcb, 0x8b, 0x58, 0x80, 0xde, 0x87, 0xce, 0x30, 0x0c, 0x02, 0x74, 0xa4,
	0x17, 0x06, 0x63, 0xc9, 0xe5, 0x42, 0x90, 0xeb, 0xd0, 0x34, 0x18, 0xba, 0x56, 0xa9, 0x5b, 0x3a,
	0x68, 0xb0, 0x25, 0x40, 0xbb, 0x50, 0x1d, 0x21, 0x46, 0xc4, 0x82, 0xfa, 0xc0, 0x75, 0x23, 0x14,
	0x42, 0xcb, 0x34, 0x59, 0x42, 0xd2, 0xbb, 0xb0, 0x3b, 0x5e, 0x4c, 0x84, 0x13, 0x79, 0x73, 0x65,
	0x95, 0xe1, 0x9b, 0x05, 0x0a, 0x49, 0xae, 0xc0, 0xd6, 0x59, 0x38, 0xf7, 0x1c, 0x23, 0x1e, 0x13,
	0x74, 0x1f, 0xda, 0x59, 0x61, 0x72, 0x09, 0xca, 0x4f, 0x8e, 0xb5, 0x48, 0x95, 0x95, 0x9f, 0x1c,
	0xd3, 0x3e, 0x74, 0x4e, 0x51, 0xaa, 0x13, 0x05, 0x43, 0x31, 0x0f, 0x03, 0x81, 0x64, 0x1f, 0xb6,
	0x34, 0x60, 0x95, 0xba, 0x95, 0x83, 0x56, 0xbf, 0xd1, 0x9b, 0x4f, 0x7a, 0x0a, 0x60, 0x31, 0x4c,
	0x6f, 0x40, 0xfd, 0x67, 0x14, 0x82, 0x4f, 0x91, 0x10, 0xa8, 0x1e, 0x73, 0xc9, 0xb5, 0xc1, 0x36,
	0xd3, 0xdf, 0xf4, 0x3b, 0xd8, 0x31, 0xec, 0x41, 0xe0, 0x6a, 0x2f, 0x8a, 0xc4, 0x96, 0xfe, 0x96,
	0xb3, 0xfe, 0xde, 0x36, 0x67, 0x7f, 0xd0, 0x89, 0xbb, 0xb0, 0x63, 0x82, 0x96, 0xfa, 0x6d, 0x41,
	0x7d, 0xbc, 0x70, 0x9c, 0x24, 0x64, 0x0d, 0x96, 0x90, 0xb4, 0x07, 0xe4, 0xd8, 0x13, 0xce, 0x47,
	0xcb, 0x6f, 0x43, 0x6b, 0xd4, 0x1f, 0x8d, 0x51, 0x4a, 0x2f, 0x98, 0x0a, 0x7a, 0x0c, 0xdd, 0x53,
	0x94, 0x63, 0x3f, 0x94, 0x83, 0xc0, 0x1d, 0x9f, 0xf3, 0xc8, 0x1d, 0x08, 0xe1, 0x4d, 0x83, 0x19,
	0x06, 0x32, 0x09, 0x7f, 0x17, 0x5a, 0x2f, 0xb8, 0xef, 0xb9, 0x5c, 0x86, 0x91, 0x89, 0xf0, 0x36,
	0xcb, 0x42, 0xd4, 0x85, 0xbd, 0x62, 0x13, 0xda, 0x11, 0x05, 0xa5, 0x7a, 0x09, 0xa9, 0x02, 0xa7,
	0x74, 0x74, 0x8c, 0xaa, 0x4c, 0x7f, 0x93, 0xeb, 0x50, 0x65, 0xa1, 0x8f, 0x56, 0xa5, 0x5b, 0x3a,
	0xb8, 0x14, 0x07, 0x46, 0xd1, 0x4c, 0xa3, 0xf4, 0x21, 0x90, 0xf1, 0x62, 0x32, 0xf3, 0xe4, 0x91,
	0x1f, 0x3a, 0xaf, 0x13, 0xef, 0x6e, 0xc2, 0x96, 0xa6, 0xb5, 0xfd, 0x56, 0xbf, 0xa9, 0x94, 0x62,
	0x81, 0x18, 0xa7, 0x87, 0xba, 0xa8, 0x96, 0x6a, 0x26, 0x44, 0xd7, 0xa1, 0xa9, 0x81, 0x1f, 0xb9,
	0x38, 0x37, 0xd9, 0x5b, 0x02, 0xf4, 0x01, 0x10, 0xe5, 0xd1, 0x2f, 0x8b, 0xd9, 0x04, 0xa3, 0x4c,
	0xf9, 0xc0, 0x12, 0x35, 0xa5, 0x96, 0x41, 0xe8, 0x43, 0xd8, 0x3d, 0x45, 0x99, 0x5a, 0x49, 0x5c,
	0xfc, 0x90, 0xda, 0x1d, 0xb8, 0xb2, 0xaa, 0x66, 0x8e, 0x23, 0x50, 0xcd, 0x78, 0xa7, 0xbf, 0xe9,
	0x9f, 0x65, 0xb8, 0x9c, 0x86, 0x3e, 0x95, 0xdc, 0x83, 0xda, 0x68, 0x31, 0x79, 0x8d, 0x17, 0x26,
	0xca, 0x86, 0x22, 0x5f, 0xc1, 0xe5, 0x97, 0x9e, 0x3c, 0x77, 0x23, 0xfe, 0x3b, 0xf7, 0x93, 0x47,
	0x57, 0xd6, 0xe6, 0xf2, 0x8c, 0x55, 0xe9, 0x24, 0x6d, 0x15, 0x6d, 0x30, 0xcf, 0x20, 0x77, 0xa0,
	0xc3, 0x78, 0xe0, 0xf2, 0x70, 0x18, 0xce, 0x66, 0x9e, 0x54, 0xe9, 0xb6, 0xaa, 0xda, 0x74, 0x0e,
	0x5f, 0xca, 0x3e, 0xe5, 0x42, 0x0e, 0xcf, 0x79, 0x30, 0x45, 0x6b, 0x4b, 0xc7, 0x21, 0x87, 0xab,
	0x92, 0x39, 0xe2, 0x3e, 0x0f, 0x1c, 0xb4, 0x6a, 0x5a, 0x24, 0x21, 0xd5, 0x2d, 0xe3, 0x46, 0x63,
	0xd5, 0xe3, 0x5b, 0x9a, 0xb6, 0x63, 0x43, 0xe3, 0xe4, 0x9d, 0xa7, 0xab, 0xd8, 0x6a, 0x68, 0x95,
	0x94, 0xa6, 0x7d, 0xb0, 0x4f, 0x51, 0xa6, 0x11, 0x1b, 0xc8, 0x27, 0x81, 0x8b, 0xef, 0x32, 0x9d,
	0x45, 0xd3, 0x26, 0x6c, 0x31, 0x41, 0x19, 0x5c, 0x2b, 0xd4, 0x31, 0xc1, 0x3e, 0x84, 0x66, 0xca,
	0x33, 0x55, 0x77, 0x55, 0x55, 0x5d, 0x2e, 0x2d, 0x6c, 0x29, 0x47, 0x9f, 0xc3, 0x8d, 0x53, 0x94,
	0x71, 0x48, 0x24, 0x62, 0xca, 0x10, 0x1f, 0x59, 0x24, 0xca, 0x55, 0x1d, 0x79, 0x9d, 0xbe, 0x6d,
	0x16, 0x13, 0xf4, 0x25, 0xec, 0x6f, 0x32, 0x6b, 0xbc, 0x7d, 0x08, 0xb0, 0x44, 0x4d, 0xcb, 0xd9,
	0xe0, 0x6e, 0x46, 0x90, 0xfe, 0x55, 0x36, 0xef, 0xea, 0x83, 0x8e, 0x51, 0x68, 0xc7, 0x39, 0x64,
	0xf8, 0x16, 0xb9, 0x6f, 0xca, 0x6b, 0x05, 0x23, 0x5f, 0xc0, 0xa5, 0x41, 0xe0, 0xa0, 0x90, 0x61,
	0xa4, 0xaa, 0x18, 0x85, 0x55, 0xe9, 0x56, 0x0e, 0xda, 0x6c, 0x0d, 0x25, 0x07, 0xb0, 0x33, 0x70,
	0xa4, 0xf7, 0x16, 0x55, 0x66, 0x91, 0x85, 0x61, 0x52, 0x52, 0xeb, 0x30, 0x79, 0x00, 0x57, 0x87,
	0xd1, 0x85, 0x90, 0xdc, 0xf7, 0xbd, 0x3f, 0xd0, 0x5d, 0xca, 0x6f, 0x69, 0xf9, 0x62, 0x26, 0x39,
	0x84, 0xf6, 0x40, 0x4a, 0x14, 0x92, 0xab, 0x91, 0x21, 0xac, 0x9a, 0x0e, 0xc7, 0x8e, 0x0a, 0x47,
	0x06, 0x67, 0x2b, 0x42, 0xe4, 0x36, 0x34, 0xc6, 0x73, 0x74, 0x3c, 0xee, 0xab, 0xc2, 0x53, 0x0a,
	0x2d, 0xa5, 0x60, 0x30, 0x96, 0x32, 0xe9, 0xd7, 0x50, 0x37, 0xdf, 0xea, 0xe9, 0x9e, 0x5d, 0xcc,
	0xd1, 0xd4, 0x95, 0xfe, 0x4e, 0x47, 0x45, 0x59, 0x5f, 0x3d, 0x9e, 0x28, 0x7f, 0x97, 0xa1, 0x95,
	0x39, 0x2c, 0xed, 0x8a, 0xa5, 0x4c, 0x57, 0xcc, 0xf4, 0xd0, 0xf2, 0x6a, 0x0f, 0xbd, 0x05, 0xdb,
	0x3f, 0x2d, 0x84, 0xf4, 0x5e, 0x79, 0xe8, 0x6a, 0xb5, 0x8a, 0x56, 0x5b, 0x05, 0x49, 0x0f, 0x48,
	0x0a, 0x2c, 0x5b, 0x5e, 0x1c, 0xd7, 0x02, 0x8e, 0x4a, 0x96, 0x3e, 0x60, 0x29, 0x1b, 0xc7, 0x74,
	0x0d, 0x25, 0xf7, 0x61, 0xf7, 0xd9, 0xc4, 0xf7, 0xde, 0x2c, 0x70, 0xc4, 0x23, 0x0c, 0xa4, 0xc9,
	0x6c, 0x4d, 0x5f, 0xaf, 0x88, 0xa5, 0xda, 0x40, 0x7c, 0x59, 0x8c, 0x8e, 0x3c, 0xf9, 0xd8, 0x43,
	0xdf, 0xd5, 0x4f, 0xb9, 0xcd, 0x72, 0xb8, 0xf2, 0x7a, 0x30, 0x9d, 0x46, 0x38, 0xe5, 0x12, 0xc7,
	0xde, 0x34, 0xe0, 0x72, 0x11, 0xa1, 0x7e, 0xde, 0x6d, 0x56, 0xc0, 0xa1, 0xff, 0x96, 0xe0, 0x6a,
	0x26, 0x92, 0x8a, 0x81, 0xae, 0x1e, 0xc7, 0x16, 0xd4, 0x5f, 0x60, 0x24, 0xbc, 0x30, 0x48, 0x66,
	0x90, 0x21, 0x0b, 0x67, 0x50, 0xfa, 0xce, 0x2a, 0x99, 0x77, 0xa6, 0x8a, 0x7c, 0xe5, 0x92, 0x55,
	0x7d, 0xc9, 0x15, 0xec, 0xa3, 0xe3, 0x96, 0xcb, 0x5a, 0xad, 0x20, 0x6b, 0x77, 0x68, 0x3c, 0x0b,
	0x49, 0x1b, 0x1a, 0x83, 0xb3, 0xb3, 0x93, 0xf1, 0xd9, 0x09, 0xeb, 0x7c, 0xa2, 0xa8, 0x11, 0x7b,
	0x36, 0x7a, 0x36, 0x3e, 0x61, 0x9d, 0x52, 0xff, 0xbf, 0x0a, 0x6c, 0x6b, 0xbb, 0xce, 0x39, 0xf7,
	0x02, 0x36, 0x1a, 0x92, 0xef, 0xa1, 0x95, 0x19, 0x76, 0x64, 0x4f, 0x17, 0x6a, 0x6e, 0x68, 0xda,
	0x9f, 0xe6, 0x70, 0xd3, 0x2d, 0x7e, 0x80, 0x6d, 0xb3, 0x0f, 0x98, 0xd7, 0xbd, 0xd7, 0x8b, 0x97,
	0xc0, 0x5e, 0xb2, 0x04, 0xf6, 0x4e, 0xd4, 0x12, 0x68, 0xc7, 0x96, 0xf3, 0x23, 0x72, 0x00, 0xed,
	0xec, 0x2c, 0x23, 0xfa, 0xa4, 0x82, 0xa1, 0x68, 0x5b, 0x79, 0x86, 0x31, 0xf1, 0x2b, 0x7c, 0xb6,
	0x71, 0x27, 0x21, 0xb7, 0x8c, 0xda, 0x7b, 0x57, 0x16, 0xdb, 0x4e, 0xbc, 0x2b, 0xb0, 0xf0, 0x42,
	0x0f, 0xe9, 0xf5, 0xee, 0x4e, 0xf6, 0x8d, 0xe1, 0x0d, 0xa3, 0xc2, 0xbe, 0xb9, 0x91, 0x6f, 0xdc,
	0xfe, 0x0d, 0xf6, 0x8a, 0x5b, 0x31, 0xf9, 0xdc, 0xa8, 0x6e, 0xee, 0xfe, 0x36, 0x7d, 0x9f, 0x48,
	0x7c, 0x40, 0xff, 0x9f, 0x0a, 0xd4, 0x46, 0xfd, 0x91, 0x4a, 0xf3, 0x50, 0xdf, 0x21, 0xb7, 0x7f,
	0x6f, 0x4a, 0xd6, 0x15, 0x65, 0x3d, 0x27, 0xfd, 0x08, 0x1a, 0xc9, 0x82, 0xfc, 0x7e, 0xcd, 0xdc,
	0x1a, 0xfd, 0x0d, 0x34, 0xcd, 0xea, 0x3d, 0x41, 0x92, 0xd4, 0xd2, 0xfa, 0xda, 0x6e, 0x77, 0xd6,
	0x19, 0xe4, 0x01, 0x5c, 0x7e, 0xea, 0x09, 0x89, 0xc1, 0xe3, 0x30, 0x32, 0x8b, 0xb4, 0x20, 0x39,
	0x31, 0x5b, 0xb7, 0x57, 0xc3, 0xbf, 0x5f, 0x22, 0xdf, 0x42, 0xeb, 0x79, 0x20, 0xd2, 0xf3, 0xf2,
	0xf2, 0x1b, 0x9c, 0x27, 0x5f, 0x42, 0xdd, 0x5c, 0x9a, 0x34, 0x93, 0x25, 0x5b, 0xd8, 0xbb, 0x99,
	0x60, 0x64, 0x6e, 0xd4, 0x52, 0x45, 0x65, 0xd6, 0xe2, 0x8d, 0xe1, 0xd0, 0x93, 0x22, 0xb3, 0x3f,
	0x93, 0x47, 0xd0, 0x3c, 0x8a, 0x42, 0xee, 0x3a, 0x5c, 0x48, 0xb2, 0x9b, 0xf1, 0x3b, 0xf9, 0x41,
	0xd8, 0xe4, 0xdc, 0xa4, 0xa6, 0xe9, 0xc3, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x42, 0x54, 0xff,
	0x51, 0x74, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainRPCClient is the client API for BlockchainRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainRPCClient interface {
	SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
	GetSlotNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SlotNumberResponse, error)
	GetBlockHash(ctx context.Context, in *GetBlockHashRequest, opts ...grpc.CallOption) (*GetBlockHashResponse, error)
	GetSlotAndShardAssignment(ctx context.Context, in *GetSlotAndShardAssignmentRequest, opts ...grpc.CallOption) (*SlotAndShardAssignment, error)
	GetValidatorAtIndex(ctx context.Context, in *GetValidatorAtIndexRequest, opts ...grpc.CallOption) (*GetValidatorAtIndexResponse, error)
	GetCommitteeValidators(ctx context.Context, in *GetCommitteeValidatorsRequest, opts ...grpc.CallOption) (*GetCommitteeValidatorsResponse, error)
}

type blockchainRPCClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainRPCClient(cc *grpc.ClientConn) BlockchainRPCClient {
	return &blockchainRPCClient{cc}
}

func (c *blockchainRPCClient) SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/SubmitBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetSlotNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SlotNumberResponse, error) {
	out := new(SlotNumberResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetSlotNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetBlockHash(ctx context.Context, in *GetBlockHashRequest, opts ...grpc.CallOption) (*GetBlockHashResponse, error) {
	out := new(GetBlockHashResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetSlotAndShardAssignment(ctx context.Context, in *GetSlotAndShardAssignmentRequest, opts ...grpc.CallOption) (*SlotAndShardAssignment, error) {
	out := new(SlotAndShardAssignment)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetSlotAndShardAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetValidatorAtIndex(ctx context.Context, in *GetValidatorAtIndexRequest, opts ...grpc.CallOption) (*GetValidatorAtIndexResponse, error) {
	out := new(GetValidatorAtIndexResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetValidatorAtIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainRPCClient) GetCommitteeValidators(ctx context.Context, in *GetCommitteeValidatorsRequest, opts ...grpc.CallOption) (*GetCommitteeValidatorsResponse, error) {
	out := new(GetCommitteeValidatorsResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainRPC/GetCommitteeValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainRPCServer is the server API for BlockchainRPC service.
type BlockchainRPCServer interface {
	SubmitBlock(context.Context, *SubmitBlockRequest) (*SubmitBlockResponse, error)
	GetSlotNumber(context.Context, *empty.Empty) (*SlotNumberResponse, error)
	GetBlockHash(context.Context, *GetBlockHashRequest) (*GetBlockHashResponse, error)
	GetSlotAndShardAssignment(context.Context, *GetSlotAndShardAssignmentRequest) (*SlotAndShardAssignment, error)
	GetValidatorAtIndex(context.Context, *GetValidatorAtIndexRequest) (*GetValidatorAtIndexResponse, error)
	GetCommitteeValidators(context.Context, *GetCommitteeValidatorsRequest) (*GetCommitteeValidatorsResponse, error)
}

func RegisterBlockchainRPCServer(s *grpc.Server, srv BlockchainRPCServer) {
	s.RegisterService(&_BlockchainRPC_serviceDesc, srv)
}

func _BlockchainRPC_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/SubmitBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).SubmitBlock(ctx, req.(*SubmitBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetSlotNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetSlotNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetSlotNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetSlotNumber(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetBlockHash(ctx, req.(*GetBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetSlotAndShardAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotAndShardAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetSlotAndShardAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetSlotAndShardAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetSlotAndShardAssignment(ctx, req.(*GetSlotAndShardAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetValidatorAtIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorAtIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetValidatorAtIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetValidatorAtIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetValidatorAtIndex(ctx, req.(*GetValidatorAtIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainRPC_GetCommitteeValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitteeValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainRPCServer).GetCommitteeValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainRPC/GetCommitteeValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainRPCServer).GetCommitteeValidators(ctx, req.(*GetCommitteeValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockchainRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlockchainRPC",
	HandlerType: (*BlockchainRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBlock",
			Handler:    _BlockchainRPC_SubmitBlock_Handler,
		},
		{
			MethodName: "GetSlotNumber",
			Handler:    _BlockchainRPC_GetSlotNumber_Handler,
		},
		{
			MethodName: "GetBlockHash",
			Handler:    _BlockchainRPC_GetBlockHash_Handler,
		},
		{
			MethodName: "GetSlotAndShardAssignment",
			Handler:    _BlockchainRPC_GetSlotAndShardAssignment_Handler,
		},
		{
			MethodName: "GetValidatorAtIndex",
			Handler:    _BlockchainRPC_GetValidatorAtIndex_Handler,
		},
		{
			MethodName: "GetCommitteeValidators",
			Handler:    _BlockchainRPC_GetCommitteeValidators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// P2PRPCClient is the client API for P2PRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type P2PRPCClient interface {
	GetConnectionStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ConnectionStatus, error)
	GetPeers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetPeersResponse, error)
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*Subscription, error)
	ListenForMessages(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (P2PRPC_ListenForMessagesClient, error)
	Unsubscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*empty.Empty, error)
	Connect(ctx context.Context, in *Peers, opts ...grpc.CallOption) (*ConnectResponse, error)
	GetSettings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*P2PSettings, error)
	Broadcast(ctx context.Context, in *MessageAndTopic, opts ...grpc.CallOption) (*empty.Empty, error)
}

type p2PRPCClient struct {
	cc *grpc.ClientConn
}

func NewP2PRPCClient(cc *grpc.ClientConn) P2PRPCClient {
	return &p2PRPCClient{cc}
}

func (c *p2PRPCClient) GetConnectionStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ConnectionStatus, error) {
	out := new(ConnectionStatus)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/GetConnectionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PRPCClient) GetPeers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/GetPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PRPCClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*Subscription, error) {
	out := new(Subscription)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PRPCClient) ListenForMessages(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (P2PRPC_ListenForMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_P2PRPC_serviceDesc.Streams[0], "/pb.P2PRPC/ListenForMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &p2PRPCListenForMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type P2PRPC_ListenForMessagesClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type p2PRPCListenForMessagesClient struct {
	grpc.ClientStream
}

func (x *p2PRPCListenForMessagesClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *p2PRPCClient) Unsubscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PRPCClient) Connect(ctx context.Context, in *Peers, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PRPCClient) GetSettings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*P2PSettings, error) {
	out := new(P2PSettings)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/GetSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PRPCClient) Broadcast(ctx context.Context, in *MessageAndTopic, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.P2PRPC/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// P2PRPCServer is the server API for P2PRPC service.
type P2PRPCServer interface {
	GetConnectionStatus(context.Context, *empty.Empty) (*ConnectionStatus, error)
	GetPeers(context.Context, *empty.Empty) (*GetPeersResponse, error)
	Subscribe(context.Context, *SubscriptionRequest) (*Subscription, error)
	ListenForMessages(*Subscription, P2PRPC_ListenForMessagesServer) error
	Unsubscribe(context.Context, *Subscription) (*empty.Empty, error)
	Connect(context.Context, *Peers) (*ConnectResponse, error)
	GetSettings(context.Context, *empty.Empty) (*P2PSettings, error)
	Broadcast(context.Context, *MessageAndTopic) (*empty.Empty, error)
}

func RegisterP2PRPCServer(s *grpc.Server, srv P2PRPCServer) {
	s.RegisterService(&_P2PRPC_serviceDesc, srv)
}

func _P2PRPC_GetConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).GetConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/GetConnectionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).GetConnectionStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PRPC_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/GetPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).GetPeers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PRPC_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).Subscribe(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PRPC_ListenForMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PRPCServer).ListenForMessages(m, &p2PRPCListenForMessagesServer{stream})
}

type P2PRPC_ListenForMessagesServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type p2PRPCListenForMessagesServer struct {
	grpc.ServerStream
}

func (x *p2PRPCListenForMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _P2PRPC_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).Unsubscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PRPC_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).Connect(ctx, req.(*Peers))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PRPC_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/GetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).GetSettings(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PRPC_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageAndTopic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PRPCServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.P2PRPC/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PRPCServer).Broadcast(ctx, req.(*MessageAndTopic))
	}
	return interceptor(ctx, in, info, handler)
}

var _P2PRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.P2PRPC",
	HandlerType: (*P2PRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnectionStatus",
			Handler:    _P2PRPC_GetConnectionStatus_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _P2PRPC_GetPeers_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _P2PRPC_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _P2PRPC_Unsubscribe_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _P2PRPC_Connect_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _P2PRPC_GetSettings_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _P2PRPC_Broadcast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenForMessages",
			Handler:       _P2PRPC_ListenForMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
